### PR TITLE
feature/chromeTabs -> dev

### PR DESCRIPTION
**Pull request by geogor37**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/548)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 23 of 24 files at r1.
Review status: 23 of 24 files reviewed at latest revision, all discussions resolved.

---

*[app/src/main/java/edu/byu/suite/features/external/MyBookListActivity.kt, line 10 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/548#-LBZcNzv5-gPho1uGik4:-LBZcNzv5-gPho1uGik5:b-kkoljg) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f794bf5caa065ba383abfcf261c93b9dc9a55678/app/src/main/java/edu/byu/suite/features/external/MyBookListActivity.kt#L10)):*
> ```Kotlin
> 
> class MyBookListActivity: ByuChromeTabsActivity() {
> 	override fun getUrl() = "https://booklist.byu.edu/Home/Mybooklist"
> ```

Is there a reason these are capital? Base URLs automatically switch everything to lower case anyways... Check if iOS has capitals

---

*[app/src/main/java/edu/byu/suite/features/external/MyByuActivity.kt, line 9 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/548#-LBZcVSf45GEsXYIuN3V:-LBZcVSf45GEsXYIuN3W:b-ya81ng) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f794bf5caa065ba383abfcf261c93b9dc9a55678/app/src/main/java/edu/byu/suite/features/external/MyByuActivity.kt#L9)):*
> ```Kotlin
>  */
> class MyByuActivity: ByuChromeTabsActivity() {
> 	override fun getUrl() = "https://cas.byu.edu/cas/login?service=https://my.byu.edu/uPortal/Login"
> ```

Same as above

---

*[app/src/main/java/edu/byu/suite/features/external/SaltLakeCenterActivity.kt, line 6 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/548#-LBZcd6J7p6QJAiTm9Ob:-LBZcd6J7p6QJAiTm9Oc:b-l5773k) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f794bf5caa065ba383abfcf261c93b9dc9a55678/app/src/main/java/edu/byu/suite/features/external/SaltLakeCenterActivity.kt#L6)):*
> ```Kotlin
> 
> class SaltLakeCenterActivity: ByuChromeTabsActivity() {
> 	override fun getUrl() = "http://ce.byu.edu/sl/"
> ```

Is this a typo? Should it be ces.byu.edu? It could be right, just thought I'd check

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/548)*

**Comment by romrell4** [comment]
Reviewed 1 of 24 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/activity/ByuChromeTabsActivity.kt, line 22 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/548#-LB_AeNg67cU7VUSPlwt:-LB_AeNg67cU7VUSPlwu:b-k6bt6o) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f794bf5caa065ba383abfcf261c93b9dc9a55678/support/src/main/java/edu/byu/support/activity/ByuChromeTabsActivity.kt#L22)):*
> ```Kotlin
> 	override fun onCreate(savedInstanceState: Bundle?) {
> 		super.onCreate(savedInstanceState)
> 		val toolbarColor = ContextCompat.getColor(this, R.color.colorPrimary)
> ```

Inline this

---

*[support/src/main/java/edu/byu/support/activity/ByuChromeTabsActivity.kt, line 27 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/548#-LB_AI087KRjBMX41l7h:-LB_AI087KRjBMX41l7i:b-90cxf0) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f794bf5caa065ba383abfcf261c93b9dc9a55678/support/src/main/java/edu/byu/support/activity/ByuChromeTabsActivity.kt#L27)):*
> ```Kotlin
> 			override fun onCustomTabsServiceConnected(name: ComponentName, client: CustomTabsClient) {
> 				// We have to pass in a CustomTabsSession to the intent builder in order for the behavior described above to work correctly
> 				CustomTabsIntent.Builder(client.newSession(object: CustomTabsCallback() {
> ```

Can't this be a lambda instead of an anonymous inner class? (IntelliJ should give you a shortcut to do it)

---

*[support/src/main/java/edu/byu/support/activity/ByuChromeTabsActivity.kt, line 35 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/548#-LB_AmiaClDvSpgU_ZS6:-LB_AmiaClDvSpgU_ZS7:b-8etyio) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f794bf5caa065ba383abfcf261c93b9dc9a55678/support/src/main/java/edu/byu/support/activity/ByuChromeTabsActivity.kt#L35)):*
> ```Kotlin
> 						}
> 					}
> 				})).setToolbarColor(toolbarColor).build().launchUrl(this@ByuChromeTabsActivity, Uri.parse(getUrl()))
> ```

In a newer version of kotlin, it was announced that they would add a `.toUri` method to the String class. Check if we can use that, or if it exists yet

---

*[support/src/main/java/edu/byu/support/activity/ByuChromeTabsActivity.kt, line 41 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/548#-LB_AwoJ8pyKxPyGYIr3:-LB_AwoJ8pyKxPyGYIr4:b-ya81ng) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f794bf5caa065ba383abfcf261c93b9dc9a55678/support/src/main/java/edu/byu/support/activity/ByuChromeTabsActivity.kt#L41)):*
> ```Kotlin
> 		}
> 		if (!CustomTabsClient.bindCustomTabsService(this, ByuActivity.CHROME_PACKAGE, connection)) {
> 			useDefaultBrowser(Uri.parse(getUrl()))
> ```

Same as above

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/548)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/external/MyBookListActivity.kt, line 10 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/548#-LBZcNzv5-gPho1uGik4:-LC4rMjo86cJsMLFtifl:b-xyw1b7) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f794bf5caa065ba383abfcf261c93b9dc9a55678/app/src/main/java/edu/byu/suite/features/external/MyBookListActivity.kt#L10)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Is there a reason these are capital? Base URLs automatically switch everything to lower case anyways... Check if iOS has capitals
</blockquote></details>

No, it works fine without the capitals.  iOS is currently using capitals as well.

---

*[app/src/main/java/edu/byu/suite/features/external/MyByuActivity.kt, line 9 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/548#-LBZcVSf45GEsXYIuN3V:-LC4sk08ERO1_yFZzRgy:bponlxe) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f794bf5caa065ba383abfcf261c93b9dc9a55678/app/src/main/java/edu/byu/suite/features/external/MyByuActivity.kt#L9)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

This one doesn't work without the capitals.

---

*[app/src/main/java/edu/byu/suite/features/external/SaltLakeCenterActivity.kt, line 6 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/548#-LBZcd6J7p6QJAiTm9Ob:-LC4t03gDw2DEoKqmhna:bdkbmre) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f794bf5caa065ba383abfcf261c93b9dc9a55678/app/src/main/java/edu/byu/suite/features/external/SaltLakeCenterActivity.kt#L6)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Is this a typo? Should it be ces.byu.edu? It could be right, just thought I'd check
</blockquote></details>

Nope that's right.

---

*[support/src/main/java/edu/byu/support/activity/ByuChromeTabsActivity.kt, line 22 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/548#-LB_AeNg67cU7VUSPlwt:-LC4tlcC-Im6pWSaa9cV:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f794bf5caa065ba383abfcf261c93b9dc9a55678/support/src/main/java/edu/byu/support/activity/ByuChromeTabsActivity.kt#L22)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Inline this
</blockquote></details>

Done.

---

*[support/src/main/java/edu/byu/support/activity/ByuChromeTabsActivity.kt, line 27 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/548#-LB_AI087KRjBMX41l7h:-LC4u8Jk3Csh-t5d2Wyq:b-w7iflz) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f794bf5caa065ba383abfcf261c93b9dc9a55678/support/src/main/java/edu/byu/support/activity/ByuChromeTabsActivity.kt#L27)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Can't this be a lambda instead of an anonymous inner class? (IntelliJ should give you a shortcut to do it)
</blockquote></details>

No, I don't think it can be a lambda because there are other methods in the CustomTabsCallback class that could be overridden, we're just not using them here.

---

*[support/src/main/java/edu/byu/support/activity/ByuChromeTabsActivity.kt, line 35 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/548#-LB_AmiaClDvSpgU_ZS6:-LC4udC5-cscerWRYTTD:b-jh8r66) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f794bf5caa065ba383abfcf261c93b9dc9a55678/support/src/main/java/edu/byu/support/activity/ByuChromeTabsActivity.kt#L35)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

In a newer version of kotlin, it was announced that they would add a `.toUri` method to the String class. Check if we can use that, or if it exists yet
</blockquote></details>

Doesn't look like that exists yet

---

*[support/src/main/java/edu/byu/support/activity/ByuChromeTabsActivity.kt, line 41 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/548#-LB_AwoJ8pyKxPyGYIr3:-LC4ugFbCXaS3X4est2M:b-q64pkt) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f794bf5caa065ba383abfcf261c93b9dc9a55678/support/src/main/java/edu/byu/support/activity/ByuChromeTabsActivity.kt#L41)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

See above.

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/548)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/external/MyBookListActivity.kt, line 10 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/548#-LBZcNzv5-gPho1uGik4:-LC5o19OAer-s3L_rayK:b-dwkaeu) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f794bf5caa065ba383abfcf261c93b9dc9a55678/app/src/main/java/edu/byu/suite/features/external/MyBookListActivity.kt#L10)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

No, it works fine without the capitals.  iOS is currently using capitals as well.
</blockquote></details>

Tell Erik to change that (add to VTB)

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/548)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/external/MyBookListActivity.kt, line 10 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/548#-LBZcNzv5-gPho1uGik4:-LCAjsuZ0HWX5yLRfWAY:b-e6qept) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f794bf5caa065ba383abfcf261c93b9dc9a55678/app/src/main/java/edu/byu/suite/features/external/MyBookListActivity.kt#L10)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Tell Erik to change that (add to VTB)
</blockquote></details>

I can just do it if you want since it's a super easy fix and I already know where it is.

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/548)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/external/MyBookListActivity.kt, line 10 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/548#-LBZcNzv5-gPho1uGik4:-LCD2REb40TbIFLdktfy:b-1x9rui) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f794bf5caa065ba383abfcf261c93b9dc9a55678/app/src/main/java/edu/byu/suite/features/external/MyBookListActivity.kt#L10)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

I can just do it if you want since it's a super easy fix and I already know where it is.
</blockquote></details>

Do it. Make a PR

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/548)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/external/MyBookListActivity.kt, line 10 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/548#-LBZcNzv5-gPho1uGik4:-LCEgGnO8ok-mqZR8tCX:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f794bf5caa065ba383abfcf261c93b9dc9a55678/app/src/main/java/edu/byu/suite/features/external/MyBookListActivity.kt#L10)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do it. Make a PR
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/548)*

**Pull request merged**
