### PR TITLE
feature/chromeTabs -> dev

### PR DESCRIPTION
**Pull request by geogor37**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/467)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/467)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/467#-KwkACU9kUWxYy6zxhba:-KwkACU9kUWxYy6zxhbb:bfq9bgj) (no related file):*
Switch all web views to Chrome Tabs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/467)*

**Comment by geogor37** [comment]
Review status: 8 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/467#-KwkACU9kUWxYy6zxhba:-KwkU0ENVzqqegN3b0di:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Switch all web views to Chrome Tabs
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/467)*

**Comment by romrell4** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/467)*

**Pull request merged**
