### PR TITLE
hotfix/addDrop -> dev

### PR DESCRIPTION
**Pull request by geogor37**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/537)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[app/src/main/res/layout/add_drop_fragment_meta.xml, line 2 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/537#-LB3JyQr2wW2p74dWKOu:-LB3JyQr2wW2p74dWKOv:b-uifjy0) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/37f5968da027f6bc46fdb853b8b485103200c657/app/src/main/res/layout/add_drop_fragment_meta.xml#L2)):*
> ```XML
> <?xml version="1.0" encoding="utf-8"?>
> <android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
> ```

What was the bug?

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/537)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/res/layout/add_drop_fragment_meta.xml, line 21 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/537#-LB3K68D4K9qcUyS2hbh:-LB3K68D4K9qcUyS2hbi:bvl98rn) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/37f5968da027f6bc46fdb853b8b485103200c657/app/src/main/res/layout/add_drop_fragment_meta.xml#L21)):*
> ```XML
> 		android:layout_width="0dp"
> 		android:layout_height="wrap_content"
> 		android:layout_alignParentBottom="true"
> ```

Do you need this in a constraint layout?

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/537)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/res/layout/add_drop_fragment_meta.xml, line 2 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/537#-LB3JyQr2wW2p74dWKOu:-LBMBZkYBVbAwhRGj2GP:b1jbo15) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/37f5968da027f6bc46fdb853b8b485103200c657/app/src/main/res/layout/add_drop_fragment_meta.xml#L2)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What was the bug?
</blockquote></details>

The button was blocking items at the bottom of the recyclerView

---

*[app/src/main/res/layout/add_drop_fragment_meta.xml, line 21 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/537#-LB3K68D4K9qcUyS2hbh:-LBMBmQWBxYZaZYXzCPf:b-83og3x) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/37f5968da027f6bc46fdb853b8b485103200c657/app/src/main/res/layout/add_drop_fragment_meta.xml#L21)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do you need this in a constraint layout?
</blockquote></details>

Nope.

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/537)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/537)*

**Pull request merged**
