### PR TITLE
hotfix/warnings -> dev

### PR DESCRIPTION
**Pull request by geogor37**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[app/build.gradle, line 15 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_JRIp-3Xk0iuVHRet:-LB_JRIp-3Xk0iuVHReu:b-412hw1) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a8da5dbb8db782072e6d22c63b89a10ac4a8de5f/app/build.gradle#L15)):*
> ```Gradle
>         versionCode 147
>         versionName "6.6.0"
>         vectorDrawables.useSupportLibrary = true
> ```

Interesting. Explain this one to me

---

*[app/src/main/java/edu/byu/suite/features/addDrop/model/AddDropListItemDetail.java, line 9 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_JYhlBzbwHK3RkDhy:-LB_JYhlBzbwHK3RkDhz:bnvf318) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a8da5dbb8db782072e6d22c63b89a10ac4a8de5f/app/src/main/java/edu/byu/suite/features/addDrop/model/AddDropListItemDetail.java#L9)):*
> ```Java
>  */
> 
> @SuppressLint("ParcelCreator")
> ```

Why did it want a parcel creator? Does AddDropListItem extend ByuParcelable? If so, does this mean that we don't parcel the titleText and detailText when passing it through?

---

*[app/src/main/java/edu/byu/suite/features/addDrop/model/AddDropListItemHeader.java, line 9 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_Jnfv2nAXwci4VnMF:-LB_Jnfv2nAXwci4VnMG:b-hgeise) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a8da5dbb8db782072e6d22c63b89a10ac4a8de5f/app/src/main/java/edu/byu/suite/features/addDrop/model/AddDropListItemHeader.java#L9)):*
> ```Java
>  */
> 
> @SuppressLint("ParcelCreator")
> ```

Same question here. Does headerText never need to be parceled? If not, put that as a comment about the suppress line

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java, line 160 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_JySp-EwVHz5lM187:-LB_JySp-EwVHz5lM188:b7axyct) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a8da5dbb8db782072e6d22c63b89a10ac4a8de5f/app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java#L160)):*
> ```Java
> 
> 		@Override
> 		@SuppressLint("InflateParams")
> ```

Why did we need this one here, but nowhere else? What is this doing differently?

---

*[app/src/main/java/edu/byu/suite/features/mapMyClasses/BuildingDetailDialog.java, line 32 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_K2Mm9H67dwK3HkBZ:-LB_K2Mm9H67dwK3HkB_:b-z46h7w) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a8da5dbb8db782072e6d22c63b89a10ac4a8de5f/app/src/main/java/edu/byu/suite/features/mapMyClasses/BuildingDetailDialog.java#L32)):*
> ```Java
> 
> 	@Override
> 	@SuppressLint("InflateParams")
> ```

Same question as above

---

*[app/src/main/java/edu/byu/suite/features/myFinalsSchedule/controller/FinalsBuildingDetailDialog.java, line 32 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_K8Gv495F3O93mqnP:-LB_K8Gw8-SQmMb_dmYg:b-ya81ng) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a8da5dbb8db782072e6d22c63b89a10ac4a8de5f/app/src/main/java/edu/byu/suite/features/myFinalsSchedule/controller/FinalsBuildingDetailDialog.java#L32)):*
> ```Java
> 
> 	@Override
> 	@SuppressLint("InflateParams")
> ```

Same as above

---

*[app/src/main/java/edu/byu/suite/features/myNextClass/controller/MyNextClassMapFragment.java, line 61 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_KAKG6T8SM_tTHFwr:-LB_KAKG6T8SM_tTHFws:b-ya81ng) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a8da5dbb8db782072e6d22c63b89a10ac4a8de5f/app/src/main/java/edu/byu/suite/features/myNextClass/controller/MyNextClassMapFragment.java#L61)):*
> ```Java
> 	}
> 
> 	@SuppressLint("InflateParams")
> ```

Same as above

---

*[app/src/main/java/edu/byu/suite/features/printers/controller/AllPrintersFragment.java, line 118 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_KP488nq8z2loZdqT:-LB_KP488nq8z2loZdqU:bb73xfv) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a8da5dbb8db782072e6d22c63b89a10ac4a8de5f/app/src/main/java/edu/byu/suite/features/printers/controller/AllPrintersFragment.java#L118)):*
> ```Java
> 
>         @Override
>         @SuppressLint("InflateParams")
> ```

Same

---

*[app/src/main/java/edu/byu/suite/features/printers/controller/PrintersMainActivity.java, line 64 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_KQOT4HHgX4lnXXIG:-LB_KQOT4HHgX4lnXXIH:bb73xfv) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a8da5dbb8db782072e6d22c63b89a10ac4a8de5f/app/src/main/java/edu/byu/suite/features/printers/controller/PrintersMainActivity.java#L64)):*
> ```Java
> 	}
> 
> 	@SuppressLint("InflateParams")
> ```

Same

---

*[app/src/main/java/edu/byu/suite/mainScreen/whatsNew/WhatsNewDialog.java, line 78 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_KRfa-1i6MFYpAFX5:-LB_KRfa-1i6MFYpAFX6:bb73xfv) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a8da5dbb8db782072e6d22c63b89a10ac4a8de5f/app/src/main/java/edu/byu/suite/mainScreen/whatsNew/WhatsNewDialog.java#L78)):*
> ```Java
> 
> 	@Override
> 	@SuppressLint("InflateParams")
> ```

Same

---

*[app/src/main/res/layout/cannon_commons_fragment_map.xml, line 11 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_KVsl71fictPhWoOL:-LB_KVsm-ELZRB-DcWZZ:b-n1czp6) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/42df2123b6439438d20dc1040adf05f10d92f2d6/app/src/main/res/layout/cannon_commons_fragment_map.xml#L11)):*
> ```XML
> 			android:layout_gravity="center"
> 			android:layout_centerInParent="true"
> 			android:layout_below="@+id/toolbar"
> ```

Does removing this not break anything? Don't we need to be below the toolbar, or else it will hide the top part underneath?

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[app/build.gradle, line 15 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_JRIp-3Xk0iuVHRet:-LC4w5H8DEkARGrRZ79Y:b9n2o5i) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a8da5dbb8db782072e6d22c63b89a10ac4a8de5f/app/build.gradle#L15)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Interesting. Explain this one to me
</blockquote></details>

Without this we get a warning saying `To use VectorDrawableCompat, you need to set 'android.defaultConfig.vectorDrawables.useSupportLibrary = true'.` The file that uses this is `copyright-contact-popup.xml` It seems to be the icons that are causing the problem.

---

*[app/src/main/java/edu/byu/suite/features/addDrop/model/AddDropListItemDetail.java, line 9 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_JYhlBzbwHK3RkDhy:-LC4xY0CACeZOR43KGja:b-us6jcr) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a8da5dbb8db782072e6d22c63b89a10ac4a8de5f/app/src/main/java/edu/byu/suite/features/addDrop/model/AddDropListItemDetail.java#L9)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why did it want a parcel creator? Does AddDropListItem extend ByuParcelable? If so, does this mean that we don't parcel the titleText and detailText when passing it through?
</blockquote></details>

AddDropListItem does extend ByuParcelable, but it doesn't look like we ever pass an AddDropListItemDetail through anything.

---

*[app/src/main/java/edu/byu/suite/features/addDrop/model/AddDropListItemHeader.java, line 9 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_Jnfv2nAXwci4VnMF:-LC4z7iI6Ay6oCDJWgjP:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a8da5dbb8db782072e6d22c63b89a10ac4a8de5f/app/src/main/java/edu/byu/suite/features/addDrop/model/AddDropListItemHeader.java#L9)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Same question here. Does headerText never need to be parceled? If not, put that as a comment about the suppress line
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java, line 160 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_JySp-EwVHz5lM187:-LC4zT65-Pw4B9A3AH2z:bykf1z2) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a8da5dbb8db782072e6d22c63b89a10ac4a8de5f/app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java#L160)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why did we need this one here, but nowhere else? What is this doing differently?
</blockquote></details>

Without it we get the following warning because we pass in null to the inflate method: `Avoid passing null as the view root (needed to resolve layout parameters on the inflated layout's root element).  When inflating a layout , avoid passing in null as the parent view, since otherwise any layout parameters on the root of the inflated layout will be ignored.`  In the Android documentation for the inflate method, however, it says that the value here may be null, so I don't think passing in null will ever cause us any problems.

---

*[app/src/main/res/layout/cannon_commons_fragment_map.xml, line 11 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_KVsl71fictPhWoOL:-LC5-_q11xi3vwu_aT32:b-i20u37) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/42df2123b6439438d20dc1040adf05f10d92f2d6/app/src/main/res/layout/cannon_commons_fragment_map.xml#L11)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Does removing this not break anything? Don't we need to be below the toolbar, or else it will hide the top part underneath?
</blockquote></details>

This is part of a Fragment within a FrameLayout, so this actually doesn't have any reference to the toolbar.  That logic gets taken care of in the Activity that contains the Fragment.

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[app/build.gradle, line 15 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_JRIp-3Xk0iuVHRet:-LC5fEmP57eV5VUxBoG1:b-x75h7) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a8da5dbb8db782072e6d22c63b89a10ac4a8de5f/app/build.gradle#L15)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

Without this we get a warning saying `To use VectorDrawableCompat, you need to set 'android.defaultConfig.vectorDrawables.useSupportLibrary = true'.` The file that uses this is `copyright-contact-popup.xml` It seems to be the icons that are causing the problem.
</blockquote></details>

Hmmm... is there a reason why copyright uses it? How do other features (printers, dining locations, etc) access drawables?

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java, line 160 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_JySp-EwVHz5lM187:-LC5fgvK9VfUpD56Auru:b-rl71vz) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a8da5dbb8db782072e6d22c63b89a10ac4a8de5f/app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java#L160)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

Without it we get the following warning because we pass in null to the inflate method: `Avoid passing null as the view root (needed to resolve layout parameters on the inflated layout's root element).  When inflating a layout , avoid passing in null as the parent view, since otherwise any layout parameters on the root of the inflated layout will be ignored.`  In the Android documentation for the inflate method, however, it says that the value here may be null, so I don't think passing in null will ever cause us any problems.
</blockquote></details>

Ah! I gotcha. Don’t we have A ViewUtils that inflates stuff for us? Could we just suppress the warning there?

Also, if you find it in ViewUtils, could you move it from there into an extension on Context?

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[app/build.gradle, line 15 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_JRIp-3Xk0iuVHRet:-LCAaIN_8tu_W3gW2R0x:bblkkba) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a8da5dbb8db782072e6d22c63b89a10ac4a8de5f/app/build.gradle#L15)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Hmmm... is there a reason why copyright uses it? How do other features (printers, dining locations, etc) access drawables?
</blockquote></details>

I think the reason we're only seeing the warning in the copyright feature is because the icons it's using aren't saved as .png files

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java, line 160 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_JySp-EwVHz5lM187:-LCAc_du-NhDYnv5yi7t:b-sy1zwr) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a8da5dbb8db782072e6d22c63b89a10ac4a8de5f/app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java#L160)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Ah! I gotcha. Don’t we have A ViewUtils that inflates stuff for us? Could we just suppress the warning there?

Also, if you find it in ViewUtils, could you move it from there into an extension on Context?
</blockquote></details>

Done. Unfortunately it doesn't look like we'll be able to use the extension method in any of the Java classes, it'll only work in Kotlin classes.

---

*[app/src/main/java/edu/byu/suite/features/mapMyClasses/BuildingDetailDialog.java, line 32 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_K2Mm9H67dwK3HkBZ:-LCAelnw2iWId04RccuV:bv79j2h) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a8da5dbb8db782072e6d22c63b89a10ac4a8de5f/app/src/main/java/edu/byu/suite/features/mapMyClasses/BuildingDetailDialog.java#L32)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Same question as above
</blockquote></details>

So it turns out that ViewUtils won't work for this or any of the below cases because they all deal with inflating dialog layouts, and when inflating dialog layouts it's impossible to know what the parent view will be. As such, passing in null for the parent is fine, but the ViewUtils method requires that the parent be non-null, so I think we'll have to leave these ones as is.

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549)*

**Comment by romrell4** [comment]
Reviewed 12 of 12 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[app/build.gradle, line 15 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_JRIp-3Xk0iuVHRet:-LCD2YczCNxiwOB6X5XS:b-q6nyj2) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a8da5dbb8db782072e6d22c63b89a10ac4a8de5f/app/build.gradle#L15)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

I think the reason we're only seeing the warning in the copyright feature is because the icons it's using aren't saved as .png files
</blockquote></details>

Oh interesting! Can we convert them and remove this line?

---

*[support/src/main/java/edu/byu/support/utils/Extensions.kt, line 31 at r3](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LCD3BfmCV_xxrTt6dLM:-LCD3BfmCV_xxrTt6dLN:ba2fbsy) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/fd03fe9f33175ab7ad8c94332507b60954b84cb9/support/src/main/java/edu/byu/support/utils/Extensions.kt#L31)):*
> ```Kotlin
> }
> 
> fun Context?.inflate(parent: ViewGroup, layoutResId: Int): View = LayoutInflater.from(this).inflate(layoutResId, parent, false)
> ```

Do you need the `?` here? I don't think we need to inflate from a null context, do we?

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549)*

**Comment by geogor37** [comment]
Review status: 21 of 22 files reviewed at latest revision, 7 unresolved discussions.

---

*[app/build.gradle, line 15 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_JRIp-3Xk0iuVHRet:-LCEvXyRATFrGbCLwH9R:bft8ztn) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a8da5dbb8db782072e6d22c63b89a10ac4a8de5f/app/build.gradle#L15)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Oh interesting! Can we convert them and remove this line?
</blockquote></details>

I've been looking for about a half hour, and the best way I can figure out how to convert this file to the png is by creating a new image asset, which will save both of these icons in the four different sizes.  Should I go ahead and do that?  There doesn't seem to be an easy way to do a direct conversion.

---

*[app/src/main/java/edu/byu/suite/features/myFinalsSchedule/controller/FinalsBuildingDetailDialog.java, line 32 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_K8Gv495F3O93mqnP:-LCEhFyYC2IkyMwJ8iw9:br01mq9) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a8da5dbb8db782072e6d22c63b89a10ac4a8de5f/app/src/main/java/edu/byu/suite/features/myFinalsSchedule/controller/FinalsBuildingDetailDialog.java#L32)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

This won't work for same reason I described above

---

*[app/src/main/java/edu/byu/suite/features/myNextClass/controller/MyNextClassMapFragment.java, line 61 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_KAKG6T8SM_tTHFwr:-LCEhJu2BF3GQfZBCupi:bs4q9op) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a8da5dbb8db782072e6d22c63b89a10ac4a8de5f/app/src/main/java/edu/byu/suite/features/myNextClass/controller/MyNextClassMapFragment.java#L61)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Ditto.

---

*[app/src/main/java/edu/byu/suite/features/printers/controller/AllPrintersFragment.java, line 118 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_KP488nq8z2loZdqT:-LCEhPxw9j1bkvM-GG_B:bs4q9op) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a8da5dbb8db782072e6d22c63b89a10ac4a8de5f/app/src/main/java/edu/byu/suite/features/printers/controller/AllPrintersFragment.java#L118)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Ditto.

---

*[app/src/main/java/edu/byu/suite/features/printers/controller/PrintersMainActivity.java, line 64 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_KQOT4HHgX4lnXXIG:-LCEhRYfCik87l_4Caas:bs4q9op) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a8da5dbb8db782072e6d22c63b89a10ac4a8de5f/app/src/main/java/edu/byu/suite/features/printers/controller/PrintersMainActivity.java#L64)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Ditto.

---

*[app/src/main/java/edu/byu/suite/mainScreen/whatsNew/WhatsNewDialog.java, line 78 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_KRfa-1i6MFYpAFX5:-LCEhSrJ7BuGHLYOHtIB:bs4q9op) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a8da5dbb8db782072e6d22c63b89a10ac4a8de5f/app/src/main/java/edu/byu/suite/mainScreen/whatsNew/WhatsNewDialog.java#L78)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Ditto.

---

*[support/src/main/java/edu/byu/support/utils/Extensions.kt, line 31 at r3](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LCD3BfmCV_xxrTt6dLM:-LCEhdLK79f5tJicPFSr:b-usy9ok) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/fd03fe9f33175ab7ad8c94332507b60954b84cb9/support/src/main/java/edu/byu/support/utils/Extensions.kt#L31)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do you need the `?` here? I don't think we need to inflate from a null context, do we?
</blockquote></details>

Nope, good call.

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[app/build.gradle, line 15 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_JRIp-3Xk0iuVHRet:-LCGXKlW5RYva_MAAoiM:bm5rlua) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a8da5dbb8db782072e6d22c63b89a10ac4a8de5f/app/build.gradle#L15)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

I've been looking for about a half hour, and the best way I can figure out how to convert this file to the png is by creating a new image asset, which will save both of these icons in the four different sizes.  Should I go ahead and do that?  There doesn't seem to be an easy way to do a direct conversion.
</blockquote></details>

Yeah, I think that's fine :) The other options is to completely replace these icons (if you can find some good material icons). These were found through our iconfinder.com subscription, but I am more than happy to part with them for material icons

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549)*

**Comment by geogor37** [comment]
Review status: 16 of 33 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/build.gradle, line 15 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549#-LB_JRIp-3Xk0iuVHRet:-LCUJ5VS9wjO8Opdkwh-:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a8da5dbb8db782072e6d22c63b89a10ac4a8de5f/app/build.gradle#L15)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Yeah, I think that's fine :) The other options is to completely replace these icons (if you can find some good material icons). These were found through our iconfinder.com subscription, but I am more than happy to part with them for material icons
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549)*

**Comment by romrell4** [comment]
Reviewed 17 of 18 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/549)*

**Pull request merged**
