### PR TITLE
hotfix/safewalk -> dev

### PR DESCRIPTION
**Pull request by geogor37**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/486)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java, line 38 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-7iWaZGgh7hO01kM_2:-L-7iWaZGgh7hO01kM_3:be37tv5) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9cfffa260fa024fededfcd5e6b119c76a62dc95a/app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java#L38)):*
> ```Java
> 
>             AccountInformation accountInformation = AccountInformation.fetch(SafeWalkMainActivity.this, AccountResolver.getAccount(SafeWalkMainActivity.this));
> 			phoneEditText = (EditText) findViewById(R.id.phone_number_edit_text);
> ```

Only the phone number loading needs to happen in this sync task. Do the rest outside of this lambda

---

*[app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java, line 52 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-7ijyQ16fqsSiWcgeO:-L-7ijyQ16fqsSiWcgeP:b-v8rhi0) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d30041c1bac298c5f53840740dde44f8200096e4/app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java#L52)):*
> ```Java
>         if (checkPhoneNumber()) {
>             Intent intent = new Intent(this, SafeWalkMapActivity.class);
>             intent.putExtra(SafeWalkMapActivity.EXTRA_PHONE_NUMBER, userPhoneNumber);
> ```

So this would work if they input 1-2-3-4-5-6-7-8-9-0-------------? And it would send that to the service?

---

*[app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java, line 67 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-7isnXXv1zA9es-OFR:-L-7isnXXv1zA9es-OFS:b-xgy9h9) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9cfffa260fa024fededfcd5e6b119c76a62dc95a/app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java#L67)):*
> ```Java
>             startActivity(intent);
>         } else {
>             //  Displays a dialog box prompting the user to enter in a 10 digit phone number.
> ```

No more dialog. Just make the edit text border red (or something like that to indicate that the need to edit it. Figure out what is the best Android way of validating edit texts)

---

*[app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java, line 73 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-7jBO88xxMiKrb3yHw:-L-7jBO88xxMiKrb3yHx:b2c9csw) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9cfffa260fa024fededfcd5e6b119c76a62dc95a/app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java#L73)):*
> ```Java
>             new AlertDialog.Builder(this).setTitle(R.string.invalid_phone_number)
>                     .setMessage(R.string.safewalk_input_phone_dialog_message)
>                     .setPositiveButton("OK", ((dialog, which) -> dialog.cancel()))
> ```

Wait... Does this dialog not even do anything?

---

*[app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMapActivity.java, line 43 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-7jWDx4qkRWVyaELxc:-L-7jWDx4qkRWVyaELxd:bg2lpz3) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9cfffa260fa024fededfcd5e6b119c76a62dc95a/app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMapActivity.java#L43)):*
> ```Java
> 			} else if (!isInBoundaries(markerLocation)) {
> 				new AlertDialog.Builder(this).setMessage("Your destination falls outside the boundaries monitored by BYU police. In order to use Safewalk your destination must be within a mile of campus.")
> 						.setPositiveButton("OK", ((dialog, which) -> dialog.cancel())).show();
> ```

What is this line doing...?

---

*[app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMapActivity.java, line 67 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-7jLX76Pks2efJiDBX:-L-7jLX76Pks2efJiDBY:b91q42c) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9cfffa260fa024fededfcd5e6b119c76a62dc95a/app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMapActivity.java#L67)):*
> ```Java
> 	}
> 
> 	public void startWalk(){
> ```

CMD OPT L

---

*[app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMapActivity.java, line 74 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-7jGnzzNIaXxbK7EhS:-L-7jGnzzNIaXxbK7EhT:b-na30dx) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9cfffa260fa024fededfcd5e6b119c76a62dc95a/app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMapActivity.java#L74)):*
> ```Java
> 
> 	public boolean isInBoundaries(LatLng destination) {
> 		return destination.latitude >= 40.233000 && destination.latitude <= 40.265000 && destination.longitude >= -111.668000 && destination.longitude <= -111.631000;
> ```

Save magic numbers as private static finals

---

*[app/src/main/res/layout/safewalk_activity_main.xml, line 62 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-7jxJTf3zHNTem3kqX:-L-7jxJTf3zHNTem3kqY:bht8yu9) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9cfffa260fa024fededfcd5e6b119c76a62dc95a/app/src/main/res/layout/safewalk_activity_main.xml#L62)):*
> ```XML
> 	<TextView
> 		android:id="@+id/info_bullet1"
> 		android:layout_width="0dp"
> ```

Let's put most of this stuff into a style (so that it can be used for all three). Obviously don't put in the constraint stuff, but the text size, margins, width, and height should all be the same

---

*[app/src/main/res/values/strings.xml, line 276 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-7kQQi45MJhWiXq0Vj:-L-7kQQi45MJhWiXq0Vk:b-j3zsr2) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9cfffa260fa024fededfcd5e6b119c76a62dc95a/app/src/main/res/values/strings.xml#L276)):*
> ```XML
> 
> 	
> 	<string name="cell_phone_number">Cell Phone Number:</string>
> ```

prefix this with `safewalk_` (like the other ones)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java, line 38 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-7iWaZGgh7hO01kM_2:-L-7kj3i5uhFXB2lKhh7:bo7gno8) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9cfffa260fa024fededfcd5e6b119c76a62dc95a/app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java#L38)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Only the phone number loading needs to happen in this sync task. Do the rest outside of this lambda
</blockquote></details>

Whoops, I didn't even realize this was inside of a lambda.  Haha done.

---

*[app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java, line 52 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-7ijyQ16fqsSiWcgeO:-L-7lljwh5TrVG0npB7g:b-ji39y4) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d30041c1bac298c5f53840740dde44f8200096e4/app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java#L52)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

So this would work if they input 1-2-3-4-5-6-7-8-9-0-------------? And it would send that to the service?
</blockquote></details>

The way we were handling that before was by stripping all non-digit characters out before checking and sending that to the service, so we would accept this number and send it to the service as 1234567890; I just realized, however, that I'm only stripping the number when I check it, not when I send it to the service, so I will fix that.

---

*[app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java, line 67 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-7isnXXv1zA9es-OFR:-L-7rbXATxmZdZYkYqLE:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9cfffa260fa024fededfcd5e6b119c76a62dc95a/app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java#L67)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

No more dialog. Just make the edit text border red (or something like that to indicate that the need to edit it. Figure out what is the best Android way of validating edit texts)
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java, line 73 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-7jBO88xxMiKrb3yHw:-L-7nwcGxdw29fWEAT9Y:b-th8tji) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9cfffa260fa024fededfcd5e6b119c76a62dc95a/app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java#L73)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Wait... Does this dialog not even do anything?
</blockquote></details>

No, I was just using it to notify the user that the phone number was invalid.

---

*[app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMapActivity.java, line 43 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-7jWDx4qkRWVyaELxc:-L-7o3f9lrxF8O9L720_:bgkk71y) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9cfffa260fa024fededfcd5e6b119c76a62dc95a/app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMapActivity.java#L43)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What is this line doing...?
</blockquote></details>

It just closes the dialog.

---

*[app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMapActivity.java, line 67 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-7jLX76Pks2efJiDBX:-L-7oDbknpdopWjHkKpx:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9cfffa260fa024fededfcd5e6b119c76a62dc95a/app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMapActivity.java#L67)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

CMD OPT L
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMapActivity.java, line 74 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-7jGnzzNIaXxbK7EhS:-L-7p1NSrVjhauycd2Vh:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9cfffa260fa024fededfcd5e6b119c76a62dc95a/app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMapActivity.java#L74)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Save magic numbers as private static finals
</blockquote></details>

Done.

---

*[app/src/main/res/layout/safewalk_activity_main.xml, line 62 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-7jxJTf3zHNTem3kqX:-L-7te4DYQEuCA5n8EBZ:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9cfffa260fa024fededfcd5e6b119c76a62dc95a/app/src/main/res/layout/safewalk_activity_main.xml#L62)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Let's put most of this stuff into a style (so that it can be used for all three). Obviously don't put in the constraint stuff, but the text size, margins, width, and height should all be the same
</blockquote></details>

Done.

---

*[app/src/main/res/values/strings.xml, line 276 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-7kQQi45MJhWiXq0Vj:-L-7pCrhK3X-5IUr_Epw:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9cfffa260fa024fededfcd5e6b119c76a62dc95a/app/src/main/res/values/strings.xml#L276)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

prefix this with `safewalk_` (like the other ones)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486)*

**Comment by romrell4** [comment]
Reviewed 4 of 5 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java, line 52 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-7ijyQ16fqsSiWcgeO:-L-7vyGIbe_0SPzOK8O7:b3h1sse) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d30041c1bac298c5f53840740dde44f8200096e4/app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java#L52)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

The way we were handling that before was by stripping all non-digit characters out before checking and sending that to the service, so we would accept this number and send it to the service as 1234567890; I just realized, however, that I'm only stripping the number when I check it, not when I send it to the service, so I will fix that.
</blockquote></details>

Great. Just add a comment now that you removed the function

---

*[app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java, line 31 at r3](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-7wAJ3LqsYmoIfxmnc:-L-7wAJ4wJpqv1aXnMdM:bmizybu) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/73bd899c5cc6d058b074fe6c16060baf18286c22/app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java#L31)):*
> ```Java
> 		setContentView(R.layout.safewalk_activity_main);
> 		showProgressDialog();
> 		progressDialog.setCancelable(false);
> ```

I think you can do this by passing in `false` to showProgressDialog()

---

*[app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMapActivity.java, line 43 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-7jWDx4qkRWVyaELxc:-L-7wNx5xmnJh6Loy9MY:b5tbqt9) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9cfffa260fa024fededfcd5e6b119c76a62dc95a/app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMapActivity.java#L43)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

It just closes the dialog.
</blockquote></details>

Oh I see! I'm just used to new lines for builder functions. Add a new line before `.show()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-8TSK4BEapdWmpKIl2:-L-8TSK4BEapdWmpKIl3:b-jnx2y3) (no related file):*
Wait for Steve on the coordinates

---

*[app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java, line 33 at r3](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-8Sza3sjKF0hGQIjZ1:-L-8Sza3sjKF0hGQIjZ2:bw6dzpe) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/73bd899c5cc6d058b074fe6c16060baf18286c22/app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java#L33)):*
> ```Java
> 		progressDialog.setCancelable(false);
> 
> 		AccountInformation.sync(this, AccountResolver.getAccount(this), result -> {
> ```

I don't think we need to do this anymore. Just use whatever is saved in the shared preferences when the open the feature

---

*[app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java, line 38 at r3](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-8TFkZn33ix62uEeNV:-L-8TFkZn33ix62uEeNW:bk0gdze) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/73bd899c5cc6d058b074fe6c16060baf18286c22/app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java#L38)):*
> ```Java
> 			AccountInformation accountInformation = AccountInformation.fetch(SafeWalkMainActivity.this, AccountResolver.getAccount(SafeWalkMainActivity.this));
> 			phoneEditText = (EditText) findViewById(R.id.phone_number_edit_text);
> 			phoneEditText.setText(accountInformation.getPhoneNumber() != null ? accountInformation.getPhoneNumber() : "unknown");
> ```

Don't default to "unknown" anymore

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java, line 52 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-7ijyQ16fqsSiWcgeO:-L-93JxTXi0dYLnb1WU2:b-uxv8tw) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d30041c1bac298c5f53840740dde44f8200096e4/app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java#L52)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Great. Just add a comment now that you removed the function
</blockquote></details>

I did this one for you. Let me know if you have questions

---

*[app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java, line 31 at r3](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-7wAJ3LqsYmoIfxmnc:-L-93I4_tCBdgWhjkCdp:b-uxv8tw) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/73bd899c5cc6d058b074fe6c16060baf18286c22/app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java#L31)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I think you can do this by passing in `false` to showProgressDialog()
</blockquote></details>

I did this one for you. Let me know if you have questions

---

*[app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java, line 33 at r3](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-8Sza3sjKF0hGQIjZ1:-L-93GfF8oMX6oTiWnM-:b-uxv8tw) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/73bd899c5cc6d058b074fe6c16060baf18286c22/app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java#L33)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I don't think we need to do this anymore. Just use whatever is saved in the shared preferences when the open the feature
</blockquote></details>

I did this one for you. Let me know if you have questions

---

*[app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java, line 38 at r3](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-8TFkZn33ix62uEeNV:-L-93EGeXuG-FIK7_Lgi:b-uxv8tw) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/73bd899c5cc6d058b074fe6c16060baf18286c22/app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java#L38)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Don't default to "unknown" anymore
</blockquote></details>

I did this one for you. Let me know if you have questions

---

*[app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMapActivity.java, line 43 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-7jWDx4qkRWVyaELxc:-L-93PqbkMYvx7I5K2dD:bnkac9q) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9cfffa260fa024fededfcd5e6b119c76a62dc95a/app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMapActivity.java#L43)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Oh I see! I'm just used to new lines for builder functions. Add a new line before `.show()`
</blockquote></details>

null will close them automatically. I did this one for you. Let me know if you have questions

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-8TSK4BEapdWmpKIl2:-L-DwyrFIEmkoohJIu9h:b9jm36x) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Wait for Steve on the coordinates
</blockquote></details>

Coordinates are good. Now work on location updates in background

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486)*

**Comment by romrell4** [comment]
Reviewed 5 of 7 files at r5.
Review status: 8 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[app/src/main/AndroidManifest.xml, line 45 at r5](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-X3zy2k-Z8WH2YRCzV:-L-X3zy2k-Z8WH2YRCzW:b45bqst) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/83d0cc84069b84fb790e2d7c9ca94af436b21318/app/src/main/AndroidManifest.xml#L45)):*
> ```XML
> 		<service
> 			android:name=".features.safewalk.service.SafeWalkLocationService"
> 		    android:exported="false">
> ```

What does exported do? Also, use the self-closing tag `/ >`

---

*[app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java, line 27 at r5](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-X472vnGqvaTr7hoNJ:-L-X472vnGqvaTr7hoNK:b-89817p) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/83d0cc84069b84fb790e2d7c9ca94af436b21318/app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java#L27)):*
> ```Java
> 	private EditText phoneEditText;
> 
> //	TODO: Make up arrow work properly after finishing a Safewalk session
> ```

Do it

---

*[app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkWalkActivity.java, line 40 at r5](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-X4H4K5GHYLv8yZfN6:-L-X4H4K5GHYLv8yZfN7:b-a5tg92) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/83d0cc84069b84fb790e2d7c9ca94af436b21318/app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkWalkActivity.java#L40)):*
> ```Java
> 	}
> 
> //	@Override
> ```

Remove if unneeded

---

*[support/src/main/java/edu/byu/support/activity/ByuLocationActivity.java, line 91 at r5](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-X4P1CVIfAZB-b3hrC:-L-X4P1CVIfAZB-b3hrD:b4h7yuo) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d30041c1bac298c5f53840740dde44f8200096e4/support/src/main/java/edu/byu/support/activity/ByuLocationActivity.java#L91)):*
> ```Java
> 	protected void onDestroy() {
> 		super.onDestroy();
> 		if (googleApiClient.isConnected()) {
> ```

Why did we remove this? Could this cause an exception?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486)*

**Comment by geogor37** [comment]
Review status: 5 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-8TSK4BEapdWmpKIl2:-L-d-UVOaCTggK3lhjsq:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Coordinates are good. Now work on location updates in background
</blockquote></details>

Done.

---

*[app/src/main/AndroidManifest.xml, line 45 at r5](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-X3zy2k-Z8WH2YRCzV:-L-XPWCsFjAVhTcT1Rrr:b-bydvwi) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/83d0cc84069b84fb790e2d7c9ca94af436b21318/app/src/main/AndroidManifest.xml#L45)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What does exported do? Also, use the self-closing tag `/ >`
</blockquote></details>

Setting exported to false means that other apps can't use this service.

---

*[app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java, line 27 at r5](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-X472vnGqvaTr7hoNJ:-L-XP3EVHGs5ipOaUG8Y:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/83d0cc84069b84fb790e2d7c9ca94af436b21318/app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkMainActivity.java#L27)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do it
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkWalkActivity.java, line 40 at r5](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-X4H4K5GHYLv8yZfN6:-L-d-WcYSRqY3PWIYFzZ:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/83d0cc84069b84fb790e2d7c9ca94af436b21318/app/src/main/java/edu/byu/suite/features/safewalk/controller/SafeWalkWalkActivity.java#L40)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove if unneeded
</blockquote></details>

Done.

---

*[support/src/main/java/edu/byu/support/activity/ByuLocationActivity.java, line 91 at r5](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486#-L-X4P1CVIfAZB-b3hrC:-L-XPD0yQ6GXVTlqLgFe:b9rai5t) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d30041c1bac298c5f53840740dde44f8200096e4/support/src/main/java/edu/byu/support/activity/ByuLocationActivity.java#L91)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why did we remove this? Could this cause an exception?
</blockquote></details>

No I took it out because we already check this in the stopUpdatingLocation method, so this was redundant

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/486)*

**Pull request closed without merging**
