### PR TITLE
hotfix/cougarCash -> dev

### PR DESCRIPTION
**Pull request by geogor37**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/439)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/cougarCash/controller/CougarCashMainActivity.java, line 140 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/439#-Ks9OyhwJLNqwU8h7hVB:-Ks9OyhwJLNqwU8h7hVC:b9ux6ft) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/b4bfb79a30f1371d57304852d64d65dfbd7bc953/app/src/main/java/edu/byu/suite/features/cougarCash/controller/CougarCashMainActivity.java#L140)):*
> ```Java
> 				TransactionWrapper body = response.body();
> 				List<TransactionWrapper.Transaction> transactions = body.getTransactions();
> 				if (transactions == null) {
> ```

Do we need to check for null here? I thought she said that she would return an empty list of there were none...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/439)*

**Comment by geogor37** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/cougarCash/controller/CougarCashMainActivity.java, line 140 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/439#-Ks9OyhwJLNqwU8h7hVB:-KsAFUnjF9LXUzRLvd_U:b-9959im) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/b4bfb79a30f1371d57304852d64d65dfbd7bc953/app/src/main/java/edu/byu/suite/features/cougarCash/controller/CougarCashMainActivity.java#L140)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do we need to check for null here? I thought she said that she would return an empty list of there were none...
</blockquote></details>

Good call, I guess I can get rid of that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/439)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/cougarCash/controller/CougarCashMainActivity.java, line 30 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/439#-KsAHlXQU3oBZdxsrIEm:-KsAHlXQU3oBZdxsrIEn:bl4rcy8) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/5633cdcd9fd610dc2dddcc76e13ce5477e12ec9c/app/src/main/java/edu/byu/suite/features/cougarCash/controller/CougarCashMainActivity.java#L30)):*
> ```Java
> 
> import java.text.NumberFormat;
> import java.util.ArrayList;
> ```

Optimize imports

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/439)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/cougarCash/controller/CougarCashMainActivity.java, line 30 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/439#-KsAHlXQU3oBZdxsrIEm:-KsAK3yGQAwLfRWPejf5:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/5633cdcd9fd610dc2dddcc76e13ce5477e12ec9c/app/src/main/java/edu/byu/suite/features/cougarCash/controller/CougarCashMainActivity.java#L30)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Optimize imports
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/439)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/439)*

**Pull request merged**
