### PR TITLE
feature/cougarCashDirect -> dev

### PR DESCRIPTION
**Pull request by ecbrady**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/434)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/cougarCash/controller/CougarCashMainActivity.java, line 63 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/434#-KrlPYiAMFOk7aYI2CtO:-KrlPYiAMFOk7aYI2CtP:b-kiqnf0) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/2131176ea7191848e4d365e6b984b796b70ab0b1/app/src/main/java/edu/byu/suite/features/cougarCash/controller/CougarCashMainActivity.java#L63)):*
> ```Java
> 
> 		addFundsButton.setOnClickListener(view -> {
>             if (addFundsButton.getText().equals("Add Funds")) {
> ```

We should save the String into a private static final at the top so that we don't have to duplicate it. We should also flip the `.equals` in order to be null safe

---

*[app/src/main/java/edu/byu/suite/features/cougarCash/model/BalanceWrapper.java, line 16 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/434#-KrlQFR1vYUUXM545qfA:-KrlQFR1vYUUXM545qfB:bl8fzyc) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/2131176ea7191848e4d365e6b984b796b70ab0b1/app/src/main/java/edu/byu/suite/features/cougarCash/model/BalanceWrapper.java#L16)):*
> ```Java
> 	}
> 
> 	public boolean isCanAddFunds() {
> ```

I've always been partial to `get` rather than `is` getters. Especially in cases like this where it doesn't make sense. Let's switch these to `get` functions

---

*[app/src/main/res/layout/cougar_cash_activity_main.xml, line 2 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/434#-KrlQewfOZPTllmLWhh4:-KrlQewfOZPTllmLWhh5:bvfc8r6) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/2131176ea7191848e4d365e6b984b796b70ab0b1/app/src/main/res/layout/cougar_cash_activity_main.xml#L2)):*
> ```XML
> <?xml version="1.0" encoding="utf-8"?>
> <RelativeLayout
> ```

Do this with a constraint layout (see if you can) :smile: 

---

*[app/src/main/res/layout/cougar_cash_activity_main.xml, line 45 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/434#-KrlQV30vOx46RVBSxfx:-KrlQV30vOx46RVBSxfy:b-hg7sih) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/0808dfbefd3d73f77eb9421151d2467c1f68cc9a/app/src/main/res/layout/cougar_cash_activity_main.xml#L45)):*
> ```XML
> 			android:layout_height="wrap_content"
> 			android:layout_weight="1"
> 			android:visibility="invisible"
> ```

I think we should still start this as invisible (so that they can't click it before the data loads)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/434)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/cougarCash/model/BalanceWrapper.java, line 16 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/434#-KrlQFR1vYUUXM545qfA:-KrlbpWV8g6-pPjlqq_J:bb7f2mf) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/2131176ea7191848e4d365e6b984b796b70ab0b1/app/src/main/java/edu/byu/suite/features/cougarCash/model/BalanceWrapper.java#L16)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I've always been partial to `get` rather than `is` getters. Especially in cases like this where it doesn't make sense. Let's switch these to `get` functions
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/434)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[app/src/main/res/layout/cougar_cash_activity_main.xml, line 45 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/434#-KrlQV30vOx46RVBSxfx:-KrldRhU2Ne5134rlxVh:bb7f2mf) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/0808dfbefd3d73f77eb9421151d2467c1f68cc9a/app/src/main/res/layout/cougar_cash_activity_main.xml#L45)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I think we should still start this as invisible (so that they can't click it before the data loads)
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/434)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[app/src/main/res/layout/cougar_cash_activity_main.xml, line 2 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/434#-KrlQewfOZPTllmLWhh4:-Krli6-fWLUxY5qMSaoX:bb7f2mf) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/2131176ea7191848e4d365e6b984b796b70ab0b1/app/src/main/res/layout/cougar_cash_activity_main.xml#L2)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do this with a constraint layout (see if you can) :smile: 
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/434)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/res/layout/cougar_cash_activity_main.xml, line 24 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/434#-KrlilDrF1Qbv8nUvcGY:-KrlilDrF1Qbv8nUvcGZ:b-d996p1) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/e68bf79d3604470ea0c7f336169ecdc0b7225d89/app/src/main/res/layout/cougar_cash_activity_main.xml#L24)):*
> ```XML
> 		android:layout_width="0dp"
> 		android:layout_height="wrap_content"
> 		android:layout_below="@+id/toolbar"
> ```

You shouldn't need layout_below anymore. You might be able to remove some other ones as well. Other than that, it looks pretty dang good!

---

*[app/src/main/res/layout/cougar_cash_activity_main.xml, line 38 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/434#-Krlitl3KmjjoYjwDhNi:-Krlitl3KmjjoYjwDhNj:bwpdnv6) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/e68bf79d3604470ea0c7f336169ecdc0b7225d89/app/src/main/res/layout/cougar_cash_activity_main.xml#L38)):*
> ```XML
> 		app:layout_constraintTop_toBottomOf="@+id/toolbar" />
> 
> 	<LinearLayout
> ```

Remove this linear layout. In constraint layout, you should be able to do everything without nested layouts

---

*[app/src/main/res/layout/cougar_cash_activity_main.xml, line 79 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/434#-Krlj2hG1jR8A3eU3VXa:-Krlj2hG1jR8A3eU3VXb:b-vkl1lk) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/e68bf79d3604470ea0c7f336169ecdc0b7225d89/app/src/main/res/layout/cougar_cash_activity_main.xml#L79)):*
> ```XML
> 		android:layout_width="0dp"
> 		android:layout_height="wrap_content"
> 		android:layout_alignParentBottom="true"
> ```

This should be able to go too

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/434)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[app/src/main/res/layout/cougar_cash_activity_main.xml, line 80 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/434#-KrljGizT-BWZFuckmyT:-KrljGizT-BWZFuckmyU:begxz2m) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/e68bf79d3604470ea0c7f336169ecdc0b7225d89/app/src/main/res/layout/cougar_cash_activity_main.xml#L80)):*
> ```XML
> 		android:layout_height="wrap_content"
> 		android:layout_alignParentBottom="true"
> 		android:text="Sign Up for Cougar Cash Direct"
> ```

Move this text into the strings file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/434)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[app/src/main/res/layout/cougar_cash_activity_main.xml, line 38 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/434#-Krlitl3KmjjoYjwDhNi:-KrlmzeJYyZ4Mhiet-pH:bb7f2mf) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/e68bf79d3604470ea0c7f336169ecdc0b7225d89/app/src/main/res/layout/cougar_cash_activity_main.xml#L38)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove this linear layout. In constraint layout, you should be able to do everything without nested layouts
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/434)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[app/src/main/res/layout/cougar_cash_activity_main.xml, line 24 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/434#-KrlilDrF1Qbv8nUvcGY:-KrlsIfc2AnrphWLOXPc:bb7f2mf) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/e68bf79d3604470ea0c7f336169ecdc0b7225d89/app/src/main/res/layout/cougar_cash_activity_main.xml#L24)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

You shouldn't need layout_below anymore. You might be able to remove some other ones as well. Other than that, it looks pretty dang good!
</blockquote></details>

done

---

*[app/src/main/res/layout/cougar_cash_activity_main.xml, line 79 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/434#-Krlj2hG1jR8A3eU3VXa:-KrlsKx9th_frFKMzOeq:bb7f2mf) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/e68bf79d3604470ea0c7f336169ecdc0b7225d89/app/src/main/res/layout/cougar_cash_activity_main.xml#L79)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

This should be able to go too
</blockquote></details>

done

---

*[app/src/main/res/layout/cougar_cash_activity_main.xml, line 80 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/434#-KrljGizT-BWZFuckmyT:-KrlsFidRtVoIvMt8MvQ:bb7f2mf) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/e68bf79d3604470ea0c7f336169ecdc0b7225d89/app/src/main/res/layout/cougar_cash_activity_main.xml#L80)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Move this text into the strings file
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/434)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/434)*

**Pull request merged**
