### PR TITLE
feature/java8 -> dev

### PR DESCRIPTION
**Pull request by romrell4**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/489)

### CODE REVIEW

**Comment by geogor37** [comment]
Review status: 0 of 50 files reviewed at latest revision, 2 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/activity/ByuActivity.java, line 63 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/489#-L-cBMj7GCSzx-QEDC9G:-L-cBMj7GCSzx-QEDC9H:bg0reja) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/5003be44f9c0e43429e3814504f79119a24366b9/support/src/main/java/edu/byu/support/activity/ByuActivity.java#L63)):*
> ```Java
> 
> 	private void configureToolbar(View view) {
> 		Toolbar toolbar = (Toolbar) view.findViewById(R.id.toolbar);
> ```

There's a lot of these, so I'll just leave one comment.  Do you not have to cast when you use findViewById anymore?

---

*[support/src/main/java/edu/byu/support/utils/StringUtils.java, line 91 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/489#-L-cDEeDnoHqnB0h8JJL:-L-cDEeDnoHqnB0h8JJM:b-e592gb) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/5003be44f9c0e43429e3814504f79119a24366b9/support/src/main/java/edu/byu/support/utils/StringUtils.java#L91)):*
> ```Java
> 	 * 	Capture the rest of the word (including apostrophes, periods (for web addresses), and possibly numbers) so we can lowercase it
> 	 */
> 	private static final Pattern PATTERN = Pattern.compile("(^|[ (/-])(?!(?:" + TextUtils.join("|", EXCEPTIONS) + ")\\b)([a-zA-Z])([\\w'\\.]*)");
> ```

I could be wrong, but I thought you did have to escape the period.  I seem to remember this being an issue when we were trying to validate the jwt in OAuth.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/489)*

**Comment by romrell4** [comment]
Review status: 0 of 50 files reviewed at latest revision, 2 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/activity/ByuActivity.java, line 63 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/489#-L-cBMj7GCSzx-QEDC9G:-L-cEGmApU24UucEjwJT:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/5003be44f9c0e43429e3814504f79119a24366b9/support/src/main/java/edu/byu/support/activity/ByuActivity.java#L63)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

There's a lot of these, so I'll just leave one comment.  Do you not have to cast when you use findViewById anymore?
</blockquote></details>

Done.

---

*[support/src/main/java/edu/byu/support/utils/StringUtils.java, line 91 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/489#-L-cDEeDnoHqnB0h8JJL:-L-cEJC635gr9KE-jVJo:b592zr8) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/5003be44f9c0e43429e3814504f79119a24366b9/support/src/main/java/edu/byu/support/utils/StringUtils.java#L91)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

I could be wrong, but I thought you did have to escape the period.  I seem to remember this being an issue when we were trying to validate the jwt in OAuth.
</blockquote></details>

Could you test this? The compiler kept telling me that I had an "unnecessary escape"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/489)*

**Comment by geogor37** [comment]
Reviewed 50 of 50 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/utils/StringUtils.java, line 91 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/489#-L-cDEeDnoHqnB0h8JJL:-L-cHphvJlKBmx6lc9CO:b-6ulcka) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/5003be44f9c0e43429e3814504f79119a24366b9/support/src/main/java/edu/byu/support/utils/StringUtils.java#L91)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Could you test this? The compiler kept telling me that I had an "unnecessary escape"
</blockquote></details>

Looks like this is fine

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/489)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/utils/StringUtils.java, line 91 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/489#-L-cDEeDnoHqnB0h8JJL:-L-cMY8SyhXEcW3nbS8n:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/5003be44f9c0e43429e3814504f79119a24366b9/support/src/main/java/edu/byu/support/utils/StringUtils.java#L91)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

Looks like this is fine
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/489)*

**Pull request merged**
