### PR TITLE
DependencyCleanup -> dev

### PR DESCRIPTION
**Pull request by aarowhead**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/556)

### CODE REVIEW

**Comment by aarowhead** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[support/build.gradle, line 51 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/556#-LCncSzN0IhHMtfifjvR:-LDJHW8M7kEKqG-fSOQ6:b-t2qipt) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/2452deeb97fbe5d70467b3ebd62b2e1ff96c3b2f/support/build.gradle#L51)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Did we decide that we were going to implementation for external libraries?
</blockquote></details>

So I looked into this more and realized that I had understood what was going on incorrectly. Now I understand better. What is going on is I use ```api``` for dependencies used in both the ```app``` and ```support``` modules. If a dependency is only used in one of the two modules then it uses ```implementation``` and is kept in the module that it is used in. This gives us faster compile times because if an ```implementation``` dependency is updated in the ```support``` module, the compiler knows it only needs to recompile the ```support``` module were as before it recompiled both the ```app``` and ```support``` modules even when it didn't need to. This will mean that we will need to be more conscious as to how our dependencies are used and shared. Another option would be to change all the ```api``` dependencies to ```implementation``` and put them in both the ```app``` and ```support``` modules but I don't see any advantage to this.

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/556)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[support/build.gradle, line 47 at r2](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/556#-LDJPlPs6g6Hp2R-hIAH:-LDJPlPs6g6Hp2R-hIAI:b-x35dj9) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/5f70c955042e7439ed41c93462fed9031026a9bd/support/build.gradle#L47)):*
> ```Gradle
>         exclude group: 'stax', module: 'stax'
>     }
>     api 'com.prolificinteractive:material-calendarview:1.4.3'
> ```

Make sure these are all in alphabetical order

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/556)*

**Comment by aarowhead** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[support/build.gradle, line 47 at r2](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/556#-LDJPlPs6g6Hp2R-hIAH:-LDJRC9o6-vnqcvgordB:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/5f70c955042e7439ed41c93462fed9031026a9bd/support/build.gradle#L47)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Make sure these are all in alphabetical order
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/556)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/556)*

**Pull request merged**
