### PR TITLE
feature/recyclerViewFragment -> dev

### PR DESCRIPTION
**Pull request by geogor37**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/465)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 23 of 23 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/aedLocator/controller/AllAedsListFragment.java, line 41 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/465#-KwHZSo1nvEdkiE6xmav:-KwHZSo1nvEdkiE6xmaw:b41bvbs) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/bb71e1a4df6d10fad9896ea6631c3cad8d9dab1a/app/src/main/java/edu/byu/suite/features/aedLocator/controller/AllAedsListFragment.java#L41)):*
> ```Java
> 		}
> 		setAdapter(new DefaultRecyclerAdapter<>(aedList, R.layout.default_list_item_detail_indicator, Aed::getLocation, Aed::getDistance,
> 															 (data, view1, position) -> ((AllAedsActivity) getActivity()).goToMap(data)), true);
> ```

What was this true for again? I'm trying to remember...

---

*[app/src/main/java/edu/byu/suite/features/classSchedule/CourseSectionFragment.java, line 75 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/465#-KwHZbaO0nbuhDM12SjL:-KwHZbaO0nbuhDM12SjM:b-tsd7z1) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/bb71e1a4df6d10fad9896ea6631c3cad8d9dab1a/app/src/main/java/edu/byu/suite/features/classSchedule/CourseSectionFragment.java#L75)):*
> ```Java
> 		return view;
> 	}
> 	//	Add custom message for when no sections are available?
> ```

What is this comment?

---

*[app/src/main/java/edu/byu/suite/features/myFinancialCenter/controller/UnpaidChargesFragment.java, line 35 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/465#-KwHZuTBZr0-MI4y67aF:-KwHZuTBZr0-MI4y67aG:bi1vknh) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/bb71e1a4df6d10fad9896ea6631c3cad8d9dab1a/app/src/main/java/edu/byu/suite/features/myFinancialCenter/controller/UnpaidChargesFragment.java#L35)):*
> ```Java
> 	@Override
> 	public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
> 		View view = onCreateView(inflater, container, R.layout.mfc_fragment_unpaid_charges);
> ```

Use `super.` Make sure you do this everywhere else as well

---

*[app/src/main/java/edu/byu/suite/features/restrooms/fragment/RestroomListFragment.java, line 55 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/465#-KwH_8QChpsV3-Cqd0fx:-KwH_8QChpsV3-Cqd0fy:b-76qzrw) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/bb71e1a4df6d10fad9896ea6631c3cad8d9dab1a/app/src/main/java/edu/byu/suite/features/restrooms/fragment/RestroomListFragment.java#L55)):*
> ```Java
> 	@Override
> 	protected String getEmptyDataText() {
> 		return getString(R.string.no_building_selected);
> ```

I don't see this used before... Where was this set?

---

*[app/src/main/java/edu/byu/suite/features/testingcenter/controller/ScoresFragment.java, line 174 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/465#-KwH_QRngMkLCqSBs7xX:-KwH_QRngMkLCqSBs7xY:b-k64knx) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/bb71e1a4df6d10fad9896ea6631c3cad8d9dab1a/app/src/main/java/edu/byu/suite/features/testingcenter/controller/ScoresFragment.java#L174)):*
> ```Java
> 	@Override
> 	protected String getEmptyDataText() {
> 		return getString(R.string.testing_center_no_tests);
> ```

Where did this come from? It didn't look set before...

---

*[app/src/main/res/layout/testing_center_fragment_scores.xml, line 12 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/465#-KwH_ZJy8Fy647hsMgjE:-KwH_ZJy8Fy647hsMgjF:b-g2l0iw) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/bb71e1a4df6d10fad9896ea6631c3cad8d9dab1a/app/src/main/res/layout/testing_center_fragment_scores.xml#L12)):*
> ```XML
> 			android:layout_height="match_parent">
> 
> 		<include layout="@layout/recycler_view_switcher_layout" />
> ```

Can we not just delete all of these? Is there anything special about them?

---

*[support/src/main/java/edu/byu/support/fragment/ByuRecyclerViewFragment.java, line 28 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/465#-KwH_kVahwpModJKuiYK:-KwH_kVahwpModJKuiYL:bhpp16b) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/bb71e1a4df6d10fad9896ea6631c3cad8d9dab1a/support/src/main/java/edu/byu/support/fragment/ByuRecyclerViewFragment.java#L28)):*
> ```Java
> 
> 	@Override
> 	public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
> ```

Why are there two different onCreateViews? They have quite a bit of duplicate code...

---

*[support/src/main/res/layout/fragment_recycler_view.xml, line 2 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/465#-KwH_w0Kn5D6IxyHHWPV:-KwH_w0Kn5D6IxyHHWPW:b-xwm2ek) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/bb71e1a4df6d10fad9896ea6631c3cad8d9dab1a/support/src/main/res/layout/fragment_recycler_view.xml#L2)):*
> ```XML
> <?xml version="1.0" encoding="utf-8"?>
> <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
> ```

Why LinearLayout? Can we use constraint?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/465)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/aedLocator/controller/AllAedsListFragment.java, line 41 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/465#-KwHZSo1nvEdkiE6xmav:-KwHaB23KPS0uT4El95B:b-oe7js3) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/bb71e1a4df6d10fad9896ea6631c3cad8d9dab1a/app/src/main/java/edu/byu/suite/features/aedLocator/controller/AllAedsListFragment.java#L41)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What was this true for again? I'm trying to remember...
</blockquote></details>

It tells the viewSwitcher to display the empty data text if necessary.

---

*[app/src/main/java/edu/byu/suite/features/classSchedule/CourseSectionFragment.java, line 75 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/465#-KwHZbaO0nbuhDM12SjL:-KwHaVeWXt8oC8bqo1s9:b-jkvfnl) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/bb71e1a4df6d10fad9896ea6631c3cad8d9dab1a/app/src/main/java/edu/byu/suite/features/classSchedule/CourseSectionFragment.java#L75)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What is this comment?
</blockquote></details>

I put it there as a reminder to ask you whether we wanted to add custom empty data messages on any of these Fragments that are now extending the RecyclerViewFragment.  The current default is "No information available at this time."

---

*[app/src/main/java/edu/byu/suite/features/myFinancialCenter/controller/UnpaidChargesFragment.java, line 35 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/465#-KwHZuTBZr0-MI4y67aF:-KwHg3Nvc70BeS3mwQdU:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/bb71e1a4df6d10fad9896ea6631c3cad8d9dab1a/app/src/main/java/edu/byu/suite/features/myFinancialCenter/controller/UnpaidChargesFragment.java#L35)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Use `super.` Make sure you do this everywhere else as well
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/restrooms/fragment/RestroomListFragment.java, line 55 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/465#-KwH_8QChpsV3-Cqd0fx:-KwHb7c5CzutoNJqMMUg:b278s6m) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/bb71e1a4df6d10fad9896ea6631c3cad8d9dab1a/app/src/main/java/edu/byu/suite/features/restrooms/fragment/RestroomListFragment.java#L55)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I don't see this used before... Where was this set?
</blockquote></details>

It was in the layout file, but since this is now using the same layout file as theRecyclerViewFragment I had to set it here.

---

*[app/src/main/java/edu/byu/suite/features/testingcenter/controller/ScoresFragment.java, line 174 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/465#-KwH_QRngMkLCqSBs7xX:-KwHbMuWZB7xIRKu31CP:b2nreh6) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/bb71e1a4df6d10fad9896ea6631c3cad8d9dab1a/app/src/main/java/edu/byu/suite/features/testingcenter/controller/ScoresFragment.java#L174)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Where did this come from? It didn't look set before...
</blockquote></details>

Same as above.

---

*[app/src/main/res/layout/testing_center_fragment_scores.xml, line 12 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/465#-KwH_ZJy8Fy647hsMgjE:-KwHbhwgY_8RT-knVE5Z:b-1zvemy) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/bb71e1a4df6d10fad9896ea6631c3cad8d9dab1a/app/src/main/res/layout/testing_center_fragment_scores.xml#L12)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Can we not just delete all of these? Is there anything special about them?
</blockquote></details>

Sorry, I'm not sure what "these" is referring to, you mean the SwipeRefreshLayout?

---

*[support/src/main/java/edu/byu/support/fragment/ByuRecyclerViewFragment.java, line 28 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/465#-KwH_kVahwpModJKuiYK:-KwHbzfNFl-M4fbeBVjM:b-uu7r3b) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/bb71e1a4df6d10fad9896ea6631c3cad8d9dab1a/support/src/main/java/edu/byu/support/fragment/ByuRecyclerViewFragment.java#L28)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why are there two different onCreateViews? They have quite a bit of duplicate code...
</blockquote></details>

Some of the Fragments that now extend the ByuRecyclerViewFragment were using different layout files (for example a recycler view inside a view switcher with a button at the bottom), so the second method takes in an alternate layout file as a parameter, but sets everything else up the same.  I removed the duplicate code from the first method.

---

*[support/src/main/res/layout/fragment_recycler_view.xml, line 2 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/465#-KwH_w0Kn5D6IxyHHWPV:-KwHg4Nfz4SaLvRVA7RI:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/bb71e1a4df6d10fad9896ea6631c3cad8d9dab1a/support/src/main/res/layout/fragment_recycler_view.xml#L2)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why LinearLayout? Can we use constraint?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/465)*

**Comment by romrell4** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/classSchedule/CourseSectionFragment.java, line 75 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/465#-KwHZbaO0nbuhDM12SjL:-KwHsgRV_E95iLvoE6e8:b-qo3wp2) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/bb71e1a4df6d10fad9896ea6631c3cad8d9dab1a/app/src/main/java/edu/byu/suite/features/classSchedule/CourseSectionFragment.java#L75)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

I put it there as a reminder to ask you whether we wanted to add custom empty data messages on any of these Fragments that are now extending the RecyclerViewFragment.  The current default is "No information available at this time."
</blockquote></details>

The only time I want the emptyDataMessage is if the data comes from a service and COULD be empty. If it meets this criteria, then we should add it if we feel like it would help clear confusion. (Otherwise "No information available at this time" is fine)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/465)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/classSchedule/CourseSectionFragment.java, line 75 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/465#-KwHZbaO0nbuhDM12SjL:-KwL2icVGHYbmjHsQoUU:bxxx4gf) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/bb71e1a4df6d10fad9896ea6631c3cad8d9dab1a/app/src/main/java/edu/byu/suite/features/classSchedule/CourseSectionFragment.java#L75)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

The only time I want the emptyDataMessage is if the data comes from a service and COULD be empty. If it meets this criteria, then we should add it if we feel like it would help clear confusion. (Otherwise "No information available at this time" is fine)
</blockquote></details>

That makes sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/465)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/465)*

**Pull request merged**
