### PR TITLE
feature/alumni -> dev

### PR DESCRIPTION
**Pull request by geogor37**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/476)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/476#-Kyb1KMEYyyXslRNzHAf:-Kyb1KMEYyyXslRNzHAg:b7lxfm3) (no related file):*
Get icons

---

*[app/src/main/java/edu/byu/suite/features/alumniConnect/AlumniConnectMainActivity.java, line 43 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/476#-Kyb26Mbxa_HUfYDY5xI:-Kyb26Mbxa_HUfYDY5xJ:bh1fyth) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/cbc61b01d0eca494236979eafc3485ed44026c67/app/src/main/java/edu/byu/suite/features/alumniConnect/AlumniConnectMainActivity.java#L43)):*
> ```Java
> 				new DefaultRowWithClickListener("Update Your Info", view -> startChromeTabView(UPDATE_INFO_URL)),
> 				new DefaultRowWithClickListener("Go to Alumni Site", view -> startChromeTabView(ALUMNI_HOME_PAGE_URL)),
> 				new DefaultRowWithClickListener("Visit Aspen Grove", view -> startChromeTabView(ASPEN_GROVE_URL)),
> ```

"Aspen Grove"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/476)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/alumniConnect/AlumniConnectMainActivity.java, line 43 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/476#-Kyb26Mbxa_HUfYDY5xI:-Kyb2q5npGqGSNFPKMZJ:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/cbc61b01d0eca494236979eafc3485ed44026c67/app/src/main/java/edu/byu/suite/features/alumniConnect/AlumniConnectMainActivity.java#L43)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

"Aspen Grove"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/476)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/476#-KybQefymF4u4E135MFj:-KybQefymF4u4E135MFk:b-wzatu0) (no related file):*
Get with Alex and make sure they look the exact same

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/476)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/476)*

**Comment by geogor37** [comment]
Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/476#-Kyb1KMEYyyXslRNzHAf:-Kz5abaa19dEBgWcyT9Z:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Get icons
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/476)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/476)*

**Comment by geogor37** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/476#-KybQefymF4u4E135MFj:-Kz5eAWFryUVmD4WzMnh:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Get with Alex and make sure they look the exact same
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/476)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/476)*

**Pull request merged**
