### PR TITLE
hotfix/myNextClass -> dev

### PR DESCRIPTION
**Pull request by geogor37**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/517)

### CODE REVIEW

**Comment by romrell4** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[app/src/main/java/edu/byu/suite/features/myNextClass/controller/MyNextClassMainActivity.java, line 339 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/517#-L71LoHg5QoSiZ9GPO1P:-L71LoHg5QoSiZ9GPO1Q:b-sfvpdr) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/8164204373e9c9f44dae9086ea425a448489df10/app/src/main/java/edu/byu/suite/features/myNextClass/controller/MyNextClassMainActivity.java#L339)):*
> ```Java
> 		List<Course> coursesForDay = new ArrayList<>();
> 		for (Course course : courses) {
> 			if (dayStringPattern.matcher(course.getDays().toLowerCase().contains("daily") ? "MTWThF" : course.getDays()).matches()) {
> ```

I thought you modified the getDays function to return MTWThF if it was "daily"... Why do you need this?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/517)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/517)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/myNextClass/controller/MyNextClassMainActivity.java, line 339 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/517#-L71LoHg5QoSiZ9GPO1P:-L71Mg8sR_jSAUkGZhz5:b-5qm499) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/8164204373e9c9f44dae9086ea425a448489df10/app/src/main/java/edu/byu/suite/features/myNextClass/controller/MyNextClassMainActivity.java#L339)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I thought you modified the getDays function to return MTWThF if it was "daily"... Why do you need this?
</blockquote></details>

No, MyClasses actually uses a totally different function that returns a list of the days instead of just a string.  I could put this logic in getClasses though if you want!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/517)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/myNextClass/controller/MyNextClassMainActivity.java, line 339 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/517#-L71LoHg5QoSiZ9GPO1P:-L71NdjJE7Fc_Aje9tL3:benyz54) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/8164204373e9c9f44dae9086ea425a448489df10/app/src/main/java/edu/byu/suite/features/myNextClass/controller/MyNextClassMainActivity.java#L339)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

No, MyClasses actually uses a totally different function that returns a list of the days instead of just a string.  I could put this logic in getClasses though if you want!
</blockquote></details>

Ugh. I was hoping that we could make one fix that could solve both issues. Do they not use the same underlying structure?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/517)*

**Comment by geogor37** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/myNextClass/controller/MyNextClassMainActivity.java, line 339 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/517#-L71LoHg5QoSiZ9GPO1P:-L71em5I1BVtqNK2IJw3:b2a270o) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/8164204373e9c9f44dae9086ea425a448489df10/app/src/main/java/edu/byu/suite/features/myNextClass/controller/MyNextClassMainActivity.java#L339)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Ugh. I was hoping that we could make one fix that could solve both issues. Do they not use the same underlying structure?
</blockquote></details>

K, I don't know if this is exactly what you had in mind, but this does remove the duplicate logic

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/517)*

**Comment by romrell4** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---

*[support/src/main/java/edu/byu/support/client/studentClassScheduleClient/model/Course.java, line 68 at r2](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/517#-L75Ss8v7md63ySEUvav:-L75Ss8v7md63ySEUvaw:b-dyhigj) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/028890068e3cefdb0d89c79ebda685c57ad2707c/support/src/main/java/edu/byu/support/client/studentClassScheduleClient/model/Course.java#L68)):*
> ```Java
> 	}
> 
> 	public String getDays() {
> ```

So with the other one, do we need this one anymore?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/517)*

**Comment by romrell4** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/517)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/client/studentClassScheduleClient/model/Course.java, line 68 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/517#-L75Ss8v7md63ySEUvav:-L76TqQ_nrUuvfoysrPB:biekk3f) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/028890068e3cefdb0d89c79ebda685c57ad2707c/support/src/main/java/edu/byu/support/client/studentClassScheduleClient/model/Course.java#L68)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

So with the other one, do we need this one anymore?
</blockquote></details>

Depends.  Would you prefer that we display "MTWThF" instead of "Daily" in places where we are displaying the class schedule?  Keeping this method allows us to continue displaying "Daily."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/517)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/client/studentClassScheduleClient/model/Course.java, line 68 at r2](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/517#-L75Ss8v7md63ySEUvav:-L76otCWBchJ7ZVPDpsM:b7lqu6g) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/028890068e3cefdb0d89c79ebda685c57ad2707c/support/src/main/java/edu/byu/support/client/studentClassScheduleClient/model/Course.java#L68)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

Depends.  Would you prefer that we display "MTWThF" instead of "Daily" in places where we are displaying the class schedule?  Keeping this method allows us to continue displaying "Daily."
</blockquote></details>

Yeah. Let's get rid of this. :)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/517)*

**Comment by geogor37** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/client/studentClassScheduleClient/model/Course.java, line 68 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/517#-L75Ss8v7md63ySEUvav:-L76qZitoTrYIdfYWfj2:b-h8v46m) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/028890068e3cefdb0d89c79ebda685c57ad2707c/support/src/main/java/edu/byu/support/client/studentClassScheduleClient/model/Course.java#L68)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Yeah. Let's get rid of this. :)
</blockquote></details>

Done. I went ahead and renamed it getDays as well since we're no longer distinguishing between two different methods.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/517)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/517)*

**Pull request merged**
