### PR TITLE
training -> dev

### PR DESCRIPTION
**Pull request by aarowhead**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/513)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 1 of 9 files at r1.
Review status: 1 of 9 files reviewed at latest revision, all discussions resolved.

---

*[app/src/main/AndroidManifest.xml, line 1000 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/513#-L5Pn_Bn1lKFBNPp6_8x:-L5Pn_Bn1lKFBNPp6_8y:b73tix9) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/ddc67cd5124860c04ebccc5b33dac093e3f302db/app/src/main/AndroidManifest.xml#L1000)):*
> ```XML
>             android:name=".features.carTraining.VehicleMenuActivity"
>             android:label="@string/vehicle_menu_activity_title"
>             android:parentActivityName=".mainScreen.FavoritesActivity">
> ```

Missing an icon

---

*[app/src/main/java/edu/byu/suite/features/carTraining/MakesActivity.java, line 28 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/513#-L5PngHU0NpQd1Mj3QN4:-L5PngHU0NpQd1Mj3QN5:brdm7fg) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/ddc67cd5124860c04ebccc5b33dac093e3f302db/app/src/main/java/edu/byu/suite/features/carTraining/MakesActivity.java#L28)):*
> ```Java
> 
> 	private static final String MAKE_CODESET_ID = "MAK";
> 	private final String TAG = MakesActivity.class.getSimpleName();
> ```

TAG should be static and should go at the top of the class

---

*[app/src/main/java/edu/byu/suite/features/carTraining/MakesActivity.java, line 29 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/513#-L5PncNn4jKoL3jwwFHO:-L5PncNn4jKoL3jwwFHP:bc9kmss) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/ddc67cd5124860c04ebccc5b33dac093e3f302db/app/src/main/java/edu/byu/suite/features/carTraining/MakesActivity.java#L29)):*
> ```Java
> 	private static final String MAKE_CODESET_ID = "MAK";
> 	private final String TAG = MakesActivity.class.getSimpleName();
> 	private ParkingClient.Api api;
> ```

Probably no need to save this up here. Inline it

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/513)*

**Comment by aarowhead** [comment]
Review status: 1 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/AndroidManifest.xml, line 1000 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/513#-L5Pn_Bn1lKFBNPp6_8x:-L5PnqjqJbnt2YjLuSAh:br9wil7) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/ddc67cd5124860c04ebccc5b33dac093e3f302db/app/src/main/AndroidManifest.xml#L1000)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Missing an icon
</blockquote></details>

Geoff told me that I don't need an icon.

---

*[app/src/main/java/edu/byu/suite/features/carTraining/MakesActivity.java, line 28 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/513#-L5PngHU0NpQd1Mj3QN4:-L5PoTOx_bZpdi_dn5uO:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/ddc67cd5124860c04ebccc5b33dac093e3f302db/app/src/main/java/edu/byu/suite/features/carTraining/MakesActivity.java#L28)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

TAG should be static and should go at the top of the class
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/carTraining/MakesActivity.java, line 29 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/513#-L5PncNn4jKoL3jwwFHO:-L5PozI75CXyQoVc7GIs:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/ddc67cd5124860c04ebccc5b33dac093e3f302db/app/src/main/java/edu/byu/suite/features/carTraining/MakesActivity.java#L29)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Probably no need to save this up here. Inline it
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/513)*

**Comment by geogor37** [comment]
Reviewed 8 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java, line 30 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/513#-L5QqYqp2b16439lXbkn:-L5QqYqp2b16439lXbko:b25pdm) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java#L30)):*
> ```Java
> 	private final String TAG = StatesActivity.class.getSimpleName();
> 
> 	private ParkingClient.Api api;
> ```

It looks like you could probably just inline this if you wanted.

---

*[app/src/main/java/edu/byu/suite/features/carTraining/VehiclesActivity.java, line 22 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/513#-L5QrBwf3kNWHES4NcaN:-L5QrBwf3kNWHES4NcaO:bgc4fzb) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/java/edu/byu/suite/features/carTraining/VehiclesActivity.java#L22)):*
> ```Java
> 	private final String TAG = VehiclesActivity.class.getSimpleName();
> 
> 	private ParkingClient.Api allVehiclesApi;
> ```

You could probably inline this one too

---

*[app/src/main/res/layout/vehicle_menu_content.xml, line 7 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/513#-L5Qrpc8wZBpWLrmshK6:-L5Qrpc8wZBpWLrmshK7:b-eurkta) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/res/layout/vehicle_menu_content.xml#L7)):*
> ```XML
>     android:layout_width="match_parent"
>     android:layout_height="match_parent"
>     app:layout_behavior="@string/appbar_scrolling_view_behavior"
> ```

What does this do?

---

*[app/src/main/res/layout/vehicle_menu_content.xml, line 13 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/513#-L5Qrx_6JN0S2SJMNbtM:-L5Qrx_6JN0S2SJMNbtN:b-w6ouff) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/res/layout/vehicle_menu_content.xml#L13)):*
> ```XML
>     <Button
>         android:id="@+id/vehicles_button"
>         android:layout_width="match_parent"
> ```

I think in ConstraintLayout it's preferable to set the width to 0 and constrain both the left and right sides to the parent rather than using "match_parent"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/513)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java, line 28 at r2](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/513#-L5Ua_LM7GiNn3v5iMXB:-L5Ua_LM7GiNn3v5iMXC:b-qfusq5) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java#L28)):*
> ```Java
> 
> 	private static final String STATE_CODESET_ID = "STA";
> 	private final String TAG = StatesActivity.class.getSimpleName();
> ```

TAG on top if needed (otherwise delete)

---

*[app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java, line 46 at r2](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/513#-L5UaBqq5t5RmzJb8LaW:-L5UaBqq5t5RmzJb8LaX:b-m4302y) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java#L46)):*
> ```Java
> 	public boolean onCreateOptionsMenu(Menu menu) {
> 		getMenuInflater().inflate(R.menu.search, menu);
> 		searchView = (SearchView) menu.findItem(R.id.search).getActionView();
> ```

Do you need the cast here?

---

*[app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java, line 52 at r2](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/513#-L5UbGRM98X7RmwVLPwc:-L5UbGRM98X7RmwVLPwd:b-pl8pxf) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java#L52)):*
> ```Java
> 
> 	private void getStates() {
> 		showProgressDialog("Retrieving states, please wait...");
> ```

See other comment

---

*[app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java, line 53 at r2](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/513#-L5UbHSP8pY8qGK7_FLX:-L5UbHSP8pY8qGK7_FLY:b-pl8pxf) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java#L53)):*
> ```Java
> 	private void getStates() {
> 		showProgressDialog("Retrieving states, please wait...");
> 		enqueueCall(api.getParkingCodes(STATE_CODESET_ID), new ByuCallback<List<ParkingCode>>(this, "Error retrieving states", "message") {
> ```

See other comment

---

*[app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java, line 53 at r2](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/513#-L5UbImk8bwo8uKpWNuf:-L5UbImk8bwo8uKpWNug:b413vku) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java#L53)):*
> ```Java
> 	private void getStates() {
> 		showProgressDialog("Retrieving states, please wait...");
> 		enqueueCall(api.getParkingCodes(STATE_CODESET_ID), new ByuCallback<List<ParkingCode>>(this, "Error retrieving states", "message") {
> ```

Do you understand what "message" is doing here?

---

*[app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java, line 64 at r2](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/513#-L5UbdCY9811RlxMwHNL:-L5UbdCY9811RlxMwHNM:b-e5qzmj) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java#L64)):*
> ```Java
> 			public void onFailure(Call<List<ParkingCode>> call, ByuError byuError) {
> 				dismissProgressDialog();
> 				Log.d(TAG, "onGetStatesFailure: " + byuError.getDebugMessage());
> ```

No log needed here

---

*[app/src/main/java/edu/byu/suite/features/carTraining/VehicleMenuActivity.java, line 21 at r2](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/513#-L5UWts9CUTlBbnmAFY-:-L5UWts9CUTlBbnmAFY0:b-sz8f07) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/java/edu/byu/suite/features/carTraining/VehicleMenuActivity.java#L21)):*
> ```Java
> 		setContentView(R.layout.vehicle_menu);
> 
> 		vehicleButton = (Button) findViewById(R.id.vehicles_button);
> ```

No cast should be required. This should be producing a warning in your Android Studio

---

*[app/src/main/java/edu/byu/suite/features/carTraining/VehicleMenuActivity.java, line 21 at r2](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/513#-L5UXFl766Y3B_VcImWN:-L5UXFl766Y3B_VcImWO:b-rq48x5) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/java/edu/byu/suite/features/carTraining/VehicleMenuActivity.java#L21)):*
> ```Java
> 		setContentView(R.layout.vehicle_menu);
> 
> 		vehicleButton = (Button) findViewById(R.id.vehicles_button);
> ```

Can you think of a way to simplify these 6 lines with a loop? When there's only 3 buttons, it might take about the same number of lines, but it would make the code easier to modify (by removing duplicate code)

---

*[app/src/main/java/edu/byu/suite/features/carTraining/VehiclesActivity.java, line 34 at r2](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/513#-L5UWYaq7kmqrzbF3_zh:-L5UWYaq7kmqrzbF3_zi:bnbdy0f) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/java/edu/byu/suite/features/carTraining/VehiclesActivity.java#L34)):*
> ```Java
> 
> 	private void getVehicles() {
> 		showProgressDialog("Retrieving vehicles, please wait...");
> ```

Normally we only pass in a string to this when there's something interesting to tell the user. Otherwise, for consistency, we use the default loading string.

---

*[app/src/main/java/edu/byu/suite/features/carTraining/VehiclesActivity.java, line 35 at r2](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/513#-L5UWgRyAl9w54yHj9p_:-L5UWgRyAl9w54yHj9pa:buomcwb) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/java/edu/byu/suite/features/carTraining/VehiclesActivity.java#L35)):*
> ```Java
> 	private void getVehicles() {
> 		showProgressDialog("Retrieving vehicles, please wait...");
> 		enqueueCall(allVehiclesApi.getAllVehicles(), new ByuCallback<List<Vehicle>>(this, "Error retrieving vehicles", "message") {
> ```

Normally we use the default error title, unless there's something interesting to tell the user. Otherwise, for consistency, we use the default error message.

---

*[app/src/main/res/layout/vehicle_menu_content.xml, line 7 at r2](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/513#-L5Qrpc8wZBpWLrmshK6:-L5UbgAhCaVYFbahVc63:b3kscq7) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/res/layout/vehicle_menu_content.xml#L7)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

What does this do?
</blockquote></details>

I would love to hear the answer to this as well :)

---

*[app/src/main/res/values/strings.xml, line 323 at r2](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/513#-L5UV6jF3C8tdY3z7ny0:-L5UV6jF3C8tdY3z7ny1:bii0ozy) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/res/values/strings.xml#L323)):*
> ```XML
> 	<string name="state_button">States</string>
> 	<string name="makes_button">Makes</string>
> 	<string name="vehicle_menu_activity_title">TEST</string>
> ```

Remove excess strings (if unneeded)

---

*[app/src/main/res/values/strings.xml, line 324 at r2](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/513#-L5UV91E5Z117V9QZl6y:-L5UV91E5Z117V9QZl6z:b-tf6ri5) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/res/values/strings.xml#L324)):*
> ```XML
> 	<string name="makes_button">Makes</string>
> 	<string name="vehicle_menu_activity_title">TEST</string>
> 	<string name="vehicle_menu_feature_id">vehicleTesting</string>
> ```

feature_ids have their own strings file in the support module

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/513)*

**Comment by aarowhead** [comment]
Review status: 5 of 9 files reviewed at latest revision, 16 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java, line 28 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/513#-L5Ua_LM7GiNn3v5iMXB:-L5p4vTLb8AL3TSwHHrN:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java#L28)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

TAG on top if needed (otherwise delete)
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java, line 30 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/513#-L5QqYqp2b16439lXbkn:-L5p6njywvffKVZf9yUt:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java#L30)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

It looks like you could probably just inline this if you wanted.
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java, line 46 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/513#-L5UaBqq5t5RmzJb8LaW:-L5p6yc_b9emKoDk63mc:bmv2kqn) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java#L46)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do you need the cast here?
</blockquote></details>

Yes. I get an error if I don't have it.

---

*[app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java, line 52 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/513#-L5UbGRM98X7RmwVLPwc:-L5pHqz4SdyIdSjoKqMm:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java#L52)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

See other comment
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java, line 53 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/513#-L5UbHSP8pY8qGK7_FLX:-L5pHru7CxQiOOVoSKsf:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java#L53)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

See other comment
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java, line 53 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/513#-L5UbImk8bwo8uKpWNuf:-L5pHyG_oyha_Gq2PPOr:b-v68imd) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java#L53)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do you understand what "message" is doing here?
</blockquote></details>

No I don't. I removed it but I would still like to understand better what it is used for.

---

*[app/src/main/java/edu/byu/suite/features/carTraining/VehicleMenuActivity.java, line 21 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/513#-L5UWts9CUTlBbnmAFY-:-L5pEhB6GRUBydMKGaPV:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/java/edu/byu/suite/features/carTraining/VehicleMenuActivity.java#L21)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

No cast should be required. This should be producing a warning in your Android Studio
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/carTraining/VehicleMenuActivity.java, line 21 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/513#-L5UXFl766Y3B_VcImWN:-L5pEhwvtKldkF5kvF4D:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/java/edu/byu/suite/features/carTraining/VehicleMenuActivity.java#L21)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Can you think of a way to simplify these 6 lines with a loop? When there's only 3 buttons, it might take about the same number of lines, but it would make the code easier to modify (by removing duplicate code)
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/carTraining/VehiclesActivity.java, line 22 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/513#-L5QrBwf3kNWHES4NcaN:-L5pFmv-wfWbQy5KiPvJ:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/java/edu/byu/suite/features/carTraining/VehiclesActivity.java#L22)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

You could probably inline this one too
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/carTraining/VehiclesActivity.java, line 34 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/513#-L5UWYaq7kmqrzbF3_zh:-L5pH0nD9hSxaxOOcihQ:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/java/edu/byu/suite/features/carTraining/VehiclesActivity.java#L34)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Normally we only pass in a string to this when there's something interesting to tell the user. Otherwise, for consistency, we use the default loading string.
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/carTraining/VehiclesActivity.java, line 35 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/513#-L5UWgRyAl9w54yHj9p_:-L5pH3ctgDZgbpXhooAR:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/java/edu/byu/suite/features/carTraining/VehiclesActivity.java#L35)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Normally we use the default error title, unless there's something interesting to tell the user. Otherwise, for consistency, we use the default error message.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/513)*

**Comment by romrell4** [comment]
Review status: 5 of 9 files reviewed at latest revision, 8 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java, line 53 at r2](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/513#-L5UbImk8bwo8uKpWNuf:-L5uGxGR5Cec2gw_6Kzi:bwsmwid) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java#L53)):*
<details><summary><i>Previously, aarowhead (Aaron Hill) wrote…</i></summary><blockquote>

No I don't. I removed it but I would still like to understand better what it is used for.
</blockquote></details>

You will want "message" in there again. I'll talk to you about it (you can also look into it and try to figure out how the API will use it)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/513)*

**Comment by aarowhead** [comment]
Review status: 3 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java, line 53 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/513#-L5UbImk8bwo8uKpWNuf:-L5umHrkBmCwL-_zF_Xp:btj1aoz) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java#L53)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

You will want "message" in there again. I'll talk to you about it (you can also look into it and try to figure out how the API will use it)
</blockquote></details>

It looks like "message" was the path to get the error message from the json response object in case of an error. Is that right? I've updated it to what I think is correct.

---

*[app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java, line 64 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/513#-L5UbdCY9811RlxMwHNL:-L5uPuFB97CTTVTkmyiN:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java#L64)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

No log needed here
</blockquote></details>

Done.

---

*[app/src/main/res/layout/vehicle_menu_content.xml, line 7 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/513#-L5Qrpc8wZBpWLrmshK6:-L5uf1iNrVlLKrrosydU:bav2xsm) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/res/layout/vehicle_menu_content.xml#L7)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I would love to hear the answer to this as well :)
</blockquote></details>

It doesn't do anything in this case. I just forgot to remove it after I copied it from another file. It has been removed.

---

*[app/src/main/res/layout/vehicle_menu_content.xml, line 13 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/513#-L5Qrx_6JN0S2SJMNbtM:-L5ui2XGy8fNjwfM_wBE:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/res/layout/vehicle_menu_content.xml#L13)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

I think in ConstraintLayout it's preferable to set the width to 0 and constrain both the left and right sides to the parent rather than using "match_parent"
</blockquote></details>

Done.

---

*[app/src/main/res/values/strings.xml, line 323 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/513#-L5UV6jF3C8tdY3z7ny0:-L5udczpoYFaUCmcwPbQ:b-h91se) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/res/values/strings.xml#L323)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove excess strings (if unneeded)
</blockquote></details>

So the titles and the button strings are the same but I separated them because I didn't think they would always have to be the same thing, there are conceivable scenarios where the button would say something different then the title. But if its more standard practice to combine those then I will change them.

---

*[app/src/main/res/values/strings.xml, line 324 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/513#-L5UV91E5Z117V9QZl6y:-L5udaJCZCXtqDAsELun:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/res/values/strings.xml#L324)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

feature_ids have their own strings file in the support module
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/513)*

**Comment by romrell4** [comment]
Review status: 3 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/carTraining/MakesActivity.java, line 27 at r3](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/513#-L5y6PHJ8VguM7ZDlLz6:-L5y6PHJ8VguM7ZDlLz7:b-b1mfsj) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/6fb7ec0e81752de59ca179c58e5d902907c44395/app/src/main/java/edu/byu/suite/features/carTraining/MakesActivity.java#L27)):*
> ```Java
> public class MakesActivity extends ByuRecyclerViewActivity {
> 
> 	private static final String TAG = MakesActivity.class.getSimpleName();
> ```

With the log removed, do we need this TAG anymore?

---

*[app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java, line 27 at r3](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/513#-L5y6UDR1kvI9n4jaEqc:-L5y6UDR1kvI9n4jaEqd:b-99ajhz) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/6fb7ec0e81752de59ca179c58e5d902907c44395/app/src/main/java/edu/byu/suite/features/carTraining/StatesActivity.java#L27)):*
> ```Java
> public class StatesActivity extends ByuRecyclerViewActivity {
> 
> 	private final String TAG = StatesActivity.class.getSimpleName();
> ```

static (if you still need it. I think this might not be used anymore...)

---

*[app/src/main/res/values/strings.xml, line 323 at r2](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/513#-L5UV6jF3C8tdY3z7ny0:-L5y71gQ8s39r5xqRr2e:b-sxncx9) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/111d26560bc84c53ef7defe664b2e2f6d9e3aec6/app/src/main/res/values/strings.xml#L323)):*
<details><summary><i>Previously, aarowhead (Aaron Hill) wrote…</i></summary><blockquote>

So the titles and the button strings are the same but I separated them because I didn't think they would always have to be the same thing, there are conceivable scenarios where the button would say something different then the title. But if its more standard practice to combine those then I will change them.
</blockquote></details>

No, that's great. However, the titles for the pages should be added to the manifest, instead of being set up manually

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/513)*

**Comment by romrell4** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/513)*

**Comment by romrell4** [comment]
Reviewed 1 of 9 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/513)*

**Pull request closed without merging**
