### PR TITLE
hotfix/chromeTabs -> dev

### PR DESCRIPTION
**Pull request by geogor37**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/471)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/activity/ByuActivity.java, line 156 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/471#-KyNfykTg7OObr0gJCnX:-KyNfykTg7OObr0gJCnY:b29v8qn) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/20fc97f50ed1f84a314a264b8ebfa0bb84cc7f9d/support/src/main/java/edu/byu/support/activity/ByuActivity.java#L156)):*
> ```Java
> 	}
> 
> 	public void startChromeTabView(final String url) {
> ```

Have you made the login stuff use this?

---

*[support/src/main/java/edu/byu/support/activity/ByuChromeTabsActivity.java, line 22 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/471#-KyNg6V5e-278nXtkt-s:-KyNg6V5e-278nXtkt-t:b-wwnoe1) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/20fc97f50ed1f84a314a264b8ebfa0bb84cc7f9d/support/src/main/java/edu/byu/support/activity/ByuChromeTabsActivity.java#L22)):*
> ```Java
> 	protected void onCreate(Bundle savedInstanceState) {
> 		super.onCreate(savedInstanceState);
> 		final int toolbarColor = ContextCompat.getColor(this, R.color.colorPrimary);
> ```

Duplicate code...

---

*[support/src/main/java/edu/byu/support/fragment/ByuFragment.java, line 105 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/471#-KyNgGo7VdmIofUHsdAM:-KyNgGo7VdmIofUHsdAN:b-dyts4t) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/20fc97f50ed1f84a314a264b8ebfa0bb84cc7f9d/support/src/main/java/edu/byu/support/fragment/ByuFragment.java#L105)):*
> ```Java
> 
> 	public void startChromeTabView(final String url) {
> 		final int toolbarColor = ContextCompat.getColor(getActivity(), R.color.colorPrimary);
> ```

Can we just call getActivity().startChromeTabView instead of duplicating?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/471)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/activity/ByuActivity.java, line 156 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/471#-KyNfykTg7OObr0gJCnX:-KyNgfGiPRvU6FXwP5c8:b-kw96nb) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/20fc97f50ed1f84a314a264b8ebfa0bb84cc7f9d/support/src/main/java/edu/byu/support/activity/ByuActivity.java#L156)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Have you made the login stuff use this?
</blockquote></details>

No because we do some things there that aren't really standard behavior (example: switching toolbar color to red when logging in to sandbox or closing the tab once the url is finished loading when logging out)

---

*[support/src/main/java/edu/byu/support/activity/ByuChromeTabsActivity.java, line 22 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/471#-KyNg6V5e-278nXtkt-s:-KyNh-dVx_9t2Dg_nna4:bzba1p6) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/20fc97f50ed1f84a314a264b8ebfa0bb84cc7f9d/support/src/main/java/edu/byu/support/activity/ByuChromeTabsActivity.java#L22)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Duplicate code...
</blockquote></details>

I didn't make this use the new method because here we finish the activity as soon as the tab opens, which we wouldn't want to be standard behavior.

---

*[support/src/main/java/edu/byu/support/fragment/ByuFragment.java, line 105 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/471#-KyNgGo7VdmIofUHsdAM:-KyNhH91UmXcNgXRubi-:b7ty8w) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/20fc97f50ed1f84a314a264b8ebfa0bb84cc7f9d/support/src/main/java/edu/byu/support/fragment/ByuFragment.java#L105)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Can we just call getActivity().startChromeTabView instead of duplicating?
</blockquote></details>

Yeah if I made it a static method, would you prefer that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/471)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/activity/ByuActivity.java, line 156 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/471#-KyNfykTg7OObr0gJCnX:-KyNhZMqJ9gEnKppzf1_:b-he7yg4) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/20fc97f50ed1f84a314a264b8ebfa0bb84cc7f9d/support/src/main/java/edu/byu/support/activity/ByuActivity.java#L156)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

No because we do some things there that aren't really standard behavior (example: switching toolbar color to red when logging in to sandbox or closing the tab once the url is finished loading when logging out)
</blockquote></details>

Create another constructor where you can pass in the color

---

*[support/src/main/java/edu/byu/support/activity/ByuChromeTabsActivity.java, line 22 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/471#-KyNg6V5e-278nXtkt-s:-KyNhd8a0jpSSPW1p9lq:b-vqzgjz) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/20fc97f50ed1f84a314a264b8ebfa0bb84cc7f9d/support/src/main/java/edu/byu/support/activity/ByuChromeTabsActivity.java#L22)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

I didn't make this use the new method because here we finish the activity as soon as the tab opens, which we wouldn't want to be standard behavior.
</blockquote></details>

Hmm.. Okay

---

*[support/src/main/java/edu/byu/support/fragment/ByuFragment.java, line 105 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/471#-KyNgGo7VdmIofUHsdAM:-KyNhQT12C_8MN1ttviR:b3in0j6) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/20fc97f50ed1f84a314a264b8ebfa0bb84cc7f9d/support/src/main/java/edu/byu/support/fragment/ByuFragment.java#L105)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

Yeah if I made it a static method, would you prefer that?
</blockquote></details>

Why wouldn't that make it static?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/471)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/activity/ByuActivity.java, line 156 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/471#-KyNfykTg7OObr0gJCnX:-KyNjizmE4entX-vHu77:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/20fc97f50ed1f84a314a264b8ebfa0bb84cc7f9d/support/src/main/java/edu/byu/support/activity/ByuActivity.java#L156)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Create another constructor where you can pass in the color
</blockquote></details>

Done.

---

*[support/src/main/java/edu/byu/support/fragment/ByuFragment.java, line 105 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/471#-KyNgGo7VdmIofUHsdAM:-KyNjpFVc4rCrEmZFZ5O:bjojir9) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/20fc97f50ed1f84a314a264b8ebfa0bb84cc7f9d/support/src/main/java/edu/byu/support/fragment/ByuFragment.java#L105)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why wouldn't that make it static?
</blockquote></details>

Actually I take that back, startChromeTabView can't be a static method because it needs a context to start the chromeTab, so we can't call it like that here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/471)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/fragment/ByuFragment.java, line 105 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/471#-KyNgGo7VdmIofUHsdAM:-KyNmiNqblgwF9u6SBNa:b-qs8y02) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/20fc97f50ed1f84a314a264b8ebfa0bb84cc7f9d/support/src/main/java/edu/byu/support/fragment/ByuFragment.java#L105)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

Actually I take that back, startChromeTabView can't be a static method because it needs a context to start the chromeTab, so we can't call it like that here.
</blockquote></details>

Do what we talked about

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/471)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/fragment/ByuFragment.java, line 105 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/471#-KyNgGo7VdmIofUHsdAM:-KyNndpv0DJZIyTYxXZZ:b-qxtqi5) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/20fc97f50ed1f84a314a264b8ebfa0bb84cc7f9d/support/src/main/java/edu/byu/support/fragment/ByuFragment.java#L105)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do what we talked about
</blockquote></details>

Done. Sorry for the confusion on my part! :slightly_smiling_face: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/471)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/471)*

**Pull request merged**
