### PR TITLE
hotfix/oauth -> dev

### PR DESCRIPTION
**Pull request by geogor37**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/481)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/login/account/PersonMetadataLookup.java, line 45 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/481#-Kz5s_m8rPTir8o3L8Lb:-Kz5s_m8rPTir8o3L8Lc:beuozrl) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/7ea01ec1eb37fdfb3e7cc6e4ecd25c5ad8f22620/support/src/main/java/edu/byu/support/login/account/PersonMetadataLookup.java#L45)):*
> ```Java
> 			AccountManager accountManager = AccountManager.get(context);
> 			String peekAuthToken = accountManager.peekAuthToken(account, TYPE_BEARER_TOKEN);
> 			OAuthToken authToken = new Gson().fromJson(peekAuthToken, OAuthToken.class);
> ```

What if this token isn't valid JSON... won't that NORMALLY be the case here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/481)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/login/account/PersonMetadataLookup.java, line 45 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/481#-Kz5s_m8rPTir8o3L8Lb:-Kz60fcWA-mdKH_5HqFE:bg7q9zs) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/7ea01ec1eb37fdfb3e7cc6e4ecd25c5ad8f22620/support/src/main/java/edu/byu/support/login/account/PersonMetadataLookup.java#L45)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What if this token isn't valid JSON... won't that NORMALLY be the case here?
</blockquote></details>

That's a good point... But if that's the case then the user should get an error before hitting our log statements in the ByuAccountAuthenticator as well because we do the same exact thing there.  Should I just send whatever is in peekAuthToken instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/481)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/login/account/PersonMetadataLookup.java, line 45 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/481#-Kz5s_m8rPTir8o3L8Lb:-Kz63VJ1istrJA8W8qSc:bchsax) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/7ea01ec1eb37fdfb3e7cc6e4ecd25c5ad8f22620/support/src/main/java/edu/byu/support/login/account/PersonMetadataLookup.java#L45)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

That's a good point... But if that's the case then the user should get an error before hitting our log statements in the ByuAccountAuthenticator as well because we do the same exact thing there.  Should I just send whatever is in peekAuthToken instead?
</blockquote></details>

Probably. Let's do that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/481)*

**Comment by geogor37** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/login/account/PersonMetadataLookup.java, line 45 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/481#-Kz5s_m8rPTir8o3L8Lb:-KzA5RuytiQt3nqpFghg:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/7ea01ec1eb37fdfb3e7cc6e4ecd25c5ad8f22620/support/src/main/java/edu/byu/support/login/account/PersonMetadataLookup.java#L45)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Probably. Let's do that
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/481)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/login/account/PersonMetadataLookup.java, line 45 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/481#-Kz5s_m8rPTir8o3L8Lb:-KzAT7Pa2vg9LYn8t0_N:b-qxxqkh) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/7ea01ec1eb37fdfb3e7cc6e4ecd25c5ad8f22620/support/src/main/java/edu/byu/support/login/account/PersonMetadataLookup.java#L45)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hmm... Still thinking. Talk to me about this one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/481)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/481)*

**Pull request closed without merging**
