### PR TITLE
repo-meta -> dev

### PR DESCRIPTION
**Pull request by geogor37**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/534)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[.repo-meta.yml, line 11 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/534#-LB0RIZQ4JxolYK00BJy:-LB0RIZQ4JxolYK00BJz:bc1rb7l) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/213f46ae49a2d610e938dc1024bd32d89cf26d88/.repo-meta.yml#L11)):*
> ```YAML
>     maintained_by:
>       - romrell4
>       - geogor37
> ```

Add arrowhead as well

---

*[.repo-meta.yml, line 27 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/534#-LB0dNdIDjCGVb8EidAD:-LB0dNdIDjCGVb8EidAE:b-qyzqta) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/213f46ae49a2d610e938dc1024bd32d89cf26d88/.repo-meta.yml#L27)):*
> ```YAML
>           depends_on:
>             software:
>               # - Academic Class Schedule Instructor Schedule web service
> ```

These should exist (api-repo-sandbox? Message Valinda or Dan McNeese or Jess Lyons)

---

*[.repo-meta.yml, line 33 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/534#-LB0R_we2kuhBZ8ooG6F:-LB0R_we2kuhBZ8ooG6G:bhiyf4) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/213f46ae49a2d610e938dc1024bd32d89cf26d88/.repo-meta.yml#L33)):*
> ```YAML
>               # - Academic Registration Offerings web service
>               # - Academic Registration Student Schedule web service
>               - cameras-rest # Campus Cameras web service
> ```

I don't think we actually rely on this one... Double check? I think this is an old web service that used to do what the campus-cameras-lambda does now

---

*[.repo-meta.yml, line 35 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/534#-LB0RmMkEZAtYOE99y05:-LB0RmMkEZAtYOE99y06:bl4khh3) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/213f46ae49a2d610e938dc1024bd32d89cf26d88/.repo-meta.yml#L35)):*
> ```YAML
>               - cameras-rest # Campus Cameras web service
>               - campus-cameras-lambda
>               # - Campus Locations web service
> ```

I think this one exists... https://github.com/byu-oit/stash_location-service Kim is rewriting it now. So you can add a comment saying that we can change this whenever Kim's done. Work with her to get the new github repo name

---

*[.repo-meta.yml, line 38 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/534#-LB0au2RCBci00HE2qYC:-LB0au2RCBci00HE2qYD:b-22plz) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/213f46ae49a2d610e938dc1024bd32d89cf26d88/.repo-meta.yml#L38)):*
> ```YAML
>               - byuapi-classes # Classes web service
>               - Cougar-Cash-Web-Services # Cougar Cash web service
>               # - Department Directory web service
> ```

I think this one might be erp-fs... I just did a real quick search for `apex_rest`, and found a lot of mobile app stuff, but then one in that repo.  Double check (probably message Luke)

---

*[.repo-meta.yml, line 41 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/534#-LB0bnqiAery2cx_i8Cy:-LB0bnqiAery2cx_i8Cz:b-3n3p5d) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/213f46ae49a2d610e938dc1024bd32d89cf26d88/.repo-meta.yml#L41)):*
> ```YAML
>               - dining-account-lambda # Dining Account web service
>               - dining-services-batch
>               # - Gallery web service
> ```

Ask Sherwin if there's a repo for galleries (probably not, since it's Drupal)

---

*[.repo-meta.yml, line 42 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/534#-LB0btKtEjkHsuYJULW8:-LB0btKtEjkHsuYJULW9:bpo5chq) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/213f46ae49a2d610e938dc1024bd32d89cf26d88/.repo-meta.yml#L42)):*
> ```YAML
>               - dining-services-batch
>               # - Gallery web service
>               # - Get_Sick_Vacation web service
> ```

This should exist (message Luke)

---

*[.repo-meta.yml, line 43 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/534#-LB0c47s5z0Qhv_xTKIY:-LB0c47s5z0Qhv_xTKIZ:b-vf3lc1) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/213f46ae49a2d610e938dc1024bd32d89cf26d88/.repo-meta.yml#L43)):*
> ```YAML
>               # - Gallery web service
>               # - Get_Sick_Vacation web service
>               # - Identity Access Is Member web service
> ```

These should all exist (maybe api-repo-sandbox). Message Valinda Rose or Dan McNeese for all "Identity" ones

---

*[.repo-meta.yml, line 49 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/534#-LB0cJoP6etFcGfJIXxn:-LB0cJoP6etFcGfJIXxo:bpo5chq) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/213f46ae49a2d610e938dc1024bd32d89cf26d88/.repo-meta.yml#L49)):*
> ```YAML
>               # - Identity Person PRO Address web service
>               # - Identity Person PRO Person ID Card web service
>               # - Job Openings web service
> ```

This should exist (message Luke)

---

*[.repo-meta.yml, line 56 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/534#-LB0cWDbE_phjy2iTxq3:-LB0cWDbE_phjy2iTxq4:b2777jj) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/213f46ae49a2d610e938dc1024bd32d89cf26d88/.repo-meta.yml#L56)):*
> ```YAML
>               - byu-mpn # Mobile Push Notifications web service
>               - mfc-shim-lambda # My Financial Center Mobile App Shim web service
>               # - Och Listings web service
> ```

This should exist (och?)

---

*[.repo-meta.yml, line 62 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/534#-LB0cr4YEpFwZAsbPibC:-LB0cr4YEpFwZAsbPibD:blwjnqd) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/213f46ae49a2d610e938dc1024bd32d89cf26d88/.repo-meta.yml#L62)):*
> ```YAML
>               # - SafeWalk web service
>               - byuapi-students # Students web service
>               # - TestingCenter_Location web service
> ```

These should exist (message Micah Weatherhead or Kevin Devocht)

---

*[.repo-meta.yml, line 65 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/534#-LB0cyuu1uypLMWMbXBx:-LB0cyuu1uypLMWMbXBy:b72b7kq) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/213f46ae49a2d610e938dc1024bd32d89cf26d88/.repo-meta.yml#L65)):*
> ```YAML
>               # - TestingCenter_StudentTest web service
>               # - Vending web service
>               # - Y-Time web service
> ```

This exists (ytime-shim-lambd) but put a comment that we will be moving away from the shim soon

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/534)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[.repo-meta.yml, line 33 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/534#-LB0R_we2kuhBZ8ooG6F:-LB1upF72N_OjERHmrUd:bi45o32) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/213f46ae49a2d610e938dc1024bd32d89cf26d88/.repo-meta.yml#L33)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

As far as I can tell, the mobile app doesn't ever call the lambda directly, at least not in Android.  This is the URL we use in the ByuCameraFeedClient: https://api.byu.edu/domains/legacy/cameras/v1/ , which seems to match up with cameras-rest.
</blockquote></details>

Do what we talked about on the phone.

---

*[.repo-meta.yml, line 35 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/534#-LB0RmMkEZAtYOE99y05:-LB1vYo1-7naZkmTAbw9:b-31g9w4) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/213f46ae49a2d610e938dc1024bd32d89cf26d88/.repo-meta.yml#L35)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Add the comment

---

*[.repo-meta.yml, line 38 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/534#-LB0au2RCBci00HE2qYC:-LB1vlOY3T1EW5gSVXKE:brimygn) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/213f46ae49a2d610e938dc1024bd32d89cf26d88/.repo-meta.yml#L38)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

Luke said they weren't in charge of this one. He told me to contact Mark Hales with University Financials, and I'm still waiting to hear back from him.
</blockquote></details>

Great. Keep waiting on him before we merge this :)

---

*[.repo-meta.yml, line 65 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/534#-LB0cyuu1uypLMWMbXBx:-LB1x8v516DIDq0NZVBR:b-s9607r) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/213f46ae49a2d610e938dc1024bd32d89cf26d88/.repo-meta.yml#L65)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

So I forgot to mention this to you before I left, but I searched for ytime-shim-lambda in the organization, and nothing came up.  Then I tried to run a git pull from within the directory on my machine, and it said the repository was not found... I'm adding it to the repo-meta, but I thought you might want to know that.
</blockquote></details>

Whoa... Calling you again

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/534)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[.repo-meta.yml, line 33 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/534#-LB0R_we2kuhBZ8ooG6F:-LB1yMtnEdki1jUSn0iz:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/213f46ae49a2d610e938dc1024bd32d89cf26d88/.repo-meta.yml#L33)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do what we talked about on the phone.
</blockquote></details>

Done.

---

*[.repo-meta.yml, line 35 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/534#-LB0RmMkEZAtYOE99y05:-LB1yS9H9MkgOKG62dpU:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/213f46ae49a2d610e938dc1024bd32d89cf26d88/.repo-meta.yml#L35)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Add the comment
</blockquote></details>

Done.

---

*[.repo-meta.yml, line 65 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/534#-LB0cyuu1uypLMWMbXBx:-LB234qLBL7POKKcuvAD:b-fxcm71) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/213f46ae49a2d610e938dc1024bd32d89cf26d88/.repo-meta.yml#L65)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Whoa... Calling you again
</blockquote></details>

We decided that you will need to restore the repo when you get back.

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/534)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/534)*

**Pull request merged**
