### PR TITLE
feature/learningSuite -> dev

### PR DESCRIPTION
**Pull request by geogor37**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/448)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/activity/CourseDetailActivity.java, line 56 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448#-Ksk6W2jwYjVhFasV5Bs:-Ksk6W2jwYjVhFasV5Bt:bnshu02) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/019a7a2b542552c481826166e205f6ffbc84c575/app/src/main/java/edu/byu/suite/features/learningSuite/activity/CourseDetailActivity.java#L56)):*
> ```Java
> 		if (savedInstanceState == null) {
> 			SpinnerUtils.setUpAdapter(this, spinner, courses, R.layout.ls_spinner_display_item, onItemSelectedListener);
> 			spinner.setSelection(intent.getIntExtra(POSITION, 0));
> ```

Could you explain what this change is doing?

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/fragment/CourseListFragment.java, line 54 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448#-Ksk7cnThZ5U-NfEs78_:-Ksk7cnThZ5U-NfEs78a:bjkzfy1) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/3fdf8f9bbf6ce31847586764960037c9b4cb59d1/app/src/main/java/edu/byu/suite/features/learningSuite/fragment/CourseListFragment.java#L54)):*
> ```Java
> 	public ArrayList<Object> separateByTerm(ArrayList<Course> courseList) {
> 		ArrayList<Object> separatedList = new ArrayList<>();
> 		String currentTerm = courseList.get(0).getPeriod();
> ```

What would happen if the list was empty here?

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/fragment/CourseListFragment.java, line 57 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448#-Ksk7Vwdey20COAbKvpE:-Ksk7Vwe-U3xDOFq9_vu:b-uywqf8) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/3fdf8f9bbf6ce31847586764960037c9b4cb59d1/app/src/main/java/edu/byu/suite/features/learningSuite/fragment/CourseListFragment.java#L57)):*
> ```Java
> 		separatedList.add(new HeaderAdapter.Header(new YearTerm(currentTerm).getDescription()));
> 		separatedList.add(courseList.get(0));
> 		for(int i = 1; i < courseList.size(); i++) {
> ```

Do they already come sorted? Or do we need to sort them first?

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/model/Course.java, line 86 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448#-KskU7VRzEM_P5OLF6-G:-KskU7VRzEM_P5OLF6-H:bubckvk) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/3fdf8f9bbf6ce31847586764960037c9b4cb59d1/app/src/main/java/edu/byu/suite/features/learningSuite/model/Course.java#L86)):*
> ```Java
> 	@Override
> 	public int compareTo(@NonNull Course o) {
> 		return Integer.parseInt(this.period) == Integer.parseInt(o.period) ? this.shortTitle.compareTo(o.shortTitle) : Integer.parseInt(o.period) - Integer.parseInt(this.period);
> ```

This looks like some duplicate logic. Let's separate it out:
```java
public int compareTo(@NonNull Course o) {
  int result = o.period.compareTo(this.period);
  if (result != 0) {
    return this.shortTitle.compareTo(o.shortTitle);
  }
  return result
}
```

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/model/Course.java, line 86 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448#-KskUviLx7Sa-0ybjsVH:-KskUviLx7Sa-0ybjsVI:bc2bj75) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/3fdf8f9bbf6ce31847586764960037c9b4cb59d1/app/src/main/java/edu/byu/suite/features/learningSuite/model/Course.java#L86)):*
> ```Java
> 	@Override
> 	public int compareTo(@NonNull Course o) {
> 		return Integer.parseInt(this.period) == Integer.parseInt(o.period) ? this.shortTitle.compareTo(o.shortTitle) : Integer.parseInt(o.period) - Integer.parseInt(this.period);
> ```

Will any of these ever be null? If so, we need to make this null-safe.

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/model/Course.java, line 86 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448#-KskV-k3RisFaHVwl3iI:-KskV-k3RisFaHVwl3iJ:b-3aiqye) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/3fdf8f9bbf6ce31847586764960037c9b4cb59d1/app/src/main/java/edu/byu/suite/features/learningSuite/model/Course.java#L86)):*
> ```Java
> 	@Override
> 	public int compareTo(@NonNull Course o) {
> 		return Integer.parseInt(this.period) == Integer.parseInt(o.period) ? this.shortTitle.compareTo(o.shortTitle) : Integer.parseInt(o.period) - Integer.parseInt(this.period);
> ```

Is there any reason why we can't use string comparison instead of casting to integers?

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/service/LearningSuiteClient.java, line 58 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448#-KskV5HKTe0DvRL2PKvU:-KskV5HKTe0DvRL2PKvV:b6m76wi) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/3fdf8f9bbf6ce31847586764960037c9b4cb59d1/app/src/main/java/edu/byu/suite/features/learningSuite/service/LearningSuiteClient.java#L58)):*
> ```Java
> 		@GET("coursebuilder/course/personEnrolled/{personId}/period/{yearTerm}")
> 		@Headers("Accept: application/json")
> 		Call<ArrayList<Course>> getCoursesForStudent(@Path("personId") String personId, @Path("yearTerm") String yearTerm);
> ```

Do we need this one anymore?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/activity/CourseDetailActivity.java, line 56 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448#-Ksk6W2jwYjVhFasV5Bs:-KsnUsnMNo0Dj2xDvz3T:b-61dd32) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/019a7a2b542552c481826166e205f6ffbc84c575/app/src/main/java/edu/byu/suite/features/learningSuite/activity/CourseDetailActivity.java#L56)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Could you explain what this change is doing?
</blockquote></details>

Yeah, because I switched the RecyclerView adapter to a DefaultHeaderAdapter and included Headers in the list that gets passed in to the adapter, the positions that were getting passed in to the CourseDetailActivity were off, so I added the selectedCourse as an extra in the Intent so that the index of that course in the original list can be determined and given to the spinner, which is what the next few lines are doing.

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/fragment/CourseListFragment.java, line 54 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448#-Ksk7cnThZ5U-NfEs78_:-KsnWisk1SOkuC_l0Odt:b-3lk7kl) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/3fdf8f9bbf6ce31847586764960037c9b4cb59d1/app/src/main/java/edu/byu/suite/features/learningSuite/fragment/CourseListFragment.java#L54)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What would happen if the list was empty here?
</blockquote></details>

It should never be empty because the code checks for that in the initializeView function in the MainActivity.

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/fragment/CourseListFragment.java, line 57 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448#-Ksk7Vwdey20COAbKvpE:-KsnXAbp0e0P-CEtyzka:bcuxwy7) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/3fdf8f9bbf6ce31847586764960037c9b4cb59d1/app/src/main/java/edu/byu/suite/features/learningSuite/fragment/CourseListFragment.java#L57)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do they already come sorted? Or do we need to sort them first?
</blockquote></details>

They do.  They get sorted in the loadCourses function.

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/service/LearningSuiteClient.java, line 58 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448#-KskV5HKTe0DvRL2PKvU:-KsnXR9DqI79HpOOw6F6:b1guvu4) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/3fdf8f9bbf6ce31847586764960037c9b4cb59d1/app/src/main/java/edu/byu/suite/features/learningSuite/service/LearningSuiteClient.java#L58)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do we need this one anymore?
</blockquote></details>

I wasn't sure, I left it in because if the user comes in from the MyNextClass feature I figured we'd only want to load up classes from the current semester, especially if they've taken the same class more than once, but I wanted to ask your opinion on that.  What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448)*

**Comment by geogor37** [comment]
Review status: 4 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/model/Course.java, line 86 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448#-KskU7VRzEM_P5OLF6-G:-KsngPKkxDCelHSMM04Y:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/3fdf8f9bbf6ce31847586764960037c9b4cb59d1/app/src/main/java/edu/byu/suite/features/learningSuite/model/Course.java#L86)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

This looks like some duplicate logic. Let's separate it out:
```java
public int compareTo(@NonNull Course o) {
  int result = o.period.compareTo(this.period);
  if (result != 0) {
    return this.shortTitle.compareTo(o.shortTitle);
  }
  return result
}
```
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/model/Course.java, line 86 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448#-KskV-k3RisFaHVwl3iI:-KsngdjmHinGI4HvtjtH:b-635wjg) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/3fdf8f9bbf6ce31847586764960037c9b4cb59d1/app/src/main/java/edu/byu/suite/features/learningSuite/model/Course.java#L86)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Is there any reason why we can't use string comparison instead of casting to integers?
</blockquote></details>

Nope, that works fine. I've made the change :)

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/model/Course.java, line 86 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448#-KskUviLx7Sa-0ybjsVH:-KsnhEDudIxUKmLFUIwN:b-j9j0zl) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/3fdf8f9bbf6ce31847586764960037c9b4cb59d1/app/src/main/java/edu/byu/suite/features/learningSuite/model/Course.java#L86)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Will any of these ever be null? If so, we need to make this null-safe.
</blockquote></details>

I don't think any of the values will ever be null, but I can go ahead and make it null-safe just in case if you'd like.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/activity/CourseDetailActivity.java, line 58 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448#-Ksnwxn7u-1rRFr-qVWc:-Ksnwxn7u-1rRFr-qVWd:by5zkn0) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/b6165699d5d7953f0df73d740fa5842b9c67a751/app/src/main/java/edu/byu/suite/features/learningSuite/activity/CourseDetailActivity.java#L58)):*
> ```Java
> 			Course selectedCourse = intent.getParcelableExtra(EXTRA_COURSE);
> 			int selectedCourseIndex = 0;
> 			for (int i = 0; i < courses.size(); i++) {
> ```

Possibly use an indexOf method (make sure to implement `.equals()`)

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/activity/CourseDetailActivity.java, line 61 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448#-KsnwbPyOMiRZHh0TdZJ:-KsnwbPyOMiRZHh0TdZK:b-7smvhi) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/b6165699d5d7953f0df73d740fa5842b9c67a751/app/src/main/java/edu/byu/suite/features/learningSuite/activity/CourseDetailActivity.java#L61)):*
> ```Java
> 				if (courses.get(i).getId().equals(selectedCourse.getId())) {
> 					selectedCourseIndex = i;
> 					i = courses.size();
> ```

break

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/fragment/CourseListFragment.java, line 54 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448#-Ksk7cnThZ5U-NfEs78_:-Ksnxvn1DLTA0xWWhnjM:b-edha9f) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/3fdf8f9bbf6ce31847586764960037c9b4cb59d1/app/src/main/java/edu/byu/suite/features/learningSuite/fragment/CourseListFragment.java#L54)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

It should never be empty because the code checks for that in the initializeView function in the MainActivity.
</blockquote></details>

Comment about that here then

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/service/LearningSuiteClient.java, line 58 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448#-KskV5HKTe0DvRL2PKvU:-KsnxnPXj-uvFeiVJUD4:b-82pg7r) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/3fdf8f9bbf6ce31847586764960037c9b4cb59d1/app/src/main/java/edu/byu/suite/features/learningSuite/service/LearningSuiteClient.java#L58)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

I wasn't sure, I left it in because if the user comes in from the MyNextClass feature I figured we'd only want to load up classes from the current semester, especially if they've taken the same class more than once, but I wanted to ask your opinion on that.  What do you think?
</blockquote></details>

Talk to me about this one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448)*

**Comment by geogor37** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/activity/CourseDetailActivity.java, line 58 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448#-Ksnwxn7u-1rRFr-qVWc:-Kso3VzM4lLB7fIz0RqQ:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/b6165699d5d7953f0df73d740fa5842b9c67a751/app/src/main/java/edu/byu/suite/features/learningSuite/activity/CourseDetailActivity.java#L58)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Possibly use an indexOf method (make sure to implement `.equals()`)
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/activity/CourseDetailActivity.java, line 61 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448#-KsnwbPyOMiRZHh0TdZJ:-Kso3hu-NS4Sr3F6m50l:bkarnxq) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/b6165699d5d7953f0df73d740fa5842b9c67a751/app/src/main/java/edu/byu/suite/features/learningSuite/activity/CourseDetailActivity.java#L61)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

break
</blockquote></details>

Not necessary after changing to the indexOf method.

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/fragment/CourseListFragment.java, line 54 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448#-Ksk7cnThZ5U-NfEs78_:-Kso4EZ3Zw3nCC4DZvQu:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/3fdf8f9bbf6ce31847586764960037c9b4cb59d1/app/src/main/java/edu/byu/suite/features/learningSuite/fragment/CourseListFragment.java#L54)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comment about that here then
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/service/LearningSuiteClient.java, line 58 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448#-KskV5HKTe0DvRL2PKvU:-KsoHtdeTPhhyXoecQSW:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/3fdf8f9bbf6ce31847586764960037c9b4cb59d1/app/src/main/java/edu/byu/suite/features/learningSuite/service/LearningSuiteClient.java#L58)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Talk to me about this one
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448)*

**Comment by romrell4** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/activity/CourseDetailActivity.java, line 57 at r3](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448#-KsoJYPoSKpeywxv1_KG:-KsoJYPoSKpeywxv1_KH:b7r5xui) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/762da19c33e24ecf7f8b478324cf22cd46056cfd/app/src/main/java/edu/byu/suite/features/learningSuite/activity/CourseDetailActivity.java#L57)):*
> ```Java
> 			SpinnerUtils.setUpAdapter(this, spinner, courses, R.layout.ls_spinner_display_item, onItemSelectedListener);
> 			Course selectedCourse = intent.getParcelableExtra(EXTRA_COURSE);
> 			int selectedCourseIndex = courses.indexOf(selectedCourse);
> ```

Comment

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/activity/LearningSuiteMainActivity.java, line 68 at r3](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448#-KsoJSsr-tyTNJlT8RmG:-KsoJSsr-tyTNJlT8RmH:b7r5xui) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/762da19c33e24ecf7f8b478324cf22cd46056cfd/app/src/main/java/edu/byu/suite/features/learningSuite/activity/LearningSuiteMainActivity.java#L68)):*
> ```Java
> 				public void onSuccess(Call<ArrayList<Course>> call, Response<ArrayList<Course>> response) {
> 					studentCourses = response.body();
> 					Collections.sort(studentCourses);
> ```

Comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448)*

**Comment by geogor37** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/activity/CourseDetailActivity.java, line 57 at r3](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448#-KsoJYPoSKpeywxv1_KG:-KsoKxygWi3GwE095Cxb:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/762da19c33e24ecf7f8b478324cf22cd46056cfd/app/src/main/java/edu/byu/suite/features/learningSuite/activity/CourseDetailActivity.java#L57)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comment
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/activity/LearningSuiteMainActivity.java, line 68 at r3](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448#-KsoJSsr-tyTNJlT8RmG:-KsoLGIv_remE0Ifrqbg:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/762da19c33e24ecf7f8b478324cf22cd46056cfd/app/src/main/java/edu/byu/suite/features/learningSuite/activity/LearningSuiteMainActivity.java#L68)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comment
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/448)*

**Pull request merged**
