### PR TITLE
hotfix/recyclerViewActivity -> dev

### PR DESCRIPTION
**Pull request by geogor37**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/499)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 17 of 17 files at r1, 10 of 10 files at r2, 1 of 7 files at r3.
Review status: 22 of 28 files reviewed at latest revision, 12 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2WreQ0vBTvWMIWUdFj:-L2WreQ0vBTvWMIWUdFk:b3akckq) (no related file):*
Test each of these features (to make sure we didn't mess anything up :p

---

*[app/src/main/java/edu/byu/suite/features/addDrop/controller/CourseDetailActivity.java, line 111 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2WbaFyw6wddi4nQ_d5:-L2WbaFyw6wddi4nQ_d6:b-89817p) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d2ca43b03210781f9a09319bedd20aff0088872a/app/src/main/java/edu/byu/suite/features/addDrop/controller/CourseDetailActivity.java#L111)):*
> ```Java
> 	}
> 
> //	TODO: Custom empty data text?
> ```

Do it

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java, line 33 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2WcHDcDXSIGGH3Gbud:-L2WcHDcDXSIGGH3Gbue:bc1f4b) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d2ca43b03210781f9a09319bedd20aff0088872a/app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java#L33)):*
> ```Java
>  * Created by cwoodfie on 10/10/16
>  */
> ```

Remove new line

---

*[app/src/main/java/edu/byu/suite/features/classRolls/controller/ClassRollActivity.java, line 67 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2WcpmutWMJqgnzDjE_:-L2WcpmutWMJqgnzDjEa:bb7462z) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d2ca43b03210781f9a09319bedd20aff0088872a/app/src/main/java/edu/byu/suite/features/classRolls/controller/ClassRollActivity.java#L67)):*
> ```Java
> 						//if there are no students that have registered for the class we show an error message.
> 						if (students.getStudents().size() == 0) {
> //							TODO: Should we still display this as an error? Or should we use the empty data text in the viewSwitcher instead?
> ```

TODO

---

*[app/src/main/java/edu/byu/suite/features/classRolls/controller/ClassRollsMainActivity.java, line 24 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2WcudHgc_WOoBSqj6s:-L2WcudHgc_WOoBSqj6t:bb7462z) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d2ca43b03210781f9a09319bedd20aff0088872a/app/src/main/java/edu/byu/suite/features/classRolls/controller/ClassRollsMainActivity.java#L24)):*
> ```Java
> import retrofit2.Response;
> 
> //	TODO: Delete old layout file (class_roles_activity_class_rolls_main)
> ```

TODO

---

*[app/src/main/java/edu/byu/suite/features/cougarCash/controller/CougarCashMainActivity.java, line 202 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2Wd6EL9CUdaQ_go26e:-L2Wd6EL9CUdaQ_go26f:bb7462z) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d2ca43b03210781f9a09319bedd20aff0088872a/app/src/main/java/edu/byu/suite/features/cougarCash/controller/CougarCashMainActivity.java#L202)):*
> ```Java
> 	}
> 
> //	TODO: Add custom empty data text?
> ```

TODO

---

*[app/src/main/java/edu/byu/suite/features/cougarCash/controller/PaymentMethodActivity.java, line 76 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2Wd8HKLh4RNsNy9jp8:-L2Wd8HKLh4RNsNy9jp9:bb7462z) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d2ca43b03210781f9a09319bedd20aff0088872a/app/src/main/java/edu/byu/suite/features/cougarCash/controller/PaymentMethodActivity.java#L76)):*
> ```Java
> 	}
> 
> //	TODO: Custom empty data text?
> ```

TODO

---

*[app/src/main/java/edu/byu/suite/features/lockerRental/controller/LockerRentalMainActivity.java, line 87 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2Wr3sI2U2NPC_O9Kf4:-L2Wr3sI2U2NPC_O9Kf5:bg6evfd) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d2ca43b03210781f9a09319bedd20aff0088872a/app/src/main/java/edu/byu/suite/features/lockerRental/controller/LockerRentalMainActivity.java#L87)):*
> ```Java
> 			@SuppressWarnings("unchecked")
> 			private void doneLoading() {
> 				adapter.setList(new ArrayList<>());
> ```

Instead of setting the adapter, should we just add to a list and it set once at the end? I'm open to the current option if you think it's better

---

*[app/src/main/java/edu/byu/suite/features/testingcenter/controller/ScoreActivity.java, line 23 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2Wrk92bS-xEjY-BFSv:-L2Wrk92bS-xEjY-BFSw:bb7462z) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d2ca43b03210781f9a09319bedd20aff0088872a/app/src/main/java/edu/byu/suite/features/testingcenter/controller/ScoreActivity.java#L23)):*
> ```Java
>  */
> 
> //	TODO: Delete the old layout file (testing_center_activity_score)
> ```

TODO

---

*[app/src/main/java/edu/byu/suite/features/testingcenter/controller/ScoreActivity.java, line 31 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2Wrq-M258U1fVy85aq:-L2Wrq-M258U1fVy85ar:b54qref) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d2ca43b03210781f9a09319bedd20aff0088872a/app/src/main/java/edu/byu/suite/features/testingcenter/controller/ScoreActivity.java#L31)):*
> ```Java
> 	@Override
> 	protected void onCreate(Bundle savedInstanceState) {
> 		super.onCreate(savedInstanceState);
> ```

Is this supposed to pass in the layout and have a warning to suppress?

---

*[app/src/main/java/edu/byu/suite/features/testingcenter/controller/ScoreActivity.java, line 45 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2Ws-IzbUubCIEMLBAf:-L2Ws-IzbUubCIEMLBAg:b-7atpee) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d2ca43b03210781f9a09319bedd20aff0088872a/app/src/main/java/edu/byu/suite/features/testingcenter/controller/ScoreActivity.java#L45)):*
> ```Java
> 			);
> 		}
> 		setAdapter(DefaultRecyclerAdapter.getDefaultRowAdapter(rows, R.layout.default_list_item_detail, null), true);
> ```

This look different than they other ones... Why?

---

*[support/src/main/java/edu/byu/support/activity/ByuRecyclerViewActivity.java, line 79 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2Wsv00p9KNqFyc2qD3:-L2Wsv00p9KNqFyc2qD4:b41g6m2) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d2ca43b03210781f9a09319bedd20aff0088872a/support/src/main/java/edu/byu/support/activity/ByuRecyclerViewActivity.java#L79)):*
> ```Java
> 
> 			@Override
> 			// This method detects changes when adapter.add, adapter.addAll, etc. are called
> ```

Ah interesting... So where is this going to actually get called? Give me an example of a feature. Does this replace what we used before to switch the view?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499)*

**Comment by romrell4** [comment]
Reviewed 6 of 7 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499)*

**Comment by geogor37** [comment]
Review status: 26 of 28 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2WreQ0vBTvWMIWUdFj:-L2XFWfGI-AWXcgCeciQ:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Test each of these features (to make sure we didn't mess anything up :p
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/addDrop/controller/CourseDetailActivity.java, line 111 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2WbaFyw6wddi4nQ_d5:-L2WzKUS1wvLV5CXTYDN:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d2ca43b03210781f9a09319bedd20aff0088872a/app/src/main/java/edu/byu/suite/features/addDrop/controller/CourseDetailActivity.java#L111)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do it
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java, line 33 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2WcHDcDXSIGGH3Gbud:-L2XFlmen-1NC7RYiZBm:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d2ca43b03210781f9a09319bedd20aff0088872a/app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java#L33)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove new line
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/classRolls/controller/ClassRollActivity.java, line 67 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2WcpmutWMJqgnzDjE_:-L2XFnbXMxiwdaZSTKwA:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d2ca43b03210781f9a09319bedd20aff0088872a/app/src/main/java/edu/byu/suite/features/classRolls/controller/ClassRollActivity.java#L67)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

TODO
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/classRolls/controller/ClassRollsMainActivity.java, line 24 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2WcudHgc_WOoBSqj6s:-L2XFtllssosi3idwhsn:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d2ca43b03210781f9a09319bedd20aff0088872a/app/src/main/java/edu/byu/suite/features/classRolls/controller/ClassRollsMainActivity.java#L24)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

TODO
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/cougarCash/controller/PaymentMethodActivity.java, line 76 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2Wd8HKLh4RNsNy9jp8:-L2XFvcgPEkxESEtWrkS:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d2ca43b03210781f9a09319bedd20aff0088872a/app/src/main/java/edu/byu/suite/features/cougarCash/controller/PaymentMethodActivity.java#L76)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

TODO
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/lockerRental/controller/LockerRentalMainActivity.java, line 87 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2Wr3sI2U2NPC_O9Kf4:-L2XIk1Jn_bGOQbm1Kpw:b-2jpgbq) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d2ca43b03210781f9a09319bedd20aff0088872a/app/src/main/java/edu/byu/suite/features/lockerRental/controller/LockerRentalMainActivity.java#L87)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Instead of setting the adapter, should we just add to a list and it set once at the end? I'm open to the current option if you think it's better
</blockquote></details>

That's fine with me; I think it's more consistent with how we do this in the other activities anyways.

---

*[app/src/main/java/edu/byu/suite/features/testingcenter/controller/ScoreActivity.java, line 23 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2Wrk92bS-xEjY-BFSv:-L2XGWlL2U8XJOvPkeoz:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d2ca43b03210781f9a09319bedd20aff0088872a/app/src/main/java/edu/byu/suite/features/testingcenter/controller/ScoreActivity.java#L23)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

TODO
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/testingcenter/controller/ScoreActivity.java, line 31 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2Wrq-M258U1fVy85aq:-L2XGZ2IrPAwvfK98lrX:bknlbh7) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d2ca43b03210781f9a09319bedd20aff0088872a/app/src/main/java/edu/byu/suite/features/testingcenter/controller/ScoreActivity.java#L31)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Is this supposed to pass in the layout and have a warning to suppress?
</blockquote></details>

Not here, this activity actually works fine with the default recycler view activity layout file

---

*[app/src/main/java/edu/byu/suite/features/testingcenter/controller/ScoreActivity.java, line 45 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2Ws-IzbUubCIEMLBAf:-L2XH1ZKQ5rbbtswOVm5:b-dfuzog) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d2ca43b03210781f9a09319bedd20aff0088872a/app/src/main/java/edu/byu/suite/features/testingcenter/controller/ScoreActivity.java#L45)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

This look different than they other ones... Why?
</blockquote></details>

Most of the other ones have the adapter as a member variable, but here we don't ever need to access the adapter later on, so it was inlined.

---

*[support/src/main/java/edu/byu/support/activity/ByuRecyclerViewActivity.java, line 79 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2Wsv00p9KNqFyc2qD3:-L2XHh8hnWtM9WulIPTw:b5p3m5c) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d2ca43b03210781f9a09319bedd20aff0088872a/support/src/main/java/edu/byu/support/activity/ByuRecyclerViewActivity.java#L79)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Ah interesting... So where is this going to actually get called? Give me an example of a feature. Does this replace what we used before to switch the view?
</blockquote></details>

Oh yeah, I totally forgot that I had added this! So I had noticed that sometimes the adapter wouldn't update automatically when we were adding items to the recyclerview, and in looking at the documentation for the adapterDataObserver I found out that this method needs to be overridden in order to ensure that behavior in certain situations.  Unfortunately I did this before the break, so I can't give you an example of where this helps us in the code because I don't remember where I was running into this issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499)*

**Comment by geogor37** [comment]
Review status: 22 of 28 files reviewed at latest revision, 5 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/cougarCash/controller/CougarCashMainActivity.java, line 202 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2Wd6EL9CUdaQ_go26e:-L2XV8dtIBkorDPmwIrm:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d2ca43b03210781f9a09319bedd20aff0088872a/app/src/main/java/edu/byu/suite/features/cougarCash/controller/CougarCashMainActivity.java#L202)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

TODO
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499)*

**Comment by romrell4** [comment]
Reviewed 2 of 7 files at r3, 4 of 4 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/lockerRental/controller/LockerRentalMainActivity.java, line 87 at r4](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2XVQkasZB1wvoqpoBd:-L2XVQkasZB1wvoqpoBe:b-rtm0le) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/8bf6631f4324f5d302ae1cd1e2b96d85c1326f57/app/src/main/java/edu/byu/suite/features/lockerRental/controller/LockerRentalMainActivity.java#L87)):*
> ```Java
> 			@SuppressWarnings("unchecked")
> 			private void doneLoading() {
> 				ArrayList<Object> lockerList = new ArrayList<>();
> ```

Save as List instead of ArrayList

---

*[support/src/main/java/edu/byu/support/activity/ByuRecyclerViewActivity.java, line 79 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2Wsv00p9KNqFyc2qD3:-L2XVhRrfMMhRsAJezxU:b4z75vr) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d2ca43b03210781f9a09319bedd20aff0088872a/support/src/main/java/edu/byu/support/activity/ByuRecyclerViewActivity.java#L79)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

Oh yeah, I totally forgot that I had added this! So I had noticed that sometimes the adapter wouldn't update automatically when we were adding items to the recyclerview, and in looking at the documentation for the adapterDataObserver I found out that this method needs to be overridden in order to ensure that behavior in certain situations.  Unfortunately I did this before the break, so I can't give you an example of where this helps us in the code because I don't remember where I was running into this issue.
</blockquote></details>

Gotcha. Talk to me about this one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499)*

**Comment by geogor37** [comment]
Review status: 24 of 46 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/lockerRental/controller/LockerRentalMainActivity.java, line 87 at r4](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2XVQkasZB1wvoqpoBd:-L2bFvrxUg5I_UNbgZT4:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/8bf6631f4324f5d302ae1cd1e2b96d85c1326f57/app/src/main/java/edu/byu/suite/features/lockerRental/controller/LockerRentalMainActivity.java#L87)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Save as List instead of ArrayList
</blockquote></details>

Done.

---

*[support/src/main/java/edu/byu/support/activity/ByuRecyclerViewActivity.java, line 79 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2Wsv00p9KNqFyc2qD3:-L2b_iyxIcDA9B7xXCW0:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/d2ca43b03210781f9a09319bedd20aff0088872a/support/src/main/java/edu/byu/support/activity/ByuRecyclerViewActivity.java#L79)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Gotcha. Talk to me about this one
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499)*

**Comment by romrell4** [comment]
Reviewed 22 of 22 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/activity/ByuRecyclerViewActivity.java, line 55 at r6](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2fGU-_HK8CT7WfTMhR:-L2fGU-_HK8CT7WfTMhS:bntng4f) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/ce6fddf1defbf78a5f33d1e8d8d8069089c85e67/support/src/main/java/edu/byu/support/activity/ByuRecyclerViewActivity.java#L55)):*
> ```Java
> 	 * Sets the adapter for the activity's RecyclerView. Sets a data observer on the adapter.
> 	 * switchViewIfNeeded() is called every time the adapter's elements are changed
> 	 * @param adapter 	The adapter to be set to the recyclerView
> ```

Add something to this javadoc about the null adapter list not switching the ViewSwitcher

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/activity/ByuRecyclerViewActivity.java, line 55 at r6](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499#-L2fGU-_HK8CT7WfTMhR:-L2g5IzWRgArazzxCP0e:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/ce6fddf1defbf78a5f33d1e8d8d8069089c85e67/support/src/main/java/edu/byu/support/activity/ByuRecyclerViewActivity.java#L55)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Add something to this javadoc about the null adapter list not switching the ViewSwitcher
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/499)*

**Pull request merged**
