### PR TITLE
feature/oauthDance -> dev

### PR DESCRIPTION
**Pull request by romrell4**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/466)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 1 of 26 files at r2, 62 of 70 files at r4.
Review status: 40 of 63 files reviewed at latest revision, 12 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466#-KwfALLOjBb04TQTnqqg:-KwfALLOjBb04TQTnqqh:b-b78xej) (no related file):*
Double check ChromeTabs remember me

---

*[app/src/main/java/edu/byu/suite/features/addDrop/controller/mySchedule/WaitlistFragment.java, line 11 at r4](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466#-Kwf615CbKvjCXJh13LI:-KwejUle6A91MW9uE3jh:b23my1h) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/277b07d0661758ed60a6e0d3bcfb8a0ac87f23a9/app/src/main/java/edu/byu/suite/features/addDrop/controller/mySchedule/WaitlistFragment.java#L11)):*
> ```Java
> import edu.byu.suite.features.addDrop.model.AddDropScheduledClassesWrapper;
> import edu.byu.suite.features.addDrop.service.StudentsClient;
> import edu.byu.support.activity.ByuActivity;
> ```

I just pushed a commit to optimize the imports again. Talk to me if you want to know how

---

*[app/src/main/java/edu/byu/suite/features/external/CampusShuttlesActivity.java, line 5 at r4](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466#-Kwf2Xmaaw5OqLZ7iuuk:-Kwf2Xmaaw5OqLZ7iuul:b-phqdui) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/277b07d0661758ed60a6e0d3bcfb8a0ac87f23a9/app/src/main/java/edu/byu/suite/features/external/CampusShuttlesActivity.java#L5)):*
> ```Java
> import edu.byu.support.activity.ByuExternalLinkActivity;
> 
> public class CampusShuttlesActivity extends ByuExternalLinkActivity {
> ```

Can we start using Chrome Tabs for these?

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java, line 251 at r4](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466#-Kwf9xZt4CHOwyCn4TSG:-Kwf9xZt4CHOwyCn4TSH:b-iiu763) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/277b07d0661758ed60a6e0d3bcfb8a0ac87f23a9/app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java#L251)):*
> ```Java
> 	private void logout() {
> 		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
> 			new CustomTabsIntent.Builder().setToolbarColor(getResources().getColor(R.color.colorPrimary, getTheme())).build().launchUrl(this, LOGOUT_URL);
> ```

Remove duplicate code here by saving the color with ternary, then setting the toolbar color on another line

---

*[support/src/main/AndroidManifest.xml, line 32 at r4](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466#-Kwg13QiOd4m063KgVwX:-Kwg13QiOd4m063KgVwY:b-uq1id3) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/277b07d0661758ed60a6e0d3bcfb8a0ac87f23a9/support/src/main/AndroidManifest.xml#L32)):*
> ```XML
> 		</service>
> 		<activity
> 				android:name=".login.LoginActivity"
> ```

Do we still have this with the ChromeTab?

---

*[support/src/main/java/edu/byu/support/login/LoginActivity.java, line 62 at r4](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466#-Kwg1OspDcQdATvKllS9:-Kwg1Osq-q0hrnDtBxKI:buhuug6) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/277b07d0661758ed60a6e0d3bcfb8a0ac87f23a9/support/src/main/java/edu/byu/support/login/LoginActivity.java#L62)):*
> ```Java
> 		String url = String.format(LOGIN_URL_FORMAT, USE_SANDBOX ? SANDBOX_CLIENT_ID : PROD_CLIENT_ID, androidId);
> 		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
> 			new CustomTabsIntent.Builder().setToolbarColor(getResources().getColor(R.color.colorPrimary, getTheme())).build().launchUrl(this, Uri.parse(url));
> ```

Save color outside on the line previous and replace if/else with ternary (to remove duplicate code)

---

*[support/src/main/java/edu/byu/support/login/LoginActivity.java, line 69 at r4](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466#-Kwg1imETj5qz-gF-mxe:-Kwg1imFofwpKDvSsOdY:b-jobf7f) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/277b07d0661758ed60a6e0d3bcfb8a0ac87f23a9/support/src/main/java/edu/byu/support/login/LoginActivity.java#L69)):*
> ```Java
> 
> 	@Override
> 	protected void onNewIntent (Intent intent) {
> ```

CMD OPT L (to remove space before `(`)

---

*[support/src/main/java/edu/byu/support/login/LoginActivity.java, line 88 at r4](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466#-Kwg2IslW_vK8GPzgULZ:-Kwg2IslW_vK8GPzgUL_:b26aszt) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/277b07d0661758ed60a6e0d3bcfb8a0ac87f23a9/support/src/main/java/edu/byu/support/login/LoginActivity.java#L88)):*
> ```Java
> 				token.setSandbox(USE_SANDBOX);
> 				// When we get the token, it has an expires_in but not an expire_date. setupExpireDate uses the current time and expires_in to set a expireDate field
> 				String accessToken = new Gson().toJson(token.setupExpireDate());
> ```

Explain this line to me...

---

*[support/src/main/java/edu/byu/support/login/LoginActivity.java, line 90 at r4](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466#-Kwg2NEXR0yW_SENB-II:-Kwg2NEXR0yW_SENB-IJ:b13kxz3) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/277b07d0661758ed60a6e0d3bcfb8a0ac87f23a9/support/src/main/java/edu/byu/support/login/LoginActivity.java#L90)):*
> ```Java
> 				String accessToken = new Gson().toJson(token.setupExpireDate());
> 				String username = token.getNetId();
> 				if (username == null) {
> ```

Should this actually be a part of `isValid()`?

---

*[support/src/main/java/edu/byu/support/login/LoginActivity.java, line 104 at r4](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466#-Kwg2UNdbOfuWN-NkYkr:-Kwg2UNdbOfuWN-NkYks:b7orp7g) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/277b07d0661758ed60a6e0d3bcfb8a0ac87f23a9/support/src/main/java/edu/byu/support/login/LoginActivity.java#L104)):*
> ```Java
> 						public void doneLoading(AccountInformation result) {
> 							progressDialog.dismiss();
> //							((InputMethodManager) getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(getCurrentFocus().getWindowToken(), 0);
> ```

Why is this commented out?

---

*[support/src/main/java/edu/byu/support/retrofit/ByuCallback.java, line 129 at r4](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466#-Kwg4vn_uik0s1XP2kv4:-Kwg4vn_uik0s1XP2kv5:bsqp6y4) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/277b07d0661758ed60a6e0d3bcfb8a0ac87f23a9/support/src/main/java/edu/byu/support/retrofit/ByuCallback.java#L129)):*
> ```Java
> 					context.startService(new Intent(context, RegisterWithMpnService.class).putExtra(RegisterWithMpnService.ACTION, RegisterWithMpnService.Action.LOGOUT));
> 					if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
> 						CookieManager.getInstance().removeAllCookies(null);
> ```

Do we still have to do anything with cookies? I think that logic can go away if we don't get cookies anyways. Also, let's compare this to what's in iOS.

---

*[support/src/main/res/layout/login_activity.xml, line 2 at r4](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466#-Kwg5QrIVeEzTUYfL_DU:-Kwg5QrIVeEzTUYfL_DV:b-375viu) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/277b07d0661758ed60a6e0d3bcfb8a0ac87f23a9/support/src/main/res/layout/login_activity.xml#L2)):*
> ```XML
> <?xml version="1.0" encoding="utf-8"?>
> <android.support.constraint.ConstraintLayout
> ```

Do we still need this if we're doing the ChromeTabs?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466)*

**Comment by romrell4** [comment]
Reviewed 23 of 23 files at r5.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/external/CampusShuttlesActivity.java, line 5 at r4](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466#-Kwf2Xmaaw5OqLZ7iuuk:-KwgK5JanR0wno-DLw7S:b46rrip) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/277b07d0661758ed60a6e0d3bcfb8a0ac87f23a9/app/src/main/java/edu/byu/suite/features/external/CampusShuttlesActivity.java#L5)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

I don't see why not, is that something we'd wanna do in another branch?
</blockquote></details>

Let's do that :)

---

*[support/src/main/java/edu/byu/support/login/LoginActivity.java, line 88 at r4](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466#-Kwg2IslW_vK8GPzgULZ:-KwgKG_UwXWx07wEwNw8:b-oqaffm) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/277b07d0661758ed60a6e0d3bcfb8a0ac87f23a9/support/src/main/java/edu/byu/support/login/LoginActivity.java#L88)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

This sets the token's expiration date based on the expires_in value that came with it when it was returned from the server and then saves it as a JSON string.
</blockquote></details>

Oh... Does token.setupExpireDate return the token then?

---

*[support/src/main/java/edu/byu/support/login/LoginActivity.java, line 90 at r4](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466#-Kwg2NEXR0yW_SENB-II:-KwgKORisXQp9eYgeEBm:btojbfq) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/277b07d0661758ed60a6e0d3bcfb8a0ac87f23a9/support/src/main/java/edu/byu/support/login/LoginActivity.java#L90)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

Well if this is true, then the token we got back was technically valid but something went wrong when we tried to decode the Base64 of the idToken.  I'm pretty sure the token would still be usable, right?  We just wouldn't be able to get a username to associate with it.
</blockquote></details>

Great.

---

*[support/src/main/java/edu/byu/support/login/LoginActivity.java, line 104 at r4](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466#-Kwg2UNdbOfuWN-NkYkr:-KwgKbGCU02Z4H_3QhCL:b-zgnsdt) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/277b07d0661758ed60a6e0d3bcfb8a0ac87f23a9/support/src/main/java/edu/byu/support/login/LoginActivity.java#L104)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

I have to admit I'm not 100% sure.  Honestly I don't know what this line of code would be doing.  Looking back at some previous commits, I think this was something that got added in when we were trying to implement the login with a webView, so when we switched back I'm guessing I commented this out to see whether we still needed it or not and then I forgot about it. :slightly_smiling_face: 
</blockquote></details>

This makes the keyboard disappear. Do we need it anymore? If not, remove the comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/external/CampusShuttlesActivity.java, line 5 at r4](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466#-Kwf2Xmaaw5OqLZ7iuuk:-KwgL-cR4canavPmwmWQ:b-p8xtcs) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/277b07d0661758ed60a6e0d3bcfb8a0ac87f23a9/app/src/main/java/edu/byu/suite/features/external/CampusShuttlesActivity.java#L5)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Let's do that :)
</blockquote></details>

Ok, I just added it to the Visual Task Board

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466)*

**Comment by geogor37** [comment]
Review status: 62 of 63 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[support/src/main/java/edu/byu/support/login/LoginActivity.java, line 88 at r4](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466#-Kwg2IslW_vK8GPzgULZ:-KwjpBbb-MFPTFV_QDIF:b2nhswy) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/277b07d0661758ed60a6e0d3bcfb8a0ac87f23a9/support/src/main/java/edu/byu/support/login/LoginActivity.java#L88)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Oh... Does token.setupExpireDate return the token then?
</blockquote></details>

Yes

---

*[support/src/main/java/edu/byu/support/login/LoginActivity.java, line 90 at r4](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466#-Kwg2NEXR0yW_SENB-II:-KwjpFOMm3KZ9eEU71mQ:bdyk8sy) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/277b07d0661758ed60a6e0d3bcfb8a0ac87f23a9/support/src/main/java/edu/byu/support/login/LoginActivity.java#L90)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Great.
</blockquote></details>

So this is good then?

---

*[support/src/main/java/edu/byu/support/login/LoginActivity.java, line 104 at r4](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466#-Kwg2UNdbOfuWN-NkYkr:-Kwjr2hDVVnhiRGU-CNp:bpu6gce) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/277b07d0661758ed60a6e0d3bcfb8a0ac87f23a9/support/src/main/java/edu/byu/support/login/LoginActivity.java#L104)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

This makes the keyboard disappear. Do we need it anymore? If not, remove the comment
</blockquote></details>

Yeah it looks like that line actually causes it to crash, so I took it out

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/login/LoginActivity.java, line 90 at r4](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466#-Kwg2NEXR0yW_SENB-II:-KwjsU35qI1r4eQgYX5a:b-k424cn) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/277b07d0661758ed60a6e0d3bcfb8a0ac87f23a9/support/src/main/java/edu/byu/support/login/LoginActivity.java#L90)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

So this is good then?
</blockquote></details>

Yes. I've already marked it as complete on my end. You just have to acknowledge it :)

---

*[support/src/main/java/edu/byu/support/login/LoginActivity.java, line 104 at r4](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466#-Kwg2UNdbOfuWN-NkYkr:-Kwjs_Q7pOLS1zt02bvd:bbw3vue) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/277b07d0661758ed60a6e0d3bcfb8a0ac87f23a9/support/src/main/java/edu/byu/support/login/LoginActivity.java#L104)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

Yeah it looks like that line actually causes it to crash, so I took it out
</blockquote></details>

Great. It seems that you're reviewable isn't marking these as done. Please mark this as done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/login/LoginActivity.java, line 104 at r4](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466#-Kwg2UNdbOfuWN-NkYkr:-Kwjw79HRw9XeId9O84Z:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/277b07d0661758ed60a6e0d3bcfb8a0ac87f23a9/support/src/main/java/edu/byu/support/login/LoginActivity.java#L104)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Great. It seems that you're reviewable isn't marking these as done. Please mark this as done
</blockquote></details>

Done.

---

*[support/src/main/java/edu/byu/support/retrofit/ByuCallback.java, line 129 at r4](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466#-Kwg4vn_uik0s1XP2kv4:-KwjvgInb5npnfe2EU3m:be6ll4w) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/277b07d0661758ed60a6e0d3bcfb8a0ac87f23a9/support/src/main/java/edu/byu/support/retrofit/ByuCallback.java#L129)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do we still have to do anything with cookies? I think that logic can go away if we don't get cookies anyways. Also, let's compare this to what's in iOS.
</blockquote></details>

It looks like you're right and there's now no need for cookies at all.  What is it you want me to compare?  Whether or not cookies are still being used?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466)*

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/retrofit/ByuCallback.java, line 129 at r4](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466#-Kwg4vn_uik0s1XP2kv4:-Kwk-BuaWkb0IBQciAMq:b-az2r9o) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/277b07d0661758ed60a6e0d3bcfb8a0ac87f23a9/support/src/main/java/edu/byu/support/retrofit/ByuCallback.java#L129)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

It looks like you're right and there's now no need for cookies at all.  What is it you want me to compare?  Whether or not cookies are still being used?
</blockquote></details>

Let's compare the UI flow with invalid refresh tokens

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466)*

**Comment by geogor37** [comment]
Review status: 63 of 65 files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/retrofit/ByuCallback.java, line 129 at r4](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466#-Kwg4vn_uik0s1XP2kv4:-KwkKAMXTMmzSTE0VCzB:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/277b07d0661758ed60a6e0d3bcfb8a0ac87f23a9/support/src/main/java/edu/byu/support/retrofit/ByuCallback.java#L129)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Let's compare the UI flow with invalid refresh tokens
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/myFinancialCenter/controller/UnpaidChargesFragment.java, line 84 at r9](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466#-KwkKHWiIplzvlvA0tt0:-KwkKHWiIplzvlvA0tt1:b-ikhn1u) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/6631f77714edde20c06cad7eeed830cb8d64706e/app/src/main/java/edu/byu/suite/features/myFinancialCenter/controller/UnpaidChargesFragment.java#L84)):*
> ```Java
> 			public void onFailure(Call<List<Charge>> call, ByuError byuError) {
> 				dismissProgressDialog();
> 				if (byuError.getResponse() != null && byuError.getResponse().code() == 418) {
> ```

Let's look at this one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466)*

**Comment by geogor37** [comment]
Review status: 65 of 66 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/myFinancialCenter/controller/UnpaidChargesFragment.java, line 84 at r9](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466#-KwkKHWiIplzvlvA0tt0:-KwkPXj61GUHTomqCwRH:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/6631f77714edde20c06cad7eeed830cb8d64706e/app/src/main/java/edu/byu/suite/features/myFinancialCenter/controller/UnpaidChargesFragment.java#L84)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Let's look at this one
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466)*

**Comment by romrell4** [comment]
Reviewed 1 of 2 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466)*

**Comment by romrell4** [comment]
Reviewed 8 of 9 files at r11, 5 of 5 files at r12.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/466)*

**Pull request merged**
