### PR TITLE
byuFragmentToSupport -> dev

### PR DESCRIPTION
**Pull request by aarowhead**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/569)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 35 of 35 files at r1.
Review status: all files reviewed, 7 unresolved discussions (waiting on @aarowhead)

---

*[app/src/main/java/edu/byu/suite/features/myClasses/MyClassesMapFragment.kt, line 29 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/569#-LFY5SmfDjJA3w1H8Xl3:-LFY5SmfDjJA3w1H8Xl4:bbxg8jr) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9d501ddef01e752d6146576b15d4be43af8960b1/app/src/main/java/edu/byu/suite/features/myClasses/MyClassesMapFragment.kt#L29)):*
> ```Kotlin
> 	override fun onMapReady(googleMap: GoogleMap?) {
> 		super.onMapReady(googleMap)
> 		val buildings: List<Building>? = arguments?.getParcelableArrayList(BUILDINGS)
> ```

What happened here?

---

*[app/src/main/java/edu/byu/suite/features/testingCenter/controller/ScheduleFragment.kt, line 80 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/569#-LFY5aDU4OMwyG-xW4gz:-LFY5aDU4OMwyG-xW4h-:b-a68zpq) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f30136fda47a09dfa91577830cae3e7a35bc389d/app/src/main/java/edu/byu/suite/features/testingCenter/controller/ScheduleFragment.kt#L80)):*
> ```Kotlin
> 
> 		override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ByuViewHolder<CenterHour> {
> 			return ScheduleViewHolder(activity.inflate(parent, R.layout.testing_center_list_item_hours))
> ```

What was this change for?

---

*[app/src/main/java/edu/byu/suite/features/testingCenter/controller/ScoresFragment.kt, line 99 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/569#-LFY5dtCDz29jiScFFET:-LFY5dtCDz29jiScFFEU:b-a68zpq) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9d501ddef01e752d6146576b15d4be43af8960b1/app/src/main/java/edu/byu/suite/features/testingCenter/controller/ScoresFragment.kt#L99)):*
> ```Kotlin
> 
> 	private fun setUpSpinnerAdapter() {
> 		context?.let{
> ```

What was this change for?

---

*[support/src/main/java/edu/byu/support/fragment/ByuFragment.kt, line 44 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/569#-LFY5mkFA4JfZ6LJjpSJ:-LFY5mkFA4JfZ6LJjpSK:b-mahoy5) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9d501ddef01e752d6146576b15d4be43af8960b1/support/src/main/java/edu/byu/support/fragment/ByuFragment.kt#L44)):*
> ```Kotlin
> 	private var activity: ByuActivity? = null
> 
> 	open fun getTitle(): String? = arguments?.getString(TITLE)
> ```

Is arguments nullable in the support fragment, but not the regular one?

---

*[support/src/main/java/edu/byu/support/fragment/CamerasGridFragment.kt, line 62 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/569#-LFY5xJ7BgW9kP36a1V4:-LFY5xJ7BgW9kP36a1V5:blthjww) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9d501ddef01e752d6146576b15d4be43af8960b1/support/src/main/java/edu/byu/support/fragment/CamerasGridFragment.kt#L62)):*
> ```Kotlin
> 		val layerDrawable = expandedCameraView?.camera_view_progress_bar?.progressDrawable as LayerDrawable
> 		val drawable = layerDrawable.getDrawable(2)
> 		activity?.let{ drawable.setColorFilter(ContextCompat.getColor(it, R.color.colorAccent), PorterDuff.Mode.SRC_IN) }
> ```

Why is activity nullable now? Just something in the support?

---

*[support/src/main/java/edu/byu/support/fragment/CamerasGridFragment.kt, line 62 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/569#-LFY613b-YUpudQLEdpK:-LFY613b-YUpudQLEdpL:bf7b7i2) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9d501ddef01e752d6146576b15d4be43af8960b1/support/src/main/java/edu/byu/support/fragment/CamerasGridFragment.kt#L62)):*
> ```Kotlin
> 		val layerDrawable = expandedCameraView?.camera_view_progress_bar?.progressDrawable as LayerDrawable
> 		val drawable = layerDrawable.getDrawable(2)
> 		activity?.let{ drawable.setColorFilter(ContextCompat.getColor(it, R.color.colorAccent), PorterDuff.Mode.SRC_IN) }
> ```

CMD-OPT-L

---

*[support/src/main/java/edu/byu/support/fragment/CamerasGridFragment.kt, line 232 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/569#-LFY62ES5CdNGwdeIw9x:-LFY62ES5CdNGwdeIw9y:bf7b7i2) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9d501ddef01e752d6146576b15d4be43af8960b1/support/src/main/java/edu/byu/support/fragment/CamerasGridFragment.kt#L232)):*
> ```Kotlin
> 			val layerDrawable = displayFeed.camera_view_progress_bar?.progressDrawable as LayerDrawable
> 			val drawable = layerDrawable.getDrawable(2)
> 			activity?.let{ drawable.setColorFilter(ContextCompat.getColor(it, R.color.colorAccent), PorterDuff.Mode.SRC_IN) }
> ```

CMD-OPT-L

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/569)*

**Comment by romrell4** [comment]
Review status: all files reviewed, 8 unresolved discussions (waiting on @aarowhead)

---

*[a discussion](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/569#-LFY66QH1yuC2o9_o_Lj:-LFY66QH1yuC2o9_o_Lk:b-u08jht) (no related file):*
Test each and every modified feature (briefly) to make sure that this all works

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/569)*

**Comment by aarowhead** [comment]
Review status: 33 of 35 files reviewed, 8 unresolved discussions (waiting on @romrell4 and @aarowhead)

---

*[app/src/main/java/edu/byu/suite/features/myClasses/MyClassesMapFragment.kt, line 29 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/569#-LFY5SmfDjJA3w1H8Xl3:-LFYALqi-Fbz2ezJOv01:b-97estp) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9d501ddef01e752d6146576b15d4be43af8960b1/app/src/main/java/edu/byu/suite/features/myClasses/MyClassesMapFragment.kt#L29)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What happened here?
</blockquote></details>

It seems that the arguments on the support fragment are nullable but they weren't on the previous fragment type.

---

*[app/src/main/java/edu/byu/suite/features/testingCenter/controller/ScheduleFragment.kt, line 80 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/569#-LFY5aDU4OMwyG-xW4gz:-LFYAj2s8jJ16mL7J_Xo:br5c4fm) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f30136fda47a09dfa91577830cae3e7a35bc389d/app/src/main/java/edu/byu/suite/features/testingCenter/controller/ScheduleFragment.kt#L80)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What was this change for?
</blockquote></details>

The activity on the fragment is now nullable so I would have to do a null check with activity. I've changed it again to use the layoutInflator because I think that is a better way to do it.

---

*[app/src/main/java/edu/byu/suite/features/testingCenter/controller/ScoresFragment.kt, line 99 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/569#-LFY5dtCDz29jiScFFET:-LFYDiJS4eqlcBydmF0W:bbhrm14) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9d501ddef01e752d6146576b15d4be43af8960b1/app/src/main/java/edu/byu/suite/features/testingCenter/controller/ScoresFragment.kt#L99)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What was this change for?
</blockquote></details>

The context is nullable on the support fragment. I guess they recently updated the annotations on the support library to make it clearer to Kotlin whether it was nullable or not nullable.

---

*[support/src/main/java/edu/byu/support/fragment/ByuFragment.kt, line 44 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/569#-LFY5mkFA4JfZ6LJjpSJ:-LFYEqEW-Lf-YII8GdPJ:b-lnmd20) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9d501ddef01e752d6146576b15d4be43af8960b1/support/src/main/java/edu/byu/support/fragment/ByuFragment.kt#L44)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Is arguments nullable in the support fragment, but not the regular one?
</blockquote></details>

From what I have read it seems that they have just updated the annotations on the supportFragment to clarify what is nullable and not nullable. From what I understand the regular one just doesn't have the annotations.

---

*[support/src/main/java/edu/byu/support/fragment/CamerasGridFragment.kt, line 62 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/569#-LFY5xJ7BgW9kP36a1V4:-LFYF97D-oLEoiYMZ0Rg:b-fct2so) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9d501ddef01e752d6146576b15d4be43af8960b1/support/src/main/java/edu/byu/support/fragment/CamerasGridFragment.kt#L62)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why is activity nullable now? Just something in the support?
</blockquote></details>

See other comments.

---

*[support/src/main/java/edu/byu/support/fragment/CamerasGridFragment.kt, line 62 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/569#-LFY613b-YUpudQLEdpK:-LFYFS83DJwi4P2V71Bn:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9d501ddef01e752d6146576b15d4be43af8960b1/support/src/main/java/edu/byu/support/fragment/CamerasGridFragment.kt#L62)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

CMD-OPT-L
</blockquote></details>

Done.

---

*[support/src/main/java/edu/byu/support/fragment/CamerasGridFragment.kt, line 232 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/569#-LFY62ES5CdNGwdeIw9x:-LFYFX0m3as4FBt6balG:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9d501ddef01e752d6146576b15d4be43af8960b1/support/src/main/java/edu/byu/support/fragment/CamerasGridFragment.kt#L232)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

CMD-OPT-L
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/569)*

**Comment by romrell4** [comment]
Reviewed 1 of 35 files at r1, 2 of 2 files at r2.
Review status: all files reviewed, 3 unresolved discussions (waiting on @romrell4 and @aarowhead)

---

*[app/src/main/java/edu/byu/suite/features/testingCenter/controller/ScheduleFragment.kt, line 80 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/569#-LFY5aDU4OMwyG-xW4gz:-LFYpWhZ6m4h524LG3FA:b-qizqep) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f30136fda47a09dfa91577830cae3e7a35bc389d/app/src/main/java/edu/byu/suite/features/testingCenter/controller/ScheduleFragment.kt#L80)):*
<details><summary><i>Previously, aarowhead (Aaron Hill) wrote…</i></summary><blockquote>

The activity on the fragment is now nullable so I would have to do a null check with activity. I've changed it again to use the layoutInflator because I think that is a better way to do it.
</blockquote></details>

I think we created an extension to do this. Look for it

---

*[app/src/main/java/edu/byu/suite/features/testingCenter/controller/ScoresFragment.kt, line 99 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/569#-LFY5dtCDz29jiScFFET:-LFYpbenDcr9LZJ-_DZi:bf7b7i2) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9d501ddef01e752d6146576b15d4be43af8960b1/app/src/main/java/edu/byu/suite/features/testingCenter/controller/ScoresFragment.kt#L99)):*
<details><summary><i>Previously, aarowhead (Aaron Hill) wrote…</i></summary><blockquote>

The context is nullable on the support fragment. I guess they recently updated the annotations on the support library to make it clearer to Kotlin whether it was nullable or not nullable.
</blockquote></details>

CMD-OPT-L

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/569)*

**Comment by aarowhead** [comment]
Review status: 32 of 36 files reviewed, 3 unresolved discussions (waiting on @romrell4 and @aarowhead)

---

*[a discussion](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/569#-LFY66QH1yuC2o9_o_Lj:-LFYTv1nAT7tfCOB8zu3:b27n7tk) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Test each and every modified feature (briefly) to make sure that this all works
</blockquote></details>

I found an error with OchMapActivity and SafeWalk but they are fixed now. 

---

*[app/src/main/java/edu/byu/suite/features/testingCenter/controller/ScheduleFragment.kt, line 80 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/569#-LFY5aDU4OMwyG-xW4gz:-LFZ20mo6joEKKAwRMPU:b-okn2zt) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f30136fda47a09dfa91577830cae3e7a35bc389d/app/src/main/java/edu/byu/suite/features/testingCenter/controller/ScheduleFragment.kt#L80)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I think we created an extension to do this. Look for it
</blockquote></details>

We made it optional.

---

*[app/src/main/java/edu/byu/suite/features/testingCenter/controller/ScoresFragment.kt, line 99 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/569#-LFY5dtCDz29jiScFFET:-LFZ4zaiBeEjeG80nqTi:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/9d501ddef01e752d6146576b15d4be43af8960b1/app/src/main/java/edu/byu/suite/features/testingCenter/controller/ScoresFragment.kt#L99)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

CMD-OPT-L
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/569)*

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/569)*

**Pull request merged**
