### PR TITLE
feature/testingCenterCameras -> dev

### PR DESCRIPTION
**Pull request by aarowhead**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/525)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[app/src/main/java/edu/byu/suite/features/campusCameras/CampusCamerasMainActivity.kt, line 12 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WS7yA18b8x1LC-Bp1:-L9WS7yA18b8x1LC-Bp2:b-uhfzba) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/app/src/main/java/edu/byu/suite/features/campusCameras/CampusCamerasMainActivity.kt#L12)):*
> ```Kotlin
>  */
> class CampusCamerasMainActivity: ByuActivity() {
> ```

Looks like your kotlin default is to use spaces instead of tabs. Please change that in your preferences and CMD-OPT-L all of these files

---

*[app/src/main/java/edu/byu/suite/features/campusCameras/CampusCamerasMainActivity.kt, line 19 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WS5a33QKI0zp_GeLz:-L9WS5a33QKI0zp_GeM-:b5pvca3) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/app/src/main/java/edu/byu/suite/features/campusCameras/CampusCamerasMainActivity.kt#L19)):*
> ```Kotlin
>         fragmentManager.beginTransaction().replace(R.id.frameLayout, CamerasGridFragment()).commit()
>     }
> ```

Remove excess new lines

---

*[app/src/main/java/edu/byu/suite/features/testingcenter/controller/TestingCenterMainActivity.java, line 19 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WXb6W8Nxga8VjxXo-:-L9WXb6W8Nxga8VjxXo0:brzypth) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/app/src/main/java/edu/byu/suite/features/testingcenter/controller/TestingCenterMainActivity.java#L19)):*
> ```Java
> 		super.onCreate(savedInstanceState);
> 		setContentView(R.layout.activity_view_pager);
> 		ViewPager viewPager = findViewById(R.id.viewPager);
> ```

Use kotlin extensions

---

*[app/src/main/java/edu/byu/suite/features/testingcenter/controller/TestingCenterMainActivity.java, line 20 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WSJi0E1DuxU94L_f_:-L9WSJi0E1DuxU94L_fa:b-754358) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/app/src/main/java/edu/byu/suite/features/testingcenter/controller/TestingCenterMainActivity.java#L20)):*
> ```Java
> 		setContentView(R.layout.activity_view_pager);
> 		ViewPager viewPager = findViewById(R.id.viewPager);
> 		ByuFragmentPagerAdapter adapter = new ByuFragmentPagerAdapter(getFragmentManager(), new ByuFragment[] {new ScoresFragment(), CamerasGridFragment.Companion.newInstance("TESTING CENTER LINES", "testingCenter"), new ScheduleFragment()});
> ```

I don't think "Companion" should be needed here. Talk to me if you have issues removing it

---

*[app/src/main/java/edu/byu/suite/features/testingcenter/controller/TestingCenterMainActivity.java, line 20 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WSQoRAo6vAByGi9tQ:-L9WSQoRAo6vAByGi9tR:bv6egql) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/app/src/main/java/edu/byu/suite/features/testingcenter/controller/TestingCenterMainActivity.java#L20)):*
> ```Java
> 		setContentView(R.layout.activity_view_pager);
> 		ViewPager viewPager = findViewById(R.id.viewPager);
> 		ByuFragmentPagerAdapter adapter = new ByuFragmentPagerAdapter(getFragmentManager(), new ByuFragment[] {new ScoresFragment(), CamerasGridFragment.Companion.newInstance("TESTING CENTER LINES", "testingCenter"), new ScheduleFragment()});
> ```

Save "TESTING CENTER LINES" and "testingCenter" as static const vals somewhere (wherever makes most sense). Also, are these needed?

---

*[app/src/main/java/edu/byu/suite/features/testingcenter/controller/TestingCenterMainActivity.java, line 27 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WXP8A7p43-zhE84e2:-L9WXP8A7p43-zhE84e3:b-tlczn3) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/app/src/main/java/edu/byu/suite/features/testingcenter/controller/TestingCenterMainActivity.java#L27)):*
> ```Java
> 			public void onPageSelected(int position) {
> 				if (position == 1) {
> 					adapter.executeCodeOnFragment(getFragmentManager(), 1, fragment -> ((CamerasGridFragment) fragment).updateShowingImages());
> ```

In kotlin, the way you cast is using the `as` keyword. For instance, you will want this to be your lambda:
```kotlin
(fragment as? CamerasGridFragment)?.updateShowingImages()
```

---

*[support/src/main/res/layout/camera_feed_cardview.xml, line 8 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WXqHxBcCxMhyEV4hm:-L9WXqHxBcCxMhyEV4hn:b-xv1laq) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/support/src/main/res/layout/camera_feed_cardview.xml#L8)):*
> ```XML
> 											 android:layout_margin="2dp">
> 
> 	<android.support.v7.widget.CardView
> ```

Normally, when using card view, you make that the parent layout. Then, inside of it, you would put your ConstraintLayout. This one, however, doesn't feel like it needs a Constraint layout at all.... Talk to me if you have questions

---

*[support/src/main/res/layout/camera_feed_layout.xml, line 6 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WYTSB45FEpdnoJtu6:-L9WYTSB45FEpdnoJtu7:b-qxmiot) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/support/src/main/res/layout/camera_feed_layout.xml#L6)):*
> ```XML
> 											 android:layout_width="match_parent"
> 											 android:layout_height="match_parent"
> 											 android:layout_gravity="center">
> ```

Why do we need the center gravity? Aren't we constraining everything anyways?

---

*[support/src/main/res/layout/camera_feed_layout.xml, line 12 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WY_Vh0UOlUxwtzh-h:-L9WY_Vh0UOlUxwtzh-i:bqta0x4) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/support/src/main/res/layout/camera_feed_layout.xml#L12)):*
> ```XML
> 		android:layout_width="match_parent"
> 		android:layout_height="match_parent"
> 		android:adjustViewBounds="true"
> ```

What does this one do?

---

*[support/src/main/res/layout/camera_feed_layout.xml, line 23 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WZH7tAZsd7PVYshgA:-L9WZH7tAZsd7PVYshgB:byyygiu) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/support/src/main/res/layout/camera_feed_layout.xml#L23)):*
> ```XML
> 		android:layout_height="0dp"
> 		android:background="@drawable/image_title_gradient"
> 		app:layout_constraintDimensionRatio="4:1"
> ```

Can you show me how to do this?

---

*[support/src/main/res/layout/camera_feed_layout.xml, line 33 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WZMO-8o-v6iFp1lKv:-L9WZMO-8o-v6iFp1lKw:b-jwzlnt) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/support/src/main/res/layout/camera_feed_layout.xml#L33)):*
> ```XML
> 		android:layout_width="0dp"
> 		android:layout_height="2dp"
> 		android:layout_margin="3dp"
> ```

What is this margin doing?

---

*[support/src/main/res/layout/cameras_fragment_recycler_layout.xml, line 7 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WZb1i4qENo8XLG_1W:-L9WZb1i4qENo8XLG_1X:bzbeut3) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/support/src/main/res/layout/cameras_fragment_recycler_layout.xml#L7)):*
> ```XML
> 											 android:layout_height="match_parent">
> 
> 	<ProgressBar
> ```

What is this guy?

---

*[support/src/main/res/layout/cameras_fragment_recycler_layout.xml, line 27 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WZxX_1btLjctNHnTr:-L9WZxX_1btLjctNHnTs:bfxqmj0) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/support/src/main/res/layout/cameras_fragment_recycler_layout.xml#L27)):*
> ```XML
> 		<include
> 			android:id="@+id/camera_feed_full_screen"
> 			layout="@layout/camera_feed_layout"
> ```

So why did you decide to divvy this one out into it's own layout file?

---

*[support/src/main/res/values/colors.xml, line 25 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9W_3H75ep012eXaBuz:-L9W_3H75ep012eXaBv-:b-sv4v70) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/support/src/main/res/values/colors.xml#L25)):*
> ```XML
> 	<color name="textLighter">#37000000</color>
> 	<color name="loginHintTextColor">#55000000</color>
> 	<color name="transparent">#00000000</color>
> ```

Who uses this?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525)*

**Comment by aarowhead** [comment]
Review status: 12 of 16 files reviewed at latest revision, 14 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/campusCameras/CampusCamerasMainActivity.kt, line 12 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WS7yA18b8x1LC-Bp1:-L9fu5T00rlvOKL2b5LK:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/app/src/main/java/edu/byu/suite/features/campusCameras/CampusCamerasMainActivity.kt#L12)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Looks like your kotlin default is to use spaces instead of tabs. Please change that in your preferences and CMD-OPT-L all of these files
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/campusCameras/CampusCamerasMainActivity.kt, line 19 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WS5a33QKI0zp_GeLz:-L9ftL2i7LBZMCI-rbMu:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/app/src/main/java/edu/byu/suite/features/campusCameras/CampusCamerasMainActivity.kt#L19)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove excess new lines
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/testingcenter/controller/TestingCenterMainActivity.java, line 19 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WXb6W8Nxga8VjxXo-:-L9fqFSs4tNYlqewcVIY:bf3yw71) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/app/src/main/java/edu/byu/suite/features/testingcenter/controller/TestingCenterMainActivity.java#L19)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Use kotlin extensions
</blockquote></details>

This is still a java file because I just modified a few lines but I can convert it to Kotlin and use the Kotlin extensions. Should I do that?

---

*[app/src/main/java/edu/byu/suite/features/testingcenter/controller/TestingCenterMainActivity.java, line 20 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WSJi0E1DuxU94L_f_:-L9fqRn2BorFG9ZZUqyK:btpf8rf) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/app/src/main/java/edu/byu/suite/features/testingcenter/controller/TestingCenterMainActivity.java#L20)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I don't think "Companion" should be needed here. Talk to me if you have issues removing it
</blockquote></details>

You need "Companion" when you are accessing a Kotlin static constant from a Java class. It might be worth it to rewrite this class in Kotlin and then I wouldn't need it.

---

*[app/src/main/java/edu/byu/suite/features/testingcenter/controller/TestingCenterMainActivity.java, line 20 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WSQoRAo6vAByGi9tQ:-L9fqoe54NV5uaNUIiCY:b-741jx) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/app/src/main/java/edu/byu/suite/features/testingcenter/controller/TestingCenterMainActivity.java#L20)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Save "TESTING CENTER LINES" and "testingCenter" as static const vals somewhere (wherever makes most sense). Also, are these needed?
</blockquote></details>

I use these to set the fragment title which is used on the testing center viewpager and to set the filter to filter the list for testing center cameras. The idea behind this is that if in the future we want to reuse this fragment in another activity and we wanted to filter out other cameras you would just but the category string in here and it would filter by that.

---

*[app/src/main/java/edu/byu/suite/features/testingcenter/controller/TestingCenterMainActivity.java, line 27 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WXP8A7p43-zhE84e2:-L9frJ10DHU66yB1Jwcl:byu5gld) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/app/src/main/java/edu/byu/suite/features/testingcenter/controller/TestingCenterMainActivity.java#L27)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

In kotlin, the way you cast is using the `as` keyword. For instance, you will want this to be your lambda:
```kotlin
(fragment as? CamerasGridFragment)?.updateShowingImages()
```
</blockquote></details>

Right, maybe I can convert this file to Kotlin.

---

*[support/src/main/res/drawable/image_title_gradient.xml, line 7 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9frOgH7BspEMMFiVQS:-L9frOgH7BspEMMFiVQT:b-cewax2) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/support/src/main/res/drawable/image_title_gradient.xml#L7)):*
> ```XML
> 	<gradient
> 		android:angle="90"
> 		android:endColor="@color/transparent"
> ```

This is where I use the transparent color from the color res folder.

---

*[support/src/main/res/layout/camera_feed_cardview.xml, line 8 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WXqHxBcCxMhyEV4hm:-L9g4Gd-7w-x-y96Cocd:b1u2sks) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/support/src/main/res/layout/camera_feed_cardview.xml#L8)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Normally, when using card view, you make that the parent layout. Then, inside of it, you would put your ConstraintLayout. This one, however, doesn't feel like it needs a Constraint layout at all.... Talk to me if you have questions
</blockquote></details>

I've made it so that the CardView is the parent layout and put a ConstraintLayout inside of it because the layout_constraintDimensionRatio uses it to make it square. I also set constraints on the ProgressBar.

---

*[support/src/main/res/layout/camera_feed_layout.xml, line 6 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WYTSB45FEpdnoJtu6:-L9fuv2l6cmrnMSbcNn_:b-vuyazi) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/support/src/main/res/layout/camera_feed_layout.xml#L6)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why do we need the center gravity? Aren't we constraining everything anyways?
</blockquote></details>

It was unnecessary and has been removed.

---

*[support/src/main/res/layout/camera_feed_layout.xml, line 12 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WY_Vh0UOlUxwtzh-h:-L9fvQ8r9wr33fXhSEKd:bva4pf5) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/support/src/main/res/layout/camera_feed_layout.xml#L12)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What does this one do?
</blockquote></details>

This allows the image view to adjust it view bounds to preserve the aspect ratio of the drawable. It is important for use in the expanded view. Otherwise, the drawable stays really small while the image view fills the screen.

---

*[support/src/main/res/layout/camera_feed_layout.xml, line 23 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WZH7tAZsd7PVYshgA:-L9froC1DDeygFJEV4T9:b-9wik01) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/support/src/main/res/layout/camera_feed_layout.xml#L23)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Can you show me how to do this?
</blockquote></details>

Yes. A simple explanation is that because the width is constrained but the height is not, it will make the height 1/4 of the width. 

---

*[support/src/main/res/layout/camera_feed_layout.xml, line 33 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WZMO-8o-v6iFp1lKv:-L9fw0oMB48nVWtBBk6p:b3198a7) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/support/src/main/res/layout/camera_feed_layout.xml#L33)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What is this margin doing?
</blockquote></details>

This gives the progress bar some room from the edges of the view. I thought it looked better than having it squished against the edge because the progress bar has rounded ends that look weird to me when they are touching the sides of the view.

---

*[support/src/main/res/layout/cameras_fragment_recycler_layout.xml, line 7 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WZb1i4qENo8XLG_1W:-L9fsHuG167o7ufEXeZw:b-pz4mtg) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/support/src/main/res/layout/cameras_fragment_recycler_layout.xml#L7)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What is this guy?
</blockquote></details>

I noticed that on the iOS version of the app there is a loading bar in the center as it loads the list of camera streams (not the camera images itself, just the list of them). This is the same thing. It shows up on the center of the blank screen while it is retrieving the camera streams. Usually it loads fast enough that you don't really see it but it is helpful for slow connections.

---

*[support/src/main/res/layout/cameras_fragment_recycler_layout.xml, line 27 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WZxX_1btLjctNHnTr:-L9fss0Y9OB8L9BnPa8-:b-p7ftlc) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/support/src/main/res/layout/cameras_fragment_recycler_layout.xml#L27)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

So why did you decide to divvy this one out into it's own layout file?
</blockquote></details>

It is the same layout that is used in the card views so I didn't want to copy and past that into here. That way, if we want to change how the progress bar looks, for example, we can just change it in the one layout file and it shows up in the card views and the expanded view.

---

*[support/src/main/res/values/colors.xml, line 25 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9W_3H75ep012eXaBuz:-L9fgvU-4WTh3O3SEWqr:b-oiewzs) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/support/src/main/res/values/colors.xml#L25)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Who uses this?
</blockquote></details>

The gradient for the image view on testing center uses it. I put a comment on the file where it is used.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525)*

**Comment by romrell4** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/testingcenter/controller/TestingCenterMainActivity.java, line 27 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WXP8A7p43-zhE84e2:-L9gCUSUE8iJ3TUtQg_7:b-89817p) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/app/src/main/java/edu/byu/suite/features/testingcenter/controller/TestingCenterMainActivity.java#L27)):*
<details><summary><i>Previously, aarowhead (Aaron Hill) wrote…</i></summary><blockquote>

Right, maybe I can convert this file to Kotlin.
</blockquote></details>

Do it

---

*[app/src/main/java/edu/byu/suite/features/testingcenter/controller/TestingCenterMainActivity.java, line 16 at r2](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9gCOWg-pF-E97OdVIA:-L9gCOWg-pF-E97OdVIB:b-s419mt) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/b0db0078636398133657b810cd006d9d4ab260d7/app/src/main/java/edu/byu/suite/features/testingcenter/controller/TestingCenterMainActivity.java#L16)):*
> ```Java
> public class TestingCenterMainActivity extends ByuActivity {
> 
> 	private static final String TESTING_CENTER_LINES = "TESTING CENTER LINES";
> ```

rename variable and make value title cased

---

*[support/src/main/res/layout/camera_feed_layout.xml, line 33 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WZMO-8o-v6iFp1lKv:-L9gCpTp6tLByAPfVzVB:bhs7p0f) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/support/src/main/res/layout/camera_feed_layout.xml#L33)):*
<details><summary><i>Previously, aarowhead (Aaron Hill) wrote…</i></summary><blockquote>

This gives the progress bar some room from the edges of the view. I thought it looked better than having it squished against the edge because the progress bar has rounded ends that look weird to me when they are touching the sides of the view.
</blockquote></details>

Show this one to me

---

*[support/src/main/res/layout/cameras_fragment_recycler_layout.xml, line 7 at r1](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9WZb1i4qENo8XLG_1W:-L9gCz1b6H8LTQS7QMYf:blehn57) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/f0c8a1c9d92d32d262532d15df0f6030ee09bbde/support/src/main/res/layout/cameras_fragment_recycler_layout.xml#L7)):*
<details><summary><i>Previously, aarowhead (Aaron Hill) wrote…</i></summary><blockquote>

I noticed that on the iOS version of the app there is a loading bar in the center as it loads the list of camera streams (not the camera images itself, just the list of them). This is the same thing. It shows up on the center of the blank screen while it is retrieving the camera streams. Usually it loads fast enough that you don't really see it but it is helpful for slow connections.
</blockquote></details>

Gotcha. Would this be easier to use a view pager for? Or do you like having the progress bar show/hide functionality?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525)*

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[app/src/main/java/edu/byu/suite/features/testingcenter/controller/TestingCenterMainActivity.kt, line 17 at r3](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9ksEJ24QdbjJY0nz50:-L9ksEJ24QdbjJY0nz51:bt4y3tz) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/17a14a13a618b3a5520f3b20784b9737989eb3ab/app/src/main/java/edu/byu/suite/features/testingcenter/controller/TestingCenterMainActivity.kt#L17)):*
> ```Kotlin
> 	companion object {
> 
> 		const val LINES_TITLE = "Testing Center Lines"
> ```

Can these be private?

---

*[support/src/main/res/layout/cameras_fragment_recycler_layout.xml, line 4 at r3](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9ksWT1B4ZAnXOQ6UIP:-L9ksWT1B4ZAnXOQ6UIQ:bf7b7i2) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/17a14a13a618b3a5520f3b20784b9737989eb3ab/support/src/main/res/layout/cameras_fragment_recycler_layout.xml#L4)):*
> ```XML
> <ViewSwitcher
> 	xmlns:android="http://schemas.android.com/apk/res/android"
> 	android:id="@+id/loading_grid_view_switcher"
> ```

CMD-OPT-L

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525)*

**Comment by aarowhead** [comment]
Review status: 15 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/testingcenter/controller/TestingCenterMainActivity.kt, line 17 at r3](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9ksEJ24QdbjJY0nz50:-L9pybvS9eXjk5a5l1FQ:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/17a14a13a618b3a5520f3b20784b9737989eb3ab/app/src/main/java/edu/byu/suite/features/testingcenter/controller/TestingCenterMainActivity.kt#L17)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Can these be private?
</blockquote></details>

Done.

---

*[support/src/main/res/layout/cameras_fragment_recycler_layout.xml, line 4 at r3](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525#-L9ksWT1B4ZAnXOQ6UIP:-L9pybhxBd6gODZXzQvo:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/17a14a13a618b3a5520f3b20784b9737989eb3ab/support/src/main/res/layout/cameras_fragment_recycler_layout.xml#L4)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

CMD-OPT-L
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/byu-oit/android-byu-suite-v2/525)*

**Pull request merged**
