### PR TITLE
hotfix/warnings -> dev

### PR DESCRIPTION
**Pull request by geogor37**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/538)

### CODE REVIEW

**Comment by geogor37** [comment]
This branch is for the task in the Visual Task Board that says to remove all possible warnings in Android.  Since there are hundreds of warnings I thought it would be more productive to resolve the warnings in waves, rather than all at once in a single revision.  So all the changes in the current revision should be somewhat related, which will hopefully make things go faster :slightly_smiling_face: 

---

Review status: 0 of 26 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/538#-:-LBMCrl06Qmm5OJEIf_j:bqxnwpy)*

**Comment by romrell4** [comment]
Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[app/src/main/res/layout/cougar_cash_activity_main.xml, line 34 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/538#-LBMuEP72flsKk0Hq8eR:-LBMuEP72flsKk0Hq8eS:bqta0x4) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/22b9e03d372a8f5d0c41abef9c8a387f303bd252/app/src/main/res/layout/cougar_cash_activity_main.xml#L34)):*
> ```XML
> 		app:layout_constraintHorizontal_bias="0.0"
> 		app:layout_constraintTop_toBottomOf="@+id/toolbar"
> 		tools:targetApi="lollipop" />
> ```

What does this one do?

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/538)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/res/layout/cougar_cash_activity_main.xml, line 34 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/538#-LBMuEP72flsKk0Hq8eR:-LBNJLoE7IejTpy7LePg:bd1zy0e) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/22b9e03d372a8f5d0c41abef9c8a387f303bd252/app/src/main/res/layout/cougar_cash_activity_main.xml#L34)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What does this one do?
</blockquote></details>

Without this the IDE gives a warning that the elevation attribute only exists in API 21 and above.

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/538)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[app/src/main/res/layout/cougar_cash_activity_main.xml, line 34 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/538#-LBMuEP72flsKk0Hq8eR:-LBRSQA29e4t35WCgQHR:bb384oz) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/22b9e03d372a8f5d0c41abef9c8a387f303bd252/app/src/main/res/layout/cougar_cash_activity_main.xml#L34)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

Without this the IDE gives a warning that the elevation attribute only exists in API 21 and above.
</blockquote></details>

Is that an issue, as we target 17+?

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/538)*

**Comment by geogor37** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/res/layout/cougar_cash_activity_main.xml, line 34 at r1](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/538#-LBMuEP72flsKk0Hq8eR:-LBRbPyEBny-fMcDdaMA:bonx6vq) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/22b9e03d372a8f5d0c41abef9c8a387f303bd252/app/src/main/res/layout/cougar_cash_activity_main.xml#L34)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Is that an issue, as we target 17+?
</blockquote></details>

It just means that any phone using 20 or below won't see the elevation effect, but the app will still run fine.

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/538)*

**Pull request merged**
