### PR TITLE
hotfix/personDirectory -> dev

### PR DESCRIPTION
**Pull request by geogor37**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/496)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonInfoActivity.java, line 41 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/496#-L0uCE3tmhC3gQeQEKqh:-L0uCE3tmhC3gQeQEKqi:b-tm287r) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/201d91bdae7f29445f014a63a9c09e210011a691/app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonInfoActivity.java#L41)):*
> ```Java
> 	@SuppressLint("MissingSuperCall")
> 	protected void onCreate(Bundle savedInstanceState) {
> 		onCreate(savedInstanceState, R.layout.person_directory_activity_info);
> ```

Add `super.` to the beginning (just to be explicit)

---

*[app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonInfoActivity.java, line 55 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/496#-L0uCrA5odHPu0PbNp8R:-L0uCrA5odHPu0PbNp8S:bgmop6j) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/201d91bdae7f29445f014a63a9c09e210011a691/app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonInfoActivity.java#L55)):*
> ```Java
> 	}
> 
> 	private List<Object> getAddressList(Person person) {
> ```

rename `getRows(Person person)`

---

*[app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonInfoActivity.java, line 113 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/496#-L0ufQOwcTH81tJHeWGq:-L0ufQOwcTH81tJHeWGr:bte1rdb) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/201d91bdae7f29445f014a63a9c09e210011a691/app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonInfoActivity.java#L113)):*
> ```Java
> 		boolean addressSet = false;
> 
> 		for (Object item : addressList) {
> ```

I'm confused about why this got changed from Address to Object... Talk to me when you get a second

---

*[app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonInfoActivity.java, line 114 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/496#-L0ueEjgcL6PWzEgjHzP:-L0ueEjgcL6PWzEgjHzQ:b-t4tp3b) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/201d91bdae7f29445f014a63a9c09e210011a691/app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonInfoActivity.java#L114)):*
> ```Java
> 
> 		for (Object item : addressList) {
> 			if (item.getClass() == Address.class) {
> ```

instead use item.isAssignableFrom(Address.class) or item instanceOf Address

---

*[app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonInfoActivity.java, line 180 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/496#-L0ufaXjpIZuGWB2S1nv:-L0ufaXjpIZuGWB2S1nw:b-gwdk4e) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/201d91bdae7f29445f014a63a9c09e210011a691/app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonInfoActivity.java#L180)):*
> ```Java
> 			@Override
> 			public void bind(Object data, ByuClickListener<Object> listener) {
> 				if (data.getClass() == String.class) {
> ```

isAssignableFrom

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/496)*

**Comment by geogor37** [comment]
Review status: 5 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonInfoActivity.java, line 41 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/496#-L0uCE3tmhC3gQeQEKqh:-L0zkQjl2H7vCojXSyeS:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/201d91bdae7f29445f014a63a9c09e210011a691/app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonInfoActivity.java#L41)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Add `super.` to the beginning (just to be explicit)
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonInfoActivity.java, line 55 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/496#-L0uCrA5odHPu0PbNp8R:-L0zlo1fOXxtPYGg_388:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/201d91bdae7f29445f014a63a9c09e210011a691/app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonInfoActivity.java#L55)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

rename `getRows(Person person)`
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonInfoActivity.java, line 113 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/496#-L0ufQOwcTH81tJHeWGq:-L0zlXEyaNEa1V6PxuHy:b29eu7a) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/201d91bdae7f29445f014a63a9c09e210011a691/app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonInfoActivity.java#L113)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I'm confused about why this got changed from Address to Object... Talk to me when you get a second
</blockquote></details>

We talked about it

---

*[app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonInfoActivity.java, line 114 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/496#-L0ueEjgcL6PWzEgjHzP:-L0zkifX6Tw3CY6L5Jvm:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/201d91bdae7f29445f014a63a9c09e210011a691/app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonInfoActivity.java#L114)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

instead use item.isAssignableFrom(Address.class) or item instanceOf Address
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonInfoActivity.java, line 180 at r1](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/496#-L0ufaXjpIZuGWB2S1nv:-L0zkxli6PQ7Q-zqf77F:b-xdanux) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/201d91bdae7f29445f014a63a9c09e210011a691/app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonInfoActivity.java#L180)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

isAssignableFrom
</blockquote></details>

Done.  It wouldn't let me use isAssignableFrom, so I used instanceOf instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/496)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonInfoActivity.java, line 165 at r2](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/496#-L13KVZFzXvVzZP2Mmp4:-L13KVZGj7C9l5jeIUhd:b-7wqecq) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/31917dd5ae8c85570054e9bf993c1d4d9da48ff8/app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonInfoActivity.java#L165)):*
> ```Java
> 
> 		private class AddressViewHolder extends ByuViewHolder<Object> {
> 			TextView header;
> ```

Let's make these private. They shouldn't need package access. The constructor will need package-private access, though

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/496)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit/android-byu-suite-v2/496)*

**Pull request merged**
