### PR TITLE
hotfix/oauth -> dev

### PR DESCRIPTION
**Pull request by geogor37**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/557)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/557#-LDHaFJiClQkJh53Ra52:-LDHaFJjEADplH2H0FY1:bupq2q1) (no related file):*
Let's wait to merge this until we decided whether to remove the auto sync

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/557)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java, line 331 at r2](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/557#-LDHs3yE2PSgGogD9JT3:-LDHs3yE2PSgGogD9JT4:bjqav8g) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a976b6f3fb7829e8a10da837cce539e9dc0d20d4/app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java#L331)):*
> ```Java
> 			// this attempts to load their name and other account info
> 			AccountInformation.sync(this, account, result -> {
> 				if (result != null) {
> ```

Add an `&&` here that will only call updateLoginStatus if the preferred name changed

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/557)*

**Comment by geogor37** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java, line 331 at r2](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/557#-LDHs3yE2PSgGogD9JT3:-LDHvdlNE1rWS9GpFtDq:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a976b6f3fb7829e8a10da837cce539e9dc0d20d4/app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java#L331)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Add an `&&` here that will only call updateLoginStatus if the preferred name changed
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/557)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java, line 331 at r2](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/557#-LDHs3yE2PSgGogD9JT3:-LDHwitl9_yPL8drKZQg:bnewba7) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a976b6f3fb7829e8a10da837cce539e9dc0d20d4/app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java#L331)):*
<details><summary><i>Previously, geogor37 (Geoff Gorham) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oh wow... that was a lot more complicated than I thought... I was hoping for something closer to this:

```java
if (result != null && result.getPreferredName() != null && result.getPreferredName().equals(accountInformation.getPreferredName()) {
...
}
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/557)*

**Comment by geogor37** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java, line 331 at r2](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/557#-LDHs3yE2PSgGogD9JT3:-LDI49a6BlK2WLXROJBP:b-896fix) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/a976b6f3fb7829e8a10da837cce539e9dc0d20d4/app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java#L331)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Oh wow... that was a lot more complicated than I thought... I was hoping for something closer to this:

```java
if (result != null && result.getPreferredName() != null && result.getPreferredName().equals(accountInformation.getPreferredName()) {
...
}
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/557)*

**Comment by romrell4** [comment]
Reviewed 5 of 6 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java, line 331 at r4](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/557#-LDIE_JU99Dt9Nlx_qCg:-LDIE_JU99Dt9Nlx_qCh:b5cyrh7) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/df4da24fb43237e1f1ec8ab81a1f1a94703ea9c1/app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java#L331)):*
> ```Java
> 			// this attempts to load their name and other account info
> 			AccountInformation.sync(this, account, result -> {
> 				if (result != null && result.getPreferredName() != null && accountInformation != null && !result.getPreferredName().equals(accountInformation.getPreferredName())) {
> ```

Add comment

---

*[support/src/main/java/edu/byu/support/login/LoginActivity.java, line 53 at r4](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/557#-LDIGLQ5Cb1x0s_EJKLF:-LDIGLQ5Cb1x0s_EJKLG:b-lwl866) ([raw file](https://github.com/byu-oit/android-byu-suite-v2/blob/df4da24fb43237e1f1ec8ab81a1f1a94703ea9c1/support/src/main/java/edu/byu/support/login/LoginActivity.java#L53)):*
> ```Java
> 				OAuthToken token = response.body();
> 				if (token == null || !token.isValid()) {
> 					onFailure(call, new ByuError(getString(R.string.invalid_token_message)));
> ```

Use empty string

---


*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/557)*

**Comment by romrell4** [comment]
Reviewed 2 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/byu-oit/android-byu-suite-v2/557)*

**Pull request merged**
